- MahApps.Metro/Controls/MetroWindow.cs
I hate it when the user can move the window with a grid at the window. This property allows me to disable that.
> Allows the user to disable the window dragging

- MahApps.Metro/Behaviours/BorderlessWindowBehavior.cs
- MahApps.Metro/Microsoft.Windows.Shell/WindowChromeWorker.cs
Move AutoHidden taskbar handling code into WindowChromeWorker. 
GetMinMaxInfo hook shouldn't be needed in BorderlessWindowBehavior any longer.
> Don't maximize over autohidden taskbar

- MahApps.Metro/Behaviours/BorderlessWindowBehavior.cs
- MahApps.Metro/Behaviours/GlowWindowBehavior.cs
- MahApps.Metro/Controls/GlowWindow.xaml.cs
- MahApps.Metro/Microsoft.Windows.Shell/Standard/NativeMethods.cs
- MahApps.Metro/Microsoft.Windows.Shell/WindowChrome.cs
- MahApps.Metro/Microsoft.Windows.Shell/WindowChromeWorker.cs
- MahApps.Metro/Native/ABEdge.cs
- MahApps.Metro/Native/ABMsg.cs
- MahApps.Metro/Native/APPBARDATA.cs
- MahApps.Metro/Native/Constants.cs
- MahApps.Metro/Native/UnsafeNativeMethods.cs
- docs/release-notes/1.1.0.md
- samples/MetroDemo/MainWindow.xaml
- samples/MetroDemo/MainWindow.xaml.cs
this pr should fix the missing minimize and maximize/restore animations.
thx to @AdditionalPylons for the inspiration and work to solve this issue (hopefully).
limitations goes to a window that ignores the taskbar (no animation)
Closes #1539 
this closes #1275 too (Issues when switching MetroWindow between monitors while maximized)
> Min, Restore/Max animation fix

- MahApps.Metro/Themes/MetroWindow.xaml
We were using an ItemsControl inside our ItemsControl and binding the
nested ItemsControl's source to our ItemsControl's source. Wut?
> Remove redundant ItemsControl inside our ItemsControl

- MahApps.Metro/Themes/Dialogs/ProgressDialog.xaml
Should be "Arrow" instead of inheriting "Wait".
> Fix the cursor of the Button in ProgressDialog

- MahApps.Metro/Styles/Clean/CleanWindow.xaml
- MahApps.Metro/Styles/VS/Window.xaml
- docs/release-notes/1.1.0.md
with this we can put the complete MahApps styles only in a window.
and only this window gets MahApps themed.
> add the buttons resource to window style resources

- MahApps.Metro/Controls/WindowSettings.cs
- docs/release-notes/1.1.0.md
- Added a `UpgradeSettings` property to `IWindowPlacementSettings`, which defaults to true
- Added a `void Upgrade()` method to `IWindowPlacementSettings`, which is implemeneted by `ApplicationSettingsBase`
Closes #1736
> Upgrade WindowPlacementSettings on version change

- MahApps.Metro/Controls/Dialogs/BaseMetroDialog.cs
- MahApps.Metro/Controls/Dialogs/InputDialog.cs
- MahApps.Metro/Controls/Dialogs/LoginDialog.cs
- MahApps.Metro/Controls/Dialogs/MessageDialog.cs
- MahApps.Metro/Themes/Dialogs/BaseMetroDialog.xaml
there is a little bug with accented dialogs and the text of the buttons, so this should fix it...
Closes #1755
> fix preservetext for buttons in dialogs

- MahApps.Metro/Controls/Helper/TextBoxHelper.cs
Subscribe to clear button even if control is already loaded. Fixes #1764
> Subscribe to clear button even if control is already loaded. Fixes #1764

- MahApps.Metro/Controls/SplitButton.cs
These fixes make SplitButton work a little bit better as a drop in replacement for ComboBox
> Fix SplitButton SelectedIndex and SelectedItem

- MahApps.Metro/Behaviours/BorderlessWindowBehavior.cs
- MahApps.Metro/Controls/GlowWindow.xaml.cs
- MahApps.Metro/Controls/MetroWindow.cs
- MahApps.Metro/Styles/Clean/CleanWindow.xaml
- MahApps.Metro/Themes/Glow.xaml
- MahApps.Metro/Themes/MetroWindow.xaml
- samples/MetroDemo/MainWindow.xaml
- samples/MetroDemo/MainWindow.xaml.cs
after this pr it's possible to have
- border
+ `BorderBrush="{DynamicResource AccentColorBrush}"`
- glow with border
+ `GlowBrush="{DynamicResource AccentColorBrush}"`
- glow without border
+ `BorderThickness="0"`
+ `GlowBrush="{DynamicResource AccentColorBrush}"`
- drop shadow
+ `BorderThickness="0"`
+ `GlowBrush="Black"`
- or drop shadow with
+ `EnableDWMDropShadow="True"`
Closes Window loses shadow [EnableDWMDropShadow] #1791
> Use the Glow to enable drop shadow (EnableDWMDropShadow)

- MahApps.Metro/Themes/MetroTabItem.xaml
> Added TabControlHelper.IsUnderlined to MetroTabItem

- MahApps.Metro/Controls/Flyout.cs
- MahApps.Metro/Themes/Flyout.xaml
- samples/MetroDemo/ExampleWindows/FlyoutDemo.xaml
- samples/MetroDemo/ExampleWindows/FlyoutDemo.xaml.cs
- 2 new properties for `Flyout`
+ `public FrameworkElement FocusedElement`
+ `public bool AllowFocusElement` default to `True`
- first try focus FocusedElement
- try focus first element from content
- try focus first element from header
> Flyout focus enhancement

- MahApps.Metro/Styles/Controls.DataGrid.xaml
Now we can use style like this
```csharp
<Style x:Key="RowHeaderStyle" TargetType="DataGridRowHeader"
BasedOn="{StaticResource MetroDataGridRowHeader}">
<Setter Property="HorizontalContentAlignment" Value="Center" />
</Style>
```
```csharp
<DataGrid RowHeaderStyle="{StaticResource RowHeaderStyle}" />
```
> Added alignment properties for MetroDataGridRowHeader

- MahApps.Metro/Styles/Controls.DataGrid.xaml
Now grippers displayed in rowheaders.
> fix Gripper for MetroDataGridRowHeader

- MahApps.Metro/Themes/MetroWindow.xaml
if you ever wondered why you can't resize a `MetroWindow` on the right top or left top (if there is a icon), this pr fix this issue :-P
> yes, we need a really good HitTest control

- MahApps.Metro/Controls/RangeSlider.cs
The changes allow to use a custom format for the tooltip. For example, I
want that the user can choose a timespan (ms). The tooltip just shows
large numbers. With a converter, the tooltip can display the value in a
time format (mm:ss) which is much better to read for the user.
> Add tooltip text converter to RangeSlider

- MahApps.Metro/Controls/NumericUpDown.cs
[Fix] If in NumericUpDown the property IsReadOnly is set to true, then changing the values by clicking + and - Buttons is still possible
As you can see in https://github.com/MahApps/MahApps.Metro/blob/master/MahApps.Metro/Themes/NumericUpDown.xaml#L120 the only that disables the change of the value is the Trigger. Now even if the Style is customized and this kind of Trigger is not set, then the Change of value is not possible.
> Fix IsReadonly issue

- MahApps.Metro/Styles/Controls.ListBox.xaml
The Margin of ContentPresenter in MetroListBoxItem should inherit {TemplateBinding Padding}, and let developer use the Padding the change the Margin of ContentPresenter
> The Margin of ContentPresenter in MetroListBoxItem

- MahApps.Metro/Behaviours/PasswordBoxBindingBehavior.cs
- MahApps.Metro/Controls/Dialogs/LoginDialog.cs
- MahApps.Metro/Converters/StringToVisibilityConverter.cs
- MahApps.Metro/MahApps.Metro.NET45.csproj
- MahApps.Metro/MahApps.Metro.csproj
- MahApps.Metro/Styles/Controls.PasswordBox.xaml
- MahApps.Metro/Themes/Dialogs/LoginDialog.xaml
- samples/MetroDemo/MainWindow.xaml
- samples/MetroDemo/MainWindow.xaml.cs
> New try for LoginDialog Password Preview Feature

- MahApps.Metro/Controls/Dialogs/BaseMetroDialog.cs
- MahApps.Metro/Controls/Dialogs/DialogManager.cs
- samples/MetroDemo/MainWindow.xaml
- samples/MetroDemo/MainWindow.xaml.cs
As discussed in issue #1910, the ShowMetroDialogAsync method has now the same behaviour as the ShowMessageAsync has. If you await the returned task, it will wait until the dialog is gone.
This pull request contains the necessary changes and adds also a demo of this new capbability to the show case.
The now working code in the show-case pretty much sais all:
```csharp
await this.ShowMetroDialogAsync(dialog);
await dialog.WaitUntilUnloadedAsync(); // Just call await here to wait for the dialog to go away
// This message box is displayed after the dialog has been closed by the user
await this.ShowMessageAsync("Dialog gone", "The custom dialog has closed");
```
> ShowMetroDialogAsync - Dialog is awaitable

- MahApps.Metro/Controls/Dialogs/LoginDialog.cs
Adds the ability to set an initial password in the login dialog.  Use case is if a password is stored  it can be retrieved "displayed" in the login dialog the next time it is opened.
> Add support for initial password in login dialog

- MahApps.Metro/Microsoft.Windows.Shell/WindowChromeWorker.cs
Closes #1924 resize to fullscreen with FlowDirection="RightToLeft" is causing problems.
> fix using window FlowDirection="RightToLeft"

- MahApps.Metro/Controls/Dialogs/BaseMetroDialog.cs
fixed by handle theme in the loaded event
Closes #1931 Modal dialogs not showing in Visual Studio plugin
> fix for HandleTheme getting possible System.NullReferenceException

- MahApps.Metro/Behaviours/BorderlessWindowBehavior.cs
- MahApps.Metro/Styles/Controls.TabControl.xaml
- MahApps.Metro/Styles/Controls.TreeView.xaml
- MahApps.Metro/Themes/MetroContentControl.xaml
- MahApps.Metro/Themes/MetroWindow.xaml
- samples/MetroDemo/ExampleViews/SelectionExamples.xaml
this pr fixes a nasty behavior using the `UseLayoutRounding`. using this with the `MetroWindow` style produces blurred paths, e.g. the arrows in a `TreeView`.
omg WPF, lessons learned...
**before**
**after**
Closes #1907 Blurred arrows in TreeView
> fix blurred arrows in TreeView

- MahApps.Metro/Behaviours/BorderlessWindowBehavior.cs
- MahApps.Metro/Controls/MetroWindow.cs
- MahApps.Metro/Controls/MetroWindowHelpers.cs
...the title says...
Closes #1832 Corner resize doesn't work with glow border or drop shadow
> fix ResizeGrip usage by setting the WindowChrome ResizeGripDirection

- MahApps.Metro/Microsoft.Windows.Shell/Standard/NativeMethods.cs
- MahApps.Metro/Microsoft.Windows.Shell/WindowChromeWorker.cs
- samples/MetroDemo/MainWindow.xaml
... the title says...
Closes #1912 Minimized and not ShowInTaskbar shows windows buttons command
**before**
**after**
(the not showing right MahApps window button commands will be fixed in another pr)
> fix wrong overlapping window button commands with ShowInTaskbar=False

- MahApps.Metro/Themes/Dialogs/BaseMetroDialog.xaml
- MahApps.Metro/Themes/Dialogs/InputDialog.xaml
- MahApps.Metro/Themes/Dialogs/LoginDialog.xaml
- MahApps.Metro/Themes/Dialogs/MessageDialog.xaml
- MahApps.Metro/Themes/Dialogs/ProgressDialog.xaml
- samples/MetroDemo/MainWindow.xaml
fix the static usage of font size in dialogs
so it's now possible to override these values
```xaml
<System:Double x:Key="DialogTitleFontSize">26</System:Double>
<System:Double x:Key="DialogMessageFontSize">15</System:Double>
```
> Dynamic fontsize for dialogs

- MahApps.Metro/Controls/Dialogs/DialogCoordinator.cs
- MahApps.Metro/Controls/Dialogs/DialogParticipation.cs
- MahApps.Metro/Controls/Dialogs/IDialogCoordinator.cs
- MahApps.Metro/MahApps.Metro.NET45.csproj
- MahApps.Metro/MahApps.Metro.csproj
- samples/MetroDemo/ExampleWindows/FlyoutDemo.xaml.cs
- samples/MetroDemo/MainWindow.xaml
- samples/MetroDemo/MainWindow.xaml.cs
- samples/MetroDemo/MainWindowViewModel.cs
Using this mechanism you can easily use the MahApps dialogs from a view model.  It is agbostic to whatever DI framework you may or may not be using.
To use you add an attached property in your XAML, which will tie the Binding (your view model) to the Window:
```
Dialog:DialogParticipation.Register="{Binding}"
```
Then the DialogCoordinator can be called from your view model, providing it with a context (your view model), it will know which Window to use to show the dialog.
```
_dialogCoordinator.ShowInput(this).ContinueWith(t => Console.WriteLine(t.Result));
```
__outstanding:__ I've added to the demo app, but only a single dialog type right now.  If you accept this PR I will build out the interface for the other dialog types.
> add mechanism for easy access of a dialog from a view model

- MahApps.Metro/Controls/ToggleSwitch.cs
- MahApps.Metro/Controls/ToggleSwitchButton.cs
- MahApps.Metro/Converters/OffOnConverter.cs
- MahApps.Metro/Styles/Controls.Buttons.xaml
- MahApps.Metro/Styles/Fonts.xaml
- MahApps.Metro/Themes/ToggleSwitch.xaml
- new dependency property `ToggleSwitchButtonStyle`
- `BorderThickness` and `BorderBrush` for toggle button style now customizable
- new font keys
+ `ToggleSwitchFontFamily` and `ToggleSwitchHeaderFontFamily`
+ `ToggleSwitchFontSize`and `ToggleSwitchHeaderFontSize`
- new dependency properties to change brushes
+ `OnSwitchBrush` and `OffSwitchBrush`
+ `ThumbIndicatorBrush` and `ThumbIndicatorDisabledBrush`
- new dependency property `ThumbIndicatorWidth`
- `Validation.ErrorTemplate` support
- Keyboard focus if the `ToggleSwitch` itself or the toggle button was clicked
- Fixed on/off label binding issue #1867
- introduce commands for mvvm usage
+ `CheckChangedCommand`, `CheckedCommand` and `UnCheckedCommand`
+ `CheckChangedCommandParameter`, `CheckedCommandParameter` and …
> ToggleSwitch improvements and fixes

- MahApps.Metro/Controls/Helper/ComboBoxHelper.cs
- MahApps.Metro/Styles/Controls.ComboBox.xaml
so it's now possible to get/set
- `MaxLength`
- `CharacterCasing`
of the inner `TextBox` of a `ComboBox`
> 2 new attached properties for ComboBoxHelper

- MahApps.Metro/Styles/Controls.ComboBox.xaml
- samples/MetroDemo/ExampleViews/SelectionExamples.xaml
watermark (not editable and not focused)
watermark (focused)
Closes #1953 Watermark on ComboBox where IsEditable="False"
> Watermark for non editable combobox

- MahApps.Metro/Controls/Helper/TextBoxHelper.cs
- MahApps.Metro/Controls/NumericUpDown.cs
- MahApps.Metro/Themes/NumericUpDown.xaml
- fixed focus problem
- new `SelectAllOnFocus` dependency property (with default to true like ComboBox)
Closes #1903 NumericUpDown won't focus programatically
> NumericUpDown focusing fix

- MahApps.Metro/Controls/DataGridNumericUpDownColumn.cs
- MahApps.Metro/Controls/NumericUpDown.cs
- MahApps.Metro/Themes/NumericUpDown.xaml
Add the possibility to define the UpDownButtons width in
DataGridNumericUpDownColumn. This can be usefull for a touch application
because by default, a width of 20 is not enough because the buttons are
too close
> Possiblity to define the UpDownButtons width

- MahApps.Metro/Controls/MetroWindow.cs
- MahApps.Metro/Controls/WindowButtonCommands.cs
- MahApps.Metro/Controls/WindowCommands.cs
- Mahapps.Metro.Tests/MetroWindowTest.cs
> jit compiler limitation fix for #1919

- MahApps.Metro/Styles/Controls.CheckBox.xaml
- MahApps.Metro/Styles/Controls.GroupBox.xaml
- MahApps.Metro/Styles/Controls.RadioButton.xaml
- docs/release-notes/1.2.0.md
- samples/MetroDemo/ExampleViews/ButtonsExample.xaml
- samples/MetroDemo/ExampleViews/TabControlExamples.xaml
The styles for CheckBox, RadioButton, and GroupBox are missing `RecognizesAccessKey="true"`, so keyboard navigation fails when using shortcuts (`_` in front of access keys)
> RecognizesAccessKey in styles for CheckBox, RadioButton, and GroupBox

- MahApps.Metro/Controls/MetroWindow.cs
Because of .NET 4.0 compatibility, MahApps.Metro can't use `Task.FromResult`. However, just returning `new System.Threading.Tasks.Task(() => { })` doesn't help, because it won't execute the task. Instead, you should use a `TaskCompletionSource`. Since both methods in question already ise a TCS, in the PR I moved their creations to an earlier point and re-used them.
I noticed this issue when I tried to open two dialog at once, a continuation for the returned tasks never run.
> creating a Task instance doesn't execute it

- MahApps.Metro/Behaviours/BorderlessWindowBehavior.cs
- MahApps.Metro/Microsoft.Windows.Shell/WindowChromeWorker.cs
- MahApps.Metro/Native/UnsafeNativeMethods.cs
- samples/MetroDemo/MetroDemo.NET45.csproj
Closes #1993 Why did I get an errorwhen I run the sample on windows 8.1?
> Fix for possible System.OverflowException with IntPtr.ToInt32() on Win 8 or Win Server 2012

- MahApps.Metro/Controls/Helper/ControlsHelper.cs
- MahApps.Metro/Controls/Helper/ExpanderHelper.cs
- MahApps.Metro/Converters/ThicknessBindingConverter.cs
- MahApps.Metro/MahApps.Metro.NET45.csproj
- MahApps.Metro/MahApps.Metro.csproj
- MahApps.Metro/Styles/Clean/CleanGroupBox.xaml
- MahApps.Metro/Styles/Controls.Expander.xaml
- MahApps.Metro/Styles/Controls.GroupBox.xaml
- samples/MetroDemo/ExampleWindows/CleanWindowDemo.xaml
+ 4 new attached dependency properties `HeaderUpStyle`, `HeaderDownStyle` and `HeaderLeftStyle`, `HeaderRightStyle`. so it's now possible to create your own header toggle styles without rewriting the `Expander` style
+ the `Expander` uses now the new value converter `ThicknessBindingConverter`, so setting the `BorderThickness` is much better than before
and for `GroupBox`
> Expander enhancements

- MahApps.Metro/Controls/Dialogs/DialogManager.cs
- MahApps.Metro/Controls/MetroWindow.cs
- MahApps.Metro/Styles/Clean/CleanWindow.xaml
- MahApps.Metro/Themes/MetroWindow.xaml
- docs/release-notes/1.2.0.md
- samples/MetroDemo/MainWindow.xaml
- samples/MetroDemo/MainWindow.xaml.cs
This PR adds support for multiple dialogs at once as requested in #1974. There can only be one active dialog, and there's no support for switching between dialogs. It's like a stack of dialogs.
I hope the changes are self-explanatory.
However, there's one breaking change: previously the `MetroWindow`'s template contained a part named `PART_MetroDialogContainer`, now there are two parts named `PART_MetroActiveDialogContainer` and `PART_MetroInactiveDialogsContainer`. When someone has created his own style for `MetroWindow` it will break.
> support for multiple dialogs (fixes #1974)

- MahApps.Metro/Controls/MetroProgressBar.cs
- samples/MetroDemo/ExampleViews/DataGridExamples.xaml
- samples/MetroDemo/ExampleViews/SliderProgressExamples.xaml
this PR fix this two possible animation warnings, so a DataGrid with a `MetroProgressBar` should now be faster!
```
System.Windows.Media.Animation Warning: 6 : Unable to perform action because the specified Storyboard was never applied to this object for interactive control.; Action='Stop'; Storyboard='System.Windows.Media.Animation.Storyboard'; Storyboard.HashCode='39750236'; Storyboard.Type='System.Windows.Media.Animation.Storyboard'; TargetElement='System.Windows.Controls.Grid'; TargetElement.HashCode='19146950'; TargetElement.Type='System.Windows.Controls.Grid'
```
```
System.Windows.Media.Animation Warning: 6 : Unable to perform action because the specified Storyboard was never applied to this object for interactive control.; Action='Remove'; …
```
> MetroProgressBar System.Windows.Media.Animation warning fix

- MahApps.Metro/Controls/RangeSlider.cs
Had an issue with a range slider where I could not move the thumb all the way to the right. In this case CalculateNextTick() moved into the !IsDoubleCloseToInt() code and that did not respect the passed in distance.
> FIX: issue with RangeSlider with binding and values between ticks

- MahApps.Metro/Controls/Dialogs/BaseMetroDialog.cs
- MahApps.Metro/Controls/Dialogs/InputDialog.cs
- MahApps.Metro/Controls/Dialogs/LoginDialog.cs
- MahApps.Metro/Controls/Dialogs/MessageDialog.cs
- MahApps.Metro/Controls/Dialogs/ProgressDialog.cs
- MahApps.Metro/Controls/Dialogs/ProgressDialogController.cs
As a possible solution for #2018 I implemented support for `CancellationToken` to cancel dialogs.
I added a `CancellationToken` to `MetroDialogSettings` and the handling of that token to `InputDialog`, `LoginDialog`, `MessageDialog`, and `ProgressDialog`. `ProgressDialog`'s implementation is different from the others in that it only sets `ProgressDialogManager.IsCanceled` to `true`. 
Of course, users of MahApps.Metro deriving their dialogs from `BaseMetroDialog` have to implement their own handling of the cancellation.
```c#
var cancellationTokenSource = new CancellationTokenSource();
var mySettings = new MetroDialogSettings()
{
// ...
CancellationToken = cancellationTokenSource.Token
};
```
Here's an example using a timer to cancel the message box (by calling …
> [RFC] Support for CancellationToken to cancel dialogs

- MahApps.Metro/Controls/ProgressRing.cs
- docs/release-notes/1.2.0.md
- samples/MetroDemo/ExampleViews/SliderProgressExamples.xaml
I second that  `ProgressRing.IsActive` should be `true` by default.
This fixes #2029
> Changed default value of ProgressRing.IsActive to true

- MahApps.Metro/Controls/Dialogs/BaseMetroDialog.cs
- MahApps.Metro/Controls/Dialogs/DialogManager.cs
- MahApps.Metro/Controls/Dialogs/InputDialog.cs
- MahApps.Metro/Controls/Dialogs/LoginDialog.cs
- MahApps.Metro/Controls/Dialogs/MessageDialog.cs
- MahApps.Metro/Styles/Controls.PasswordBox.xaml
- MahApps.Metro/ThemeManager.cs
- MahApps.Metro/Themes/Dialogs/InputDialog.xaml
- MahApps.Metro/Themes/Dialogs/LoginDialog.xaml
- MahApps.Metro/Themes/Dialogs/MessageDialog.xaml
- samples/MetroDemo/MainWindow.xaml.cs
- DialogSettings property is now public
- load Controls, Fonts and Colors resource dictionries to prevent
System.Windows.ResourceDictionary Warning: 9
- new virtual methon OnLoaded
- fix external dialog background
- new property CustomResourceDictionary for DialogSettings
- fix InputDialog FocusBorderBrush when using Accented dialogs
- fix using Win8MetroPasswordBox style
Closes #1149 ProgressDialog cannot find the AccentColorBrush Resources
> MetroDialogs fixes

- MahApps.Metro/Controls/ToggleSwitchButton.cs
Use Shape is more generic and allows to use for indicator different shapes in ControlTepmlate.
> Use Shape instead of Rectangle

- MahApps.Metro/Controls/Dialogs/BaseMetroDialog.cs
There isn't a Window Theme if using Material Design In Xaml Toolkit as the App.xaml is configured differently.  Safely jumping out at this point allows dialogs to work with Material Design In Xaml Toolkit.
> Fix obj ref null exception if there is no Window Theme at runtime.

- MahApps.Metro/Controls/Dialogs/ProgressDialog.cs
- MahApps.Metro/Controls/Dialogs/ProgressDialogController.cs
- MahApps.Metro/Themes/Dialogs/ProgressDialog.xaml
- docs/release-notes/1.2.0.md
- samples/MetroDemo/MainWindow.xaml.cs
As far as I can see there is some, er, room for improvements in `ProgressDialogController`:
* `ProgressDialogController.IsOpen` is only set in the c'tor and when the dialog is closed. In fact, I see no reason to have that property, so I eliminated it.
* By default the state of the progress bar in the dialog is indeterminated. IMHO this should be set by the user explicitly.
* `ProgressDialogController` makes direct calls to several controls of `ProgressDialog`, e.g. `WrappedDialog.PART_ProgressBar.IsIndeterminate = true`. Instead I'd like to add appropriate methods to `ProgressDialog`, because the controls are implementation details of the dialog and not the concern of the controller.
> Progressdialog improvements

- MahApps.Metro/Controls/WindowSettings.cs
- MahApps.Metro/MahApps.Metro.NET45.csproj
- MahApps.Metro/MahApps.Metro.csproj
- samples/MetroDemo/MainWindow.xaml
I had the problem, that a customer could suddenly not open my
application anymore. It turned out that this is because the user.config
file was just empty and this caused a ConfigurationErrorsException. Then I
added an UnhandledExceptionHandler but this exception seems to happen
earlier. The only working solution is to delete the odd user.config and
restart the application.
For more details see here:
http://www.codeproject.com/Articles/30216/Handling-Corrupt-user-config-Settings
You can test this by editing the user.config and delete all content. But do NOT delete the file!
Then you need a window with the setting SaveWindowPosition="True" - otherwise no user.config file is created.
> If the user.config file is corrupt the whole application crashes

- MahApps.Metro/Behaviours/BorderlessWindowBehavior.cs
The existing `SizeToContent` workaround is only necessary when `ResizeMode != NoResize`. The workaround solves the problem of black bars appearing at the right and bottom edges of the window. But when `ResizeMode == NoResize`, no such black bars appear.
The reason for this pull request is that the `SizeToContent` workaround turns out to be a problem in some `SizeToContent=WidthAndHeight` edge cases. Specifically, when the size of the content changes as the window is loading, due to code in `SourceInitialized` and `LayoutUpdated` in our app. Unfortunately the repro is pretty complicated, and I haven't been able to create a minimal repro.
> Only apply SizeToContent workaround when necessary

- MahApps.Metro/Microsoft.Windows.Shell/Standard/NativeMethods.cs
- MahApps.Metro/Microsoft.Windows.Shell/WindowChromeWorker.cs
Fixes an odd side effect in calling GetWindowPlacement from WindowChromeWorker._HandleGetMinMaxInfo that caused the window to restore to the end of the drag instead of the beginning after doing an Aero Snap.
Steps to repro the bug that this PR fixes:
1. In the MahApps demo app, drag window to top of screen, which maximises the window.
2. Click Restore.
3. Window is restored to a location slightly off the top of the screen (which is, incorrectly, the location of the end of the previous drag).
Calling `IsZoomed` instead of `GetWindowPlacement` fixes this issue.
> Fix incorrect restore location after Aero Snap

- MahApps.Metro/Controls/Dialogs/DialogCoordinator.cs
- MahApps.Metro/Controls/Dialogs/IDialogCoordinator.cs
MessageDialogStyle does not makes sense for a Login dialog window and DialogManager.ShowLoginAsync (which DialogCoordinator.ShowLoginAsync is wrapping) does not take MessageDialogStyle either.
> Removed unneeded MessageDialogStyle param from IDialogCoordinator.ShowLoginAsync method

- MahApps.Metro/Controls/Dialogs/ProgressDialogController.cs
- samples/MetroDemo/MainWindow.xaml.cs
i think this is how progressbar dialog should be , removed the obsolete from IsOpen property and made it read only , also added cancelled event
> Some progressbar dialog fixes

- MahApps.Metro/Controls/Helper/ButtonHelper.cs
- MahApps.Metro/Controls/Helper/ControlsHelper.cs
- MahApps.Metro/Converters/ToUpperConverter.cs
- MahApps.Metro/Styles/Clean/CleanWindow.xaml
- MahApps.Metro/Styles/Controls.Buttons.xaml
- MahApps.Metro/Styles/Controls.DataGrid.xaml
- MahApps.Metro/Styles/Controls.Expander.xaml
- MahApps.Metro/Styles/Controls.GroupBox.xaml
- MahApps.Metro/Styles/Controls.ListView.xaml
- MahApps.Metro/Styles/Controls.xaml
- MahApps.Metro/Themes/Dialogs/BaseMetroDialog.xaml
- MahApps.Metro/Themes/DropDownButton.xaml
- MahApps.Metro/Themes/MetroWindow.xaml
- Mahapps.Metro.Tests/ButtonTest.cs
- samples/MetroDemo/ExampleViews/SelectionExamples.xaml
- samples/MetroDemo/ExampleWindows/FlyoutDemo.xaml
I think `ContentCharacterCasing` is better than saying `PreserveTextCase` true or false...
> [RFC] ContentCharacterCasing usage instead PreserveTextCase

- MahApps.Metro/Controls/Helper/MouseWheelChange.cs
- MahApps.Metro/Controls/Helper/MouseWheelState.cs
- MahApps.Metro/Controls/Helper/SliderHelper.cs
- MahApps.Metro/MahApps.Metro.NET45.csproj
Possibility to rotate the mouse wheel and change the value of the slider in following situations:
* None
* Only when the slider is focuesed and the mouse wheel is rotated
* If the mouse pointer is over the slider and the mouse wheel is rotated
> Change Slider value on MouseWheel event.

- MahApps.Metro/MahApps.Metro.NET45.csproj
- MahApps.Metro/MahApps.Metro.csproj
- MahApps.Metro/Styles/Clean/Clean.xaml
- MahApps.Metro/Styles/Clean/CleanStatusBar.xaml
- MahApps.Metro/Styles/Controls.StatusBar.xaml
- docs/release-notes/1.2.0.md
- samples/MetroDemo/ExampleWindows/CleanWindowDemo.xaml
This PR changes `StatusBar`'s background color to match the title bar as described in #2173 
Additionally, it adds the missing style for `StatusBar`s when using `CleanWindow` style.
> Dynamic statusbar background

- MahApps.Metro/Controls/WindowCommands.cs
- MahApps.Metro/Themes/WindowCommands.xaml
- samples/MetroDemo/MainWindow.xaml
- show only WindowCommandsItem with UIElements
- handle visibility of WindowCommandsItem content
Closes #2161 Window Commands Separators
> Fix WindowCommandsItem visibility

- MahApps.Metro/Controls/MetroTouchThumb.cs
- MahApps.Metro/MahApps.Metro.NET45.csproj
- MahApps.Metro/MahApps.Metro.csproj
- MahApps.Metro/Styles/Controls.Slider.xaml
In touch environment, touching a slider won't make its thumb following user's finger, for another visual has capture the touch-device. In order to make the Thumb touchable, we have to capture the touch-device in himself. So here it is.
PS : correct branch selection
> create new class of Thumb in order to be better in Touch environment

- MahApps.Metro/Controls/NumericUpDown.cs
- samples/MetroDemo/ExampleViews/TextExamples.xaml
Added the possibility for the NumericUpDown to behave as if it's Value is an Integer, removing the decimal separator as requested in Issue #2059.
Updated the Sample to reflect this change. The user can now use a CheckBox to turn the "HasDecimals" true or false to test it.
> NumericUpDown with Integer Only Option.

- MahApps.Metro/Controls/NumericUpDown.cs
Tested with different cultures and it seems to work just fine.
When the culture NumberDecimalSeparator is ',' (comma) the control replaces the '.' (period or decimal key) with the corrent NumberDecimalSeparator symbol.
All of the remaining functionality is the same.
>  NumericUpDown Culture problem #2149

- MahApps.Metro/Styles/Controls.ComboBox.xaml
- MahApps.Metro/Styles/Controls.PasswordBox.xaml
- MahApps.Metro/Styles/Controls.TextBlock.xaml
- MahApps.Metro/Styles/Controls.TextBox.xaml
- MahApps.Metro/Styles/Shared.xaml
Fixes #2225
List of changes:
- The `PART_FloatingMessageContainer` grid is now a `ContentControl` because the layout system for ContentControl is way simpler and therefore faster. Also, the grid wasn't necessary.
- The triggers that active the hide/show of the floating watermark are no longer three separate `DataTrigger`s. This system now consists of a `MultiDataTrigger` with two conditions, which both must be satisfied:
- Whether the input box should have a floating watermark
- Whether the input box has text
- The third one, whether the input box actually has a value for `TextBoxHelper.Watermark` has been dropped, because there are no 'negative' DataTriggers. This brings me to the next change:
- The animated property is no longer `Height`; it is now `MaxHeight`. If the watermark is not …
> Floating watermarks now trigger better

- MahApps.Metro/Controls/Dialogs/LoginDialog.cs
- MahApps.Metro/Converters/InvertedBooleanToVisibilityConverter.cs
- MahApps.Metro/MahApps.Metro.NET45.csproj
- MahApps.Metro/MahApps.Metro.csproj
- MahApps.Metro/Themes/Dialogs/LoginDialog.xaml
- samples/MetroDemo/ExampleViews/TextExamples.xaml
- samples/MetroDemo/MainWindow.xaml
- samples/MetroDemo/MainWindow.xaml.cs
The LoginDialog can now be shown like this to hide the username and only ask for a password:
```
var result = await this.ShowLoginAsync("Authentication", "Enter your password", 
new LoginDialogSettings 
{ 
UsernameVisibility = Visibility.Collapsed
});
```
Closes #2229
> Hide username on LoginDialog

- MahApps.Metro/Controls/Flyout.cs
- MahApps.Metro/Controls/FlyoutsControl.cs
- MahApps.Metro/Controls/MetroWindow.cs
- MahApps.Metro/MahApps.Metro.NET45.csproj
- MahApps.Metro/MahApps.Metro.csproj
- MahApps.Metro/Microsoft.Windows.Shell/Standard/NativeMethods.cs
- MahApps.Metro/Themes/Flyout.xaml
- MahApps.Metro/Themes/MetroWindow.xaml
- MahApps.Metro/Themes/Thumb.xaml
- docs/release-notes/1.2.0.md
thx @ButchersBoy for the code from [Dragablz](https://github.com/ButchersBoy/Dragablz)
Closes #1821 Move window when flyout is open
Closes #1635 Fylout window not draggable?
Closes #2036 Avalondock Anchorables could not be dragged inside MetroWindow
Closes #2122 Use behavior/attached property to control window dragging
Closes #1849 System menu present everywhere when fullscreen is toggled on
> Use thumb for dragmove

- MahApps.Metro/Themes/Tile.xaml
- samples/MetroDemo/ExampleViews/TilesExample.xaml
> If Tile is disabled then this is now shown

- MahApps.Metro/Controls/MetroWindow.cs
I've got a 3 monitor setup, all different resolutions and orientations.  Native.GetCursorPos reports .y as 200+ something on one monitor, even though the Window is maximised, and thus you can't drag-to-restore.  This seems to be a more robust solution.
> Fix Window Title Thumb Drag

- samples/MetroDemo/MainWindow.xaml
...just some notes in the XAML to stop people falling into a memory leak trap.
> MVVM dialog unregister instructions. Fixes #2241

- MahApps.Metro/Controls/DataGridNumericUpDownColumn.cs
- MahApps.Metro/Controls/Helper/TextBoxHelper.cs
- MahApps.Metro/Controls/NumericUpDown.cs
- MahApps.Metro/Themes/NumericUpDown.xaml
- samples/MetroDemo/ExampleViews/TextExamples.xaml
> [WIP] Some fixes in NumericUpDown

- MahApps.Metro/Themes/DropDownButton.xaml
- MahApps.Metro/Themes/SplitButton.xaml
**Default Style for enabled and disabled SplitButton/DropDownButton are the same**
**Disabled style (Set opacity to 0.55)**
This resolves #2127
> Set Opacity to .55 if SplitButton/DropDownButton is disabled

- MahApps.Metro/Controls/HotKeyBox.cs
- MahApps.Metro/MahApps.Metro.NET45.csproj
- MahApps.Metro/MahApps.Metro.csproj
- MahApps.Metro/Native/Constants.cs
- MahApps.Metro/Native/UnsafeNativeMethods.cs
- MahApps.Metro/Themes/Generic.xaml
- MahApps.Metro/Themes/HotKeyBox.xaml
- samples/MetroDemo/ExampleViews/TextExamples.xaml
- samples/MetroDemo/MainWindow.xaml.cs
- samples/MetroDemo/MainWindowViewModel.cs
- samples/MetroDemo/MetroDemo.NET45.csproj
- samples/MetroDemo/MetroDemo.csproj
- samples/MetroDemo/packages.config
This PR adds a `HotKeyBox` to MahApps.Metro with following features:
* handles all hotkeys except <kbd>Tab</kbd>, <kbd>Shift+Tab</kbd> (used for navigation) and <kbd>Back</kbd> (clears the hotkey)
* optionally modifier keys (<kbd>Ctrl</kbd>, <kbd>Alt</kbd>, <kbd>Shift</kbd>, or <kbd>Win</kbd>) are required
* supports watermark
* validation works
* templating support
* uses Win API [`GetKeyNameText`](https://msdn.microsoft.com/en-us/library/windows/desktop/ms646300%28v=vs.85%29.aspx?f=255&MSPPError=-2147217396) to get a textual representation of the keys. No localization is required, as it only depends on the keyboard layout as configured in Windows. (I have a German keyboard, therefore you see `STRG+UMSCHALT+POS1` in the screenshot; with an English layout it would say `CTRL+SHIFT+HOME`)
* …
> [RFC] Hotkey control

- MahApps.Metro/Behaviours/PasswordBoxBindingBehavior.cs
- MahApps.Metro/Behaviours/StylizedBehaviors.cs
- MahApps.Metro/MahApps.Metro.NET45.csproj
- MahApps.Metro/MahApps.Metro.csproj
- MahApps.Metro/Styles/Colors.xaml
- MahApps.Metro/Styles/Controls.PasswordBox.xaml
- MahApps.Metro/Styles/Controls.Shadows.xaml
- MahApps.Metro/Styles/Controls.TextBox.xaml
- MahApps.Metro/Styles/Controls.xaml
- MahApps.Metro/Styles/Shared.xaml
- samples/MetroDemo/ExampleViews/TextExamples.xaml
- add sample for Win8 PasswordBox
- add Shadows resource dictionary , e.g. for IsWaitingForData
- Fixed: Behaviors in StylizedBehaviors should be detached on unload
- Fixed: PasswordBoxBindingBehavior, it doesn't work e.g. in TabControl TabItems
- use new WaitingForDataDropShadowEffect and fix blurry effect
- IsWaitingForData for MetroButtonTextBox, MetroPasswordBox, MetroButtonPasswordBox, MetroButtonRevealedPasswordBox
- remove Win8MetroPasswordBox boilerplate code
- PackIconMaterial `Eye` for `MetroButtonRevealedPasswordBox`
- `ClearTextButton` feature for `MetroButtonRevealedPasswordBox`
Closes #2343 Win8MetroPasswordBox Preview does not work with Tabcontrol (item > 1)
> [WIP] Fix PasswordBoxBindingBehavior and IsWaitingForData

- MahApps.Metro/Styles/Controls.Tooltip.xaml
Fixed a bug in the ToolTip style where the ContentStringFormat was being ignored.
> Added ContentStringFormat TemplateBinding to ToolTip

- MahApps.Metro/Controls/Helper/TextBoxHelper.cs
- MahApps.Metro/Styles/Controls.Buttons.xaml
- MahApps.Metro/Styles/Controls.ComboBox.xaml
- MahApps.Metro/Styles/Controls.PasswordBox.xaml
- MahApps.Metro/Styles/Controls.TextBox.xaml
- MahApps.Metro/Themes/NumericUpDown.xaml
- docs/release-notes/1.3.0.md
- samples/MetroDemo/ExampleViews/SelectionExamples.xaml
- samples/MetroDemo/ExampleViews/TextExamples.xaml
- samples/MetroDemo/MainWindowViewModel.cs
- remove unnecessary ReadOnlyVisualElement
- set ChromelessButtonStyle Padding to 0
- new DependencyProperty ButtonContentTemplate
- fix width of ClearText button if height change, e.g. by floating watermark
- new MetroComboBoxDropDownToggleButtonStyle
- fix background state colors
- catch HotkeyAlreadyRegisteredException /cc @thoemmi 
Closes #2352 Can't set ComboBox buttons width with ControlsHelper.ButtonWidth
> fix ControlsHelper.ButtonWidth for combobox and other stuff

- MahApps.Metro/Controls/NumericUpDown.cs
When pasting into a NumericUpDown control any selected text is now replaced with the pasted text.
Closes Issue #2370 
Fixed up the pasting into the NumericUpDown control so that selected text is replaced.
> Paste over selection for a NumericUpDown control

- MahApps.Metro/Controls/ProgressRing.cs
Added EllipseDiameterScale property as a multiplier for Ellipse Size, below the scaling of 1.0 (default), 0.5 (smaller) and 1.5 larger values for this property are shown.
This solves issue #2204 as now it is possible do manually ajust the size of the Ellipse. In the control the Ellipse size is calculated using the formula below:
EllipseDiameter =(width / 8)*EllipseDiameterScale;
> Added EllipseDiameterScale (issue #2204)

- MahApps.Metro/Controls/MetroWindow.cs
- MahApps.Metro/Controls/WindowButtonCommands.cs
- MahApps.Metro/Styles/Controls.Buttons.xaml
- MahApps.Metro/Themes/MetroWindow.xaml
- MahApps.Metro/Themes/WindowButtonCommands.xaml
- Mahapps.Metro.Tests/FlyoutTest.cs
- Mahapps.Metro.Tests/MetroWindowTest.cs
- Mahapps.Metro.Tests/TestHelpers/WindowHelpers.cs
- use ContentPresenter to show the WindowButtonCommands, so it's now possible easier to change the min/max/close button styles
- enable changing min/max/restore/close button tooltip
- new Win10WindowButtonCommandsTemplate
Closes #1972 Changing Close button icon.
> WindowButtonCommands enhancements

- MahApps.Metro/Themes/Flyout.xaml
- MahApps.Metro/Themes/NumericUpDown.xaml
Now the AutomationId property is set according to the control x:Name property.
For NumericUpDown:
- Textbox: "PART_TextBox{x:Name value}"
- DownButton : "PART_NumericDown{x:Name value}"
- UpButton: "PART_NumericUp{x:Name value}"
For Flyout:
-NavButton: "nav{x:Name value}"
#2166
> AutomationId based on name fix

- MahApps.Metro/Controls/Dialogs/BaseMetroDialog.cs
- MahApps.Metro/Controls/Dialogs/DialogManager.cs
- MahApps.Metro/Styles/Fonts.xaml
- MahApps.Metro/Themes/Dialogs/BaseMetroDialog.xaml
- MahApps.Metro/Themes/Dialogs/InputDialog.xaml
- MahApps.Metro/Themes/Dialogs/LoginDialog.xaml
- MahApps.Metro/Themes/Dialogs/MessageDialog.xaml
- MahApps.Metro/Themes/Dialogs/ProgressDialog.xaml
The size of the fonts for the Title and Message of a Dialog, can be set using a MetroDialogSettings object and passing it as a parameter.
Example:
`var controller = await this.ShowProgressAsync("Please wait...", "We are baking some cupcakes!", false, new MetroDialogSettings() { DialogMessageFontSize = 25, DialogTitleFontSize = 50 });`
#2380
> Dialog Font Sizes Setting Implementation #2380

- MahApps.Metro/Controls/Helper/TextBoxHelper.cs
- MahApps.Metro/Styles/Controls.PasswordBox.xaml
- MahApps.Metro/Styles/Controls.TextBox.xaml
- new attached dp `TextButton` in TextBoxHelper which handles the visibility of the Button in `MetroButtonPasswordBox` and `MetroButtonTextBox`
- fixed ButtonCommandMetroTextBox text displaid over icon
Closes #2385 ButtonCommandMetroTextBox text displaid over icon.
Closes #2220 Why in the MetroButtonTextBox the visibility of PART_ClearText is not managed as the MetroTextBox?
> MetroButtonPasswordBox / MetroButtonTextBox fixes for #2385 and #2220

- MahApps.Metro/Controls/Dialogs/DialogManager.cs
- samples/MetroDemo/MainWindow.xaml.cs
- use Dispatcher in ShowMetroDialogAsync like in the other methods
Closes  #2396 ShowMetroDialogAsync does not raise DialogManager.DialogOpened event.
> 2396 show metro dialog async dialog opened fix

- MahApps.Metro/Controls/NumericUpDown.cs
Fixed the `HasDecimals` property. It was broken on commit bd6aa38e which made the property stop working and decimals like ',' '.' were available when `HasDecimals = false`.
closes issue #2403.
> Fixes the HasDecimals property, broken before on commit bd6aa38e.

- MahApps.Metro/Controls/ToggleSwitch.cs
- MahApps.Metro/Controls/ToggleSwitchButton.cs
- MahApps.Metro/Themes/ToggleSwitch.xaml
- fix click action by using the OnClick instead only OnToggle method
- and use the PropertyChangeNotifier for IsCheckedProperty to update the thumb
Closes #2415 ToggleSwitch "Click" event not triggered
and use the PropertyChangeNotifier for IsCheckedProperty to update the thumb
> ToggleSwitch "Click" event not triggered #2415

- readme.md
Links in `README.md` to `CONTRIBUTING.md` were broken, when the latter was moved to the `.github` subfolder. This PR fixes the links.
This fixes #2425.
> Fixed broken links to CONTRIBUTING.md

- MahApps.Metro/Controls/ProgressRing.cs
Removed BindsTwoWayByDefault from IsActiveProperty. There is not need to apply TwoWay by default, because the GUI does not update the IsActive property in any parts of the code
The only change is when **Visibility** changed.
In that case. Would it be important that when the visibility of ProgessRing changes that IsActive is reflected to the **bound property**?
As crossreference, IsIndeterminate has the same behavior
http://referencesource.microsoft.com/#PresentationFramework/src/Framework/System/Windows/Controls/ProgressBar.cs,60ee7d94e2137368,references
> Remove BindsTwoWayByDefault from IsActiveProperty from ProgressRing

- MahApps.Metro/Controls/Dialogs/MessageDialog.cs
Assign empty lambda instead of null to cleanupHandlers to prevent null reference exception on early cancellation
#2420
> Async Dialog Cancellation Update

- MahApps.Metro/Controls/ContentControlEx.cs
- MahApps.Metro/Controls/Flyout.cs
- MahApps.Metro/Controls/IMetroThumb.cs
- MahApps.Metro/Controls/MetroThumb.cs
- MahApps.Metro/Controls/MetroThumbContentControl.cs
- MahApps.Metro/Controls/MetroWindow.cs
- MahApps.Metro/MahApps.Metro.NET45.csproj
- MahApps.Metro/MahApps.Metro.csproj
- MahApps.Metro/Themes/ContentControlEx.xaml
- MahApps.Metro/Themes/Generic.xaml
- MahApps.Metro/Themes/MetroWindow.xaml
- Mahapps.Metro.Tests/MetroWindowTest.cs
- docs/release-notes/1.3.0.md
- samples/MetroDemo/ExampleWindows/FlyoutDemo.xaml
- samples/MetroDemo/ExampleWindows/FlyoutDemo.xaml.cs
Add and use a new `MetroThumbContentControl`. This will be used for all title bar stuff, so we can drag&move the window **and** allow custom title templates with Buttons or Menus.
Closes #2477 Create a custom Thumb for the title DragMove
Closes #2449 Visual bug while using RightWindowCommands
> New MetroThumbContentControl for better experience

- MahApps.Metro/Controls/CloseCommand.cs
- MahApps.Metro/Controls/Flyout.cs
- MahApps.Metro/Controls/Helper/ControlsHelper.cs
- MahApps.Metro/Controls/MetroTabItem.cs
- MahApps.Metro/MahApps.Metro.NET45.csproj
- MahApps.Metro/MahApps.Metro.csproj
- MahApps.Metro/Themes/Flyout.xaml
- Mahapps.Metro.Tests/FlyoutTest.cs
- docs/release-notes/1.3.0.md
- samples/MetroDemo/ExampleWindows/FlyoutDemo.xaml
- samples/MetroDemo/ExampleWindows/FlyoutDemo.xaml.cs
- use ContentControlEx for header
- use internal command handling for close button
- use ControlsHelper attaches proeprties `HeaderFontSize`, `HeaderFontWeight` and `HeaderFontStretch`
- new attached property `ControlsHelper.HeaderMargin`
Closes #2485 Hiding close button and title leaves blank space in top-positioned flyouts
> flyout improvement caused by #2485

- MahApps.Metro/Controls/MetroWindow.cs
- samples/MetroDemo/MainWindow.xaml
- samples/MetroDemo/MainWindow.xaml.cs
Added `ShowDialogsOverTitleBar` property to MetroWindow to set whether dialogs show over (hide) the window's title bar or not. Defaults to `true` so that legacy applications are not affected.
Fixes #2109
> Allow showing title bar while showing dialog (Fixes #2109)

- MahApps.Metro/Controls/FlipView.cs
- samples/MetroDemo/ExampleViews/OtherExamples.xaml
add IsNavigationEnabled Property in FlipView & test for IsNavigationEnabledProperty
For some reason, i need control Navigation by another control. there isn't a Property to hide Navigation Button.
> add IsNavigationEnabled Property in FlipView

- MahApps.Metro/Controls/Helper/DataGridCellHelper.cs
- MahApps.Metro/Controls/Helper/DataGridRowHelper.cs
- MahApps.Metro/Styles/Controls.DataGrid.xaml
- docs/release-notes/1.3.0.md
- samples/MetroDemo/ExampleViews/DataGridExamples.xaml
increase (scrolling) performance for the DataGrid
- remove DataGridCellHelper.SaveDataGrid usage
- add IsCellOrRowHeader and SelectionUnit to DataGridCellHelper and use it in the style
Closes #2504 DataGrid causes lag when switching content
> DataGrid performance

- MahApps.Metro/Controls/SplitButton.cs
If the SplitButton loses mouse capture while its Popup is open, then close the popup.
Closes #2574 -- bug where Popup would stay open even when the window lost focus.
> Close SplitButton popup if it loses mouse capture

- MahApps.Metro/Behaviours/BorderlessWindowBehavior.cs
- MahApps.Metro/Controls/GlowWindow.xaml.cs
- MahApps.Metro/Microsoft.Windows.Shell/Standard/NativeMethods.cs
- docs/release-notes/1.3.0.md
Closes #2577 Window Resizing Erroneously Acts Deferred
Closes #2279 Corner resize issues with GlowBrush enabled
> fix glow activation/dpi bug

- MahApps.Metro/Controls/Flyout.cs
I have multiple windows, and i'm using flyouts to show an alert condition in the application.  When the user dismisses the alert all flyouts are closed via my application code.
This line causes the last Window my where my code closes the flyout to receive focus , bringing that window to the front, interrupting the users activity:
```
// focus the Flyout itself to avoid nasty FocusVisual painting (it's visible until the Flyout is closed)		
flyout.Focus();
```
I understand there is a specific comment here regarding this line to perform some visual trickery.  However, it's not logically correct.  I have experimented, removed the line, and I can't see any display issues in _my_ application.
Maybe someone / @punker76 ,  with some background on this line can comment?
Another option would be to …
> Proposal - Dont focus flyout on close

- docs/release-notes/1.4.0.md
- src/MahApps.Metro/MahApps.Metro.Shared/Controls/TimePicker/DateTimePicker.cs
- src/MahApps.Metro/MahApps.Metro.Shared/Controls/TimePicker/TimePickerBase.cs
- src/MahApps.Metro/MahApps.Metro/Themes/DateTimePicker.xaml
- src/Mahapps.Metro.Tests/Mahapps.Metro.Tests.Shared/Tests/DateTimePickerTests.cs
- src/Mahapps.Metro.Tests/Mahapps.Metro.Tests.Shared/Views/DateAndTimePickerWindow.xaml
- Binding should now work correctly in both directions
- [Fix] Issue where clearing text does not immediately set value to ""
- Add Unit-Test for DateTimePicker
- [Fix] Issue where Hour 0 is not shown when using 24h clock
- [Fix] Issue where Binding issues on DateTimePicker/TimePicker are shown on the output window
- [Fix] Change DateTimePicker.SelectedDate to BindsTwoWayByDefault. The reason is that we do not have to use Mode=TwoWay explicit, and DatePicker.SelectedDate has BindsTwoWayByDefault too.
> Hotfix for DateTimePicker/TimePicker

- src/MahApps.Metro.Samples/MahApps.Metro.Demo/MahApps.Metro.Demo.Shared/ExampleWindows/VSDemo.xaml
- src/MahApps.Metro/MahApps.Metro/Styles/VS/Styles.xaml
- src/MahApps.Metro/MahApps.Metro/Styles/VS/TabControl.xaml
Implement support for StandardTabItem & TabStripPlacement for tabs in VS theme
Right now tab 4 TabStripPlacement are supported with rotation like in VS
Closes #2346
Closes #2090
Closes #1890
> Updated TabControl styles for VS

- docs/release-notes/1.4.0.md
- src/MahApps.Metro.Samples/MahApps.Metro.Demo/MahApps.Metro.Demo.Shared/ExampleViews/TextExamples.xaml
- src/MahApps.Metro/MahApps.Metro.Shared/Controls/Helper/TextBoxHelper.cs
- src/MahApps.Metro/MahApps.Metro/Styles/Controls.ContextMenu.xaml
@Deadpikle created this PR [Added more TextBox ContextMenu configuration #2758](https://github.com/MahApps/MahApps.Metro/pull/2758) which was a good idea to enhance the current ContextMenu implementation. I need some days to review theses changes and come to the conclusion that we don't need this extra attached properties to add some more context menu items to the default one and the spell checker items.
So here is my solution...
- If you want to use the default context menu items cut, copy and paste you must do nothing
- If you want to use your own context menu items without the default items you must do this
```xaml
<TextBox Text="Yeahh">
<TextBox.ContextMenu>
<ContextMenu>
<MenuItem Header="This is only a Test-Item" />
</ContextMenu>
</TextBox.ContextMenu>
</TextBox>
```
- If you want …
> TextBox ContextMenu usage improvement

- src/MahApps.Metro/MahApps.Metro/Styles/Controls.DataGrid.xaml
Some time ago i have made pull request #1819 that adds alignments to DataGridRowHeader, but in 6df54bab96e82be811edd414826636ca9084ba94 this feature was broken.
Before:
After:
> Fix DataGridRowHeader HorizontalAlignment

- docs/release-notes/1.4.0.md
- src/MahApps.Metro/MahApps.Metro.Shared/Controls/Dialogs/BaseMetroDialog.cs
- src/MahApps.Metro/MahApps.Metro.Shared/Controls/Dialogs/CustomDialog.cs
- src/MahApps.Metro/MahApps.Metro.Shared/Controls/Dialogs/DialogManager.cs
Some changes to fix #2735 MetroWindow.ShowMetroDialogAsync odd behaviour with provided DialogSettings
Closes #2735
> Custom dialogs DialogSettings

- src/MahApps.Metro/MahApps.Metro.Shared/Converters/StringToVisibilityConverter.cs
Currently `StringToVisibilityConverter` does not handle `null` gracefully. If the value is `null`, the output is `null` too. IMHO `null` should be handled like an empty string, i.e. if the value is `null`, the output should be `FalseEquivalent` (or `Visibility.Visible`, if `OppositeStringValue` is `true`)
> StringToVisibilityConverter should handle null like an empty string

- src/MahApps.Metro/MahApps.Metro/Themes/NumericUpDown.xaml
Let the TextBox handle the UseFloatingWatermark stuff and use TemplateBinding for the attached properties UseFloatingWatermark and HasText
Closes #2795 NumericUpDown Watermark is shown twice when using floatingwatermark for textboxes
> Fix NumericUpDown using UseFloatingWatermark

- src/MahApps.Metro.Samples/MahApps.Metro.Demo/MahApps.Metro.Demo.Shared/ExampleViews/TextExamples.xaml
- src/MahApps.Metro/MahApps.Metro.Shared/Controls/HotKeyBox.cs
- src/MahApps.Metro/MahApps.Metro/Themes/HotKeyBox.xaml
This PR fixes the wrong display of special media buttons in `HotKeyBox` as described in #2585.
Unfortunately, Windows does not localize media buttons, therefore I've implemented a fallback using `ToString()`.
Additionally, upper case isn't hard-coded anymore. The user has now the option to use `ControlsHelper.ContentCharacterCasing`. (Upper case is still the default)
I haven't edited any release notes in the PR as I don't know in which release will include this PR.
> Correct display of media buttons in HotKeyBox

- src/MahApps.Metro/MahApps.Metro.Shared/Controls/TimePicker/DateTimePicker.cs
[Fix] Issue where *SelectedDate* is set to the *DisplayDate* if the SelectedDate is DateTime.MinValue
This issue appears when binding to a property of `DateTime` and the date is DateTime.MinValue
> DateTimePicker SelectedDate issue

- src/MahApps.Metro/MahApps.Metro.Shared/Controls/Dialogs/BaseMetroDialog.cs
If a dialog is shown in a window other than the `MainWindow`, use `OwningWindow` if available to detect the theme.
This fixes #2835
> Use owning window to detect theme for dialogs if available

- src/MahApps.Metro/MahApps.Metro.Shared/Controls/TimePicker/DateTimePicker.cs
- src/MahApps.Metro/MahApps.Metro.Shared/Controls/TimePicker/TimePickerBase.cs
Before | After
------------ | -------------
**Time is set to 00:00:00** | **Time is now kept**
**If a date is selected then selecting the time closes the control** | **The control does now stays open**
> [Fix] Issue when the time is cleared if a date is selected

- src/MahApps.Metro/MahApps.Metro.Shared/Controls/MetroWindow.cs
If ShowInTaskbar = false, when double click on the title bar of a Minimized window, the window will be Restored instead of Maximized.
> window's default behavior : double click on title bar will restore Minimized window

- src/MahApps.Metro/MahApps.Metro/Themes/WindowCommands.xaml
Prevents `WindowCommandsItem` from erroneously responding to the tab key.
> Fix WindowCommands tab stop bug

- src/MahApps.Metro/MahApps.Metro.Shared/Controls/CustomValidationPopup.cs
Close validation popup by setting the IsOpen property with SetCurrentValue (prevents breaking available bindings). 
#2866
> Close validation popup with SetCurrentValue

- src/MahApps.Metro/MahApps.Metro.Shared/Controls/MetroWindow.cs
If someone listening for `Closing` set `e.Cancel = true` we should not overwrite/overrule that request.
> Don't overwrite cancellation for close

- docs/release-notes/1.5.0.md
- src/MahApps.Metro.Samples/MahApps.Metro.Demo/MahApps.Metro.Demo.Shared/ExampleViews/TabControlExamples.xaml
- src/MahApps.Metro/MahApps.Metro.Shared/Controls/Helper/TabControlHelper.cs
- src/MahApps.Metro/MahApps.Metro.Shared/Controls/Underline.cs
- src/MahApps.Metro/MahApps.Metro.Shared/MahApps.Metro.Shared.projitems
- src/MahApps.Metro/MahApps.Metro/MahApps.Metro.NET40.csproj
- src/MahApps.Metro/MahApps.Metro/MahApps.Metro.NET45.csproj
- src/MahApps.Metro/MahApps.Metro/Styles/Controls.TabControl.xaml
- src/MahApps.Metro/MahApps.Metro/Themes/Generic.xaml
- src/MahApps.Metro/MahApps.Metro/Themes/MetroTabControl.xaml
- src/MahApps.Metro/MahApps.Metro/Themes/MetroTabItem.xaml
- src/MahApps.Metro/MahApps.Metro/Themes/Underline.xaml
This PR adds a new attached property to add a new underlined type for the `TabControl` and `MetroTabControl`.
- Add new `Underlined` attached property to `TabControlHelper`. This property controls the type of the underline type which can be TabItem or TabPanel (with TabItem).
```
/// <summary>
/// Specifies the underline position of a TabControl.
/// </summary>
public enum UnderlinedType
{
None,
TabItems,
SelectedTabItem,
TabPanel
}
```
- Make `IsUnderlined` obsolete
- Add new `Brush` attached properties to enable easy changing the underline brushes
```
Controls:TabControlHelper.UnderlineBrush
Controls:TabControlHelper.UnderlineSelectedBrush
Controls:TabControlHelper.UnderlineMouseOverBrush
Controls:TabControlHelper.UnderlineMouseOverSelectedBrush
```
Closes #2895 [RFC] [Enhancement] …
> TabControl Underlined TabPanel

- docs/release-notes/1.5.0.md
- src/MahApps.Metro.Samples/MahApps.Metro.Demo/MahApps.Metro.Demo.Shared/ExampleViews/TabControlExamples.xaml
- src/MahApps.Metro/MahApps.Metro/Styles/Controls.AnimatedSingleRowTabControl.xaml
- src/MahApps.Metro/MahApps.Metro/Styles/Controls.AnimatedTabControl.xaml
- src/MahApps.Metro/MahApps.Metro/Styles/Controls.TabControl.xaml
- src/MahApps.Metro/MahApps.Metro/Themes/MetroAnimatedSingleRowTabControl.xaml
- src/MahApps.Metro/MahApps.Metro/Themes/MetroAnimatedTabControl.xaml
- src/MahApps.Metro/MahApps.Metro/Themes/MetroTabItem.xaml
This PR adds the new underlined types to the animated TabConotrols.
> Use new underlined types for animated TabControls

- docs/release-notes/1.5.0.md
- src/MahApps.Metro.Samples/MahApps.Metro.Demo/MahApps.Metro.Demo.Shared/ExampleViews/HamburgerMenuSample.xaml
- src/MahApps.Metro/MahApps.Metro.Shared/Controls/HamburgerMenu/HamburgerMenu.Properties.cs
- src/MahApps.Metro/MahApps.Metro/Themes/HamburgerMenu.xaml
- Update `HamburgerMenu` scroll behavior to match the UWP Toolkit (see UWP Toolkit Issue [#954](https://github.com/Microsoft/UWPCommunityToolkit/issues/954)).
- Add a new dependency property `VerticalScrollBarOnLeftSide` to show the vertical scrollbar on the left side
- Use a disappearing ScrollViewer
- thx to @amkuchta for the initial idea
Closes #2897 [RFC] [WIP] HamburgerMenu Scroll Behavior Correction
Closes #2857 HamburgerMenuItem Scrolling
> 🍔 menu scroll bar behavior like in the UWPCommunityToolkit

- src/MahApps.Metro.Samples/MahApps.Metro.Demo/MahApps.Metro.Demo.Shared/ExampleViews/HamburgerMenuSample.xaml
- src/MahApps.Metro/MahApps.Metro.Shared/Controls/HamburgerMenu/HamburgerMenu.HamburgerButton.cs
- src/MahApps.Metro/MahApps.Metro/Themes/HamburgerMenu.xaml
Added hamburfer header templating support.
Template accessible trough "HamburgerMenu.HamburgerMenuHeaderTemplate".
I experienced little problem, that GridColumn ignored HamburgerWidth (not sure why), it is reason for this code (workaround):
```
<Grid.ColumnDefinitions>
<ColumnDefinition Width="Auto"/>
<ColumnDefinition />
</Grid.ColumnDefinitions>
<Grid Width="{TemplateBinding HamburgerWidth}" HorizontalAlignment="Left" />
```
istead of ` <ColumnDefinition Width="{TemplateBinding HamburgerWidth}"/>`
I wanted to have possibility to add title to HamburgerMenu... Now it is possible for example this way:
```
<controls:HamburgerMenu.HamburgerMenuHeaderTemplate>
<DataTemplate>
<TextBlock Grid.Column="1"
VerticalAlignment="Center"
HorizontalAlignment="Center"
FontSize="16"
Foreground="White" …
```
> Hamburger Header Templating

- docs/release-notes/1.5.0.md
- src/MahApps.Metro/MahApps.Metro.Shared/Controls/Helper/TextBoxHelper.cs
- src/MahApps.Metro/MahApps.Metro/Styles/Controls.ComboBox.xaml
- src/MahApps.Metro/MahApps.Metro/Styles/Controls.DatePicker.xaml
- src/MahApps.Metro/MahApps.Metro/Styles/Controls.PasswordBox.xaml
- src/MahApps.Metro/MahApps.Metro/Styles/Controls.TextBox.xaml
- src/MahApps.Metro/MahApps.Metro/Themes/DateTimePicker.xaml
- src/MahApps.Metro/MahApps.Metro/Themes/HotKeyBox.xaml
- src/MahApps.Metro/MahApps.Metro/Themes/NumericUpDown.xaml
Add new `WatermarkAlignment` attached property to `TextBoxHelper` which indicates the horizontal alignment of the watermark (incl. floating watermark).
Closes #2627 Inconsistent FloatingWatermark Alignment
> New WatermarkAlignment attached property

- src/MahApps.Metro/MahApps.Metro/Themes/DateTimePicker.xaml
> @punker76 I have tried to modify it but `ContentFontFamily` introduces the issue. If I remove the key and use TemplateBinding then the default value of `ContentFontFamily` is not used.
> It is now possibile to set FontFamily to DateTimePicker.

- src/MahApps.Metro/MahApps.Metro.Shared/ThemeManager/Accent.cs
- src/MahApps.Metro/MahApps.Metro.Shared/ThemeManager/AppTheme.cs
- src/MahApps.Metro/MahApps.Metro.Shared/ThemeManager/ThemeManager.cs
- ThemeManager did not look at merged dictionaries the way wpf did. wpf looks at them in a reverse order and so should we.
- StringComparison should be OrdinalIgnoreCase
- Switched to nameof instead of hard coded values
- Switched to string interpolation instead of string.format
- Switched to null conditional operator instead of `SafeRaise`
- Added some missing documentation
- Removed "metro" from documentation to ease sharing of code with Fluent.Ribbon
> Fixing a few issues in ThemeManager

- src/MahApps.Metro/MahApps.Metro.Shared/ThemeManager/ThemeManager.cs
I forgot to replace one occurences of InvariantCultureIgnoreCase in my previous PR.
> Using OrdinalIgnoreCase instead of InvariantCultureIgnoreCase in ThemeManager

- src/MahApps.Metro/MahApps.Metro.Shared/Controls/TimePicker/TimePickerBase.cs
_Changed TimePickerBase.OnTextBoxLostFocus() to parse the DatePickerTextBox text as a DateTime rather than a TimeSpan so that time strings with an AM/PM will be parsed correctly_
_Closed issues. #3049_
I would have added a test, but there are currently no tests for editing the time via the textbox, and it seemed non-trivial to add.
> Allow TimePicker to parse times with an AM/PM.

- docs/release-notes/1.6.0.md
- src/MahApps.Metro/MahApps.Metro/Styles/Controls.PasswordBox.xaml
- src/MahApps.Metro/MahApps.Metro/Styles/Controls.TextBox.xaml
- src/MahApps.Metro/MahApps.Metro/Styles/Shared.xaml
- Remove the BitmapCache at AdornerDecorator.CacheMode which is causing the GPU memory leak if the app will be minimized.
- Set effect directly as DynamicResource and use po:Freeze="True" and x:Shared="False"
Closes #2990 TextBox memory leak
> Fix for TextBox GPU memory leak

- src/MahApps.Metro/MahApps.Metro.Shared/Controls/NumericUpDown.cs
The `NumericUpDown` control catches the `TextBoxChangedEvent` and therefore other styles that depend on the event doesn't work correctly, i.e. the `SmartHint` feature from Material Design.
Example: 
This PR removes the line which catches the event.
> Don't catch TextChangedEvent in NumericUpDown

- docs/release-notes/1.6.0.md
- src/MahApps.Metro/MahApps.Metro.Shared/Controls/Helper/TextBoxHelper.cs
- src/MahApps.Metro/MahApps.Metro.Shared/Controls/HotKeyBox.cs
- src/MahApps.Metro/MahApps.Metro/Styles/Controls.ComboBox.xaml
- src/MahApps.Metro/MahApps.Metro/Styles/Controls.DatePicker.xaml
- src/MahApps.Metro/MahApps.Metro/Styles/Controls.PasswordBox.xaml
- src/MahApps.Metro/MahApps.Metro/Styles/Controls.TextBox.xaml
- src/MahApps.Metro/MahApps.Metro/Themes/DateTimePicker.xaml
- src/MahApps.Metro/MahApps.Metro/Themes/HotKeyBox.xaml
- src/MahApps.Metro/MahApps.Metro/Themes/NumericUpDown.xaml
- src/Mahapps.Metro.Tests/Mahapps.Metro.Tests.Shared/Tests/AutoWatermarkTest.cs
- src/Mahapps.Metro.Tests/Mahapps.Metro.Tests.Shared/Views/AutoWatermarkTestWindow.xaml
- src/Mahapps.Metro.Tests/Mahapps.Metro.Tests.Shared/Views/AutoWatermarkTestWindow.xaml.cs
`Watermark` fixes and improvements
- Fix right aligned floating watermark.
- Use `TextBoxHelper.Watermark` for `HotKeyBox` instead own DependencyProperty (marked as obsolete).
- Allow `TextBoxHelper.AutoWatermark` for `HotKey` DependencyProperty of `HotKeyBox`.
- New `TextBoxHelper.WatermarkTrimming` attached property to set the text trimming behavior to employ when (floating) watermark overflows the content area. thx to [@amkuchta](https://github.com/amkuchta)
- New `TextBoxHelper.WatermarkWrapping` attached property (only for `TextBox`) to set how the watermark should wrap text. Default is binded to `TextWrapping` property. thx to [@amkuchta](https://github.com/amkuchta)
Closes #3067
Closes #3068
Closes #2884
Closes #2889
> Watermark fixes and improvements

- docs/release-notes/1.6.0.md
- src/MahApps.Metro.Samples/MahApps.Metro.Demo/MahApps.Metro.Demo.Shared/ExampleWindows/VSDemo.xaml
- src/MahApps.Metro/MahApps.Metro/MahApps.Metro.NET40.csproj
- src/MahApps.Metro/MahApps.Metro/MahApps.Metro.NET45.csproj
- src/MahApps.Metro/MahApps.Metro/Styles/VS/Expander.xaml
- src/MahApps.Metro/MahApps.Metro/Styles/VS/GroupBox.xaml
- src/MahApps.Metro/MahApps.Metro/Styles/VS/Styles.xaml
This PR adds the missing Expander style for the VS theme.
Closes #957
> Add missing VS StandardExpander style

- docs/release-notes/1.6.0.md
- src/MahApps.Metro/MahApps.Metro.Shared/Actions/CloseTabItemAction.cs
- src/MahApps.Metro/MahApps.Metro.Shared/Controls/Helper/TabControlHelper.cs
- src/MahApps.Metro/MahApps.Metro.Shared/Controls/MetroTabItem.cs
- src/MahApps.Metro/MahApps.Metro/Styles/VS/TabControl.xaml
This PR adds 3 new attached properties to the TabControlHelper
- TabControlHelper.CloseButtonEnabled attached property to show / hide the close button (default is true)
- TabControlHelper.CloseTabCommand attached property which executes if the TabItem will be closed
- TabControlHelper.CloseTabCommandParameter attached property which will be passed to the CloseTabCommand
Closes #1731
> VS Theme TabItem enhancements

- src/MahApps.Metro/MahApps.Metro/Styles/Controls.PasswordBox.xaml
add "MetroButtonPasswordBox" support "TextBoxHelper.ButtonsAlignment"
"MetroButtonPasswordBox" can use "TextBoxHelper.ButtonsAlignment="Left"" now
> add "PasswordBox" support "ButtonsAlignment"

- docs/release-notes/1.6.0.md
- src/MahApps.Metro/MahApps.Metro.Shared/Converters/MarkupConverter.cs
- src/MahApps.Metro/MahApps.Metro.Shared/Converters/MathConverter.cs
- src/MahApps.Metro/MahApps.Metro.Shared/MahApps.Metro.Shared.projitems
- src/MahApps.Metro/MahApps.Metro/Styles/Controls.ComboBox.xaml
- src/MahApps.Metro/MahApps.Metro/Styles/Controls.DatePicker.xaml
- src/MahApps.Metro/MahApps.Metro/Styles/Controls.PasswordBox.xaml
- src/MahApps.Metro/MahApps.Metro/Styles/Controls.TextBlock.xaml
- src/MahApps.Metro/MahApps.Metro/Styles/Controls.TextBox.xaml
- src/MahApps.Metro/MahApps.Metro/Styles/Controls.xaml
- src/MahApps.Metro/MahApps.Metro/Styles/Shared.xaml
- src/MahApps.Metro/MahApps.Metro/Themes/DateTimePicker.xaml
The height of the floating watermark container adapts now according to the font size of the floating watermark.
Before
After
Closes #3009
> Fix for Floating watermak field doesn't fit according to floating watermark FontSize

- docs/release-notes/1.6.0.md
- src/MahApps.Metro/MahApps.Metro.Shared/Behaviours/PasswordBoxBindingBehavior.cs
- src/MahApps.Metro/MahApps.Metro.Shared/Controls/Dialogs/LoginDialog.cs
- src/MahApps.Metro/MahApps.Metro/Styles/Controls.PasswordBox.xaml
- Get the caret index from PasswordBox with reflection and set it to the hidden TextBox which shows the Password.
Closes #2966
> Fix wrong caret index for revealed PasswordBox

- docs/release-notes/1.6.0.md
- src/MahApps.Metro/MahApps.Metro.Shared/Controls/Helper/ScrollBarHelper.cs
- src/MahApps.Metro/MahApps.Metro.Shared/Controls/Helper/ScrollViewerHelper.cs
- src/MahApps.Metro/MahApps.Metro.Shared/MahApps.Metro.Shared.projitems
- src/MahApps.Metro/MahApps.Metro/Styles/Controls.AnimatedSingleRowTabControl.xaml
- src/MahApps.Metro/MahApps.Metro/Styles/Controls.Scrollbars.xaml
- src/MahApps.Metro/MahApps.Metro/Themes/HamburgerMenu.xaml
- src/MahApps.Metro/MahApps.Metro/Themes/MetroAnimatedSingleRowTabControl.xaml
- new attached property IsHorizontalScrollWheelEnabled. If it's set to true and a horizontal ScrollBar is visible then the mouse wheel scrolls to left and right.
- move VerticalScrollBarOnLeftSide attached property to ScrollViewerHelper
Closes #3084
> New ScrollViewerHelper class with IsHorizontalScrollWheelEnabled

- src/MahApps.Metro/MahApps.Metro/Styles/Controls.Buttons.xaml
Use `FlatButtonForegroundBrush` in the new `MahApps.Metro.Styles.FlatButtonFocusVisualStyle` and use it for `MetroFlatButton` and `MetroFlatToggleButton`
Closes #3118 
Relates to #3118
> (#3118) Fix for dark theme FlatButton FocusVisualStyle Foreground

- src/MahApps.Metro/MahApps.Metro.Shared/Controls/Flyout.cs
The `AccentBaseColor` color could not be found which was introduced with 1.3.0 (which was a breaking change, if users has their own accents).
Closes #3109 
Relates to #3109
> (#3109) Fix NullReferenceException when using Flyout with theme

- src/MahApps.Metro.Samples/MahApps.Metro.Demo/MahApps.Metro.Demo.Shared/ExampleViews/ButtonsExample.xaml
- src/MahApps.Metro/MahApps.Metro/Styles/Controls.Buttons.xaml
Fix disabled foreground for MahApps.Metro.Styles.MetroCircleButtonStyle / obsolete MetroCircleButtonStyle and MetroCircleToggleButtonStyle .
Closes #3101 
Relates to #3101 
Relates to #3098
> (#3101) Fix disabled Foreground for MahApps.Metro.Styles.MetroCircleButtonStyle

- src/MahApps.Metro/MahApps.Metro.Shared/Controls/Helper/PasswordBoxHelper.cs
- src/MahApps.Metro/MahApps.Metro/Styles/Controls.PasswordBox.xaml
- Add 2 new attached properties `RevealButtonContent` and `RevealButtonContentTemplate` to `PasswordBoxHelper`
- Set the `DefaultRevealButtonIcon` to `RevealButtonContent` property
Closes #3105 
Relates to #3105
> (#3105) Allow to change the RevealButton Icon in the PasswordBox

- src/MahApps.Metro.Samples/MahApps.Metro.Demo/MahApps.Metro.Demo.Shared/MainWindow.xaml
- src/MahApps.Metro/MahApps.Metro/Styles/Controls.Buttons.xaml
- src/MahApps.Metro/MahApps.Metro/Themes/WindowButtonCommands.xaml
The Win 10 close button style is a little bit different to the MahApps one, so this PR adds the correct style for the close button (light and dark) (https://github.com/MahApps/MahApps.Metro/pull/2378#issuecomment-350606002).
- `MahApps.Metro.Styles.WindowButton.Close.Light.Win10`
- `MahApps.Metro.Styles.WindowButton.Close.Dark.Win10`
> Use the original Win 10 close button style

- src/MahApps.Metro/MahApps.Metro.Shared/Controls/Dialogs/BaseMetroDialog.cs
- src/MahApps.Metro/MahApps.Metro.Shared/Controls/Dialogs/DialogManager.cs
- src/MahApps.Metro/MahApps.Metro/Styles/Controls.xaml
- src/MahApps.Metro/MahApps.Metro/Themes/Dialogs/BaseMetroDialog.xaml
- src/MahApps.Metro/MahApps.Metro/Themes/Generic.xaml
- Create new style for Dialogs `MahApps.Metro.Styles.MetroDialog` and set this as default
- Add `BaseMetroDialog` resources to Control styles to allow easier dialog style manipulation
- Do not load all MahApps styles in code behind again (this is not necessary anymore, since it's now at Style level too)
- Fix inverted Dialogs theme (the background wasn't correct)
**Before**
**Now**
Closes #2813
> Fix Dialogs Resource handling

- src/MahApps.Metro/MahApps.Metro.Shared/Behaviours/WindowsSettingBehaviour.cs
- Fix possible Nullreference at `WindowsSettingBehavior`. Add some trace logging and check for null pointer.
- Add.: Fix wrong monitor positioning together with different Dpi usage for SetWindowPlacement
Closes #3107 
Closes #3110
> Fix for WindowsSettingBehaviour and possible AssociatedObject Nullreference

- src/MahApps.Metro/MahApps.Metro.Shared/Controls/HamburgerMenu/HamburgerMenu.cs
- src/MahApps.Metro/MahApps.Metro/Styles/Controls.xaml
- Set a selected Item only if there is no content set
- Add `HamburgerMenu` resources to Control styles to allow style manipulation and fix binding expression infos
Closes #3089 
Closes #3104 
Closes #3106
> Fix loaded content at HamburgerMenu

- src/MahApps.Metro/MahApps.Metro/Themes/Dialogs/BaseMetroDialog.xaml
- Template binding
- to horizontal and vertical alignment
- to all content properties (inner content)
- to SnapsToDevicePixels
- to Padding
- Add AutomationProperties names
Closes #3100
> Templated MetroDialog alignment

- src/MahApps.Metro/MahApps.Metro.Shared/Controls/Dialogs/DialogManager.cs
- src/MahApps.Metro/MahApps.Metro.Shared/Controls/MetroWindow.cs
Add a new (readonly) `IsAnyDialogVisible` dependency property. This property will be updated if a dialog is shown or not.
Closes #2806
> New IsAnyDialogVisible dependency property for MetroWindow

- src/MahApps.Metro/MahApps.Metro.Shared/Actions/CloseTabItemAction.cs
- src/MahApps.Metro/MahApps.Metro.Shared/Controls/Helper/TabControlHelper.cs
- src/MahApps.Metro/MahApps.Metro.Shared/Controls/MetroTabControl.cs
- src/MahApps.Metro/MahApps.Metro.Shared/Controls/MetroTabItem.cs
- src/MahApps.Metro/MahApps.Metro/Styles/Controls.TabControl.xaml
- src/MahApps.Metro/MahApps.Metro/Themes/MetroTabItem.xaml
- Remove internal close command and use the CloseTabItemAction
- Clear style and template for TabItem to prevent nasty binding expression errors
- Allow TabControlHelper dependency properties for TabItem too (the brushes)
Closes #3129
> Fix overriding (Metro)TabItem controltemplate/style

- src/MahApps.Metro/MahApps.Metro.Shared/Controls/NumericInput.cs
- src/MahApps.Metro/MahApps.Metro.Shared/Controls/NumericUpDown.cs
- src/MahApps.Metro/MahApps.Metro.Shared/MahApps.Metro.Shared.projitems
- Add new `NumericInputMode` property with the new flag enumeration NumericInput (default is NumericInput.All)
- Mark `HasDecimals` as obsolete
- Block scientific input if only numbers allowed
Closes #2422 
Closes #2423 
Closes #2496
> WIP NumericUpDown: Add a new property to handle the allowed numeric input

- src/MahApps.Metro/MahApps.Metro.Shared/Controls/HotKeyBox.cs
- src/MahApps.Metro/MahApps.Metro.Shared/Controls/NumericUpDown.cs
- src/MahApps.Metro/MahApps.Metro.Shared/Controls/TimePicker/TimePickerBase.cs
Problem: NumericUpDown, HotKeyBox and TimerPickerBase doesn't focus for the first time when the FocusManager will be used.
Fix not focusing at the OnGotFocus event.
Closes #3042
> Fix not focusing custom controls via FocusManager

- src/MahApps.Metro/MahApps.Metro.Shared/Controls/MetroWindow.cs
- src/MahApps.Metro/MahApps.Metro/Themes/MetroWindow.xaml
-  New `OverlayFadeIn` and `OverlayFadeOut` properties to set/override the overlay fade in/out Storyboards which are used for the Dialogs
- Fix the fade in and out animation if no duration exists
- Fix `HideMetroDialogAsync` which sometimes fails to close dialog (async call order)
Closes #2825 
Closes #3022
> WIP MetroWindow: OverlayFadeIn / OverlayFadeOut

- src/MahApps.Metro.Samples/MahApps.Metro.Demo/MahApps.Metro.Demo.Shared/ExampleViews/DateExamples.xaml
- src/MahApps.Metro/MahApps.Metro.Shared/Controls/Helper/ControlsHelper.cs
- src/MahApps.Metro/MahApps.Metro/Styles/Controls.DatePicker.xaml
Add new dependency property `ControlsHelper.IsReadOnly`.
This property sets the IsReadOnly property on the inner TextBox and the IsEnabled on the inner popup button.
> DatePicker IsReadOnly

- src/MahApps.Metro/MahApps.Metro.Shared/Controls/NumericUpDown.cs
- src/MahApps.Metro/MahApps.Metro/Themes/NumericUpDown.xaml
- Validate and convert new value on lost focus only if the text was manually changed
- Fix interaction between `IsReadOnly` and `InterceptManualEnter`
Closes #3166
> NumericUpdOwn LostFocus text validation

- src/MahApps.Metro.Samples/MahApps.Metro.Demo/MahApps.Metro.Demo.Shared/ExampleViews/DateExamples.xaml
- src/MahApps.Metro/MahApps.Metro/Styles/Controls.DatePicker.xaml
- src/MahApps.Metro/MahApps.Metro/Themes/MetroWindow.xaml
Use `BorderThickness` as Margin for inner `MetroWindow` content.
Closes #3175
> (GH-3175) MetroWindow: use BorderThickness as Margin for inner window content

- src/MahApps.Metro/MahApps.Metro.Shared/Controls/Dialogs/ProgressDialogController.cs
Added `ProgressDialogController.SetProgressBarForegroundBrush(Brush)` so that you can customize a progress dialog's progress bar foreground Brush. (Context: I wanted my `ProgressDialog` to have a white progress bar while the dialog itself used the `Accent` color scheme.)
> Add ability to set progress dialog progress bar brush color

- readme.md
Branch name was "dev" where it should be "develop".
> Fixing branch name for appveyor badges

- src/MahApps.Metro.Samples/MahApps.Metro.Demo/MainWindow.xaml
- src/MahApps.Metro/Controls/MetroWindow.cs
- src/MahApps.Metro/Themes/MetroWindow.xaml
- src/Mahapps.Metro.Tests/Tests/MetroWindowTest.cs
This PR fixes the wrong behavior while setting the `ShowTitleBar` property at the `MetroWindow`.
Closes #3192
> (GH-3192) Fix setting ShowTitleBar

- src/Directory.build.props
- src/MahApps.Metro.Samples/MahApps.Metro.Caliburn.Demo/MahApps.Metro.Caliburn.Demo.csproj
- src/MahApps.Metro.Samples/MahApps.Metro.Demo/MahApps.Metro.Demo.csproj
- src/MahApps.Metro.sln
- src/MahApps.Metro/MahApps.Metro.csproj
- src/MahApps.Metro/ThemeManager/Accent.cs
- src/MahApps.Metro/ThemeManager/AppTheme.cs
- src/MahApps.Metro/ThemeManager/ThemeManager.cs
- src/Mahapps.Metro.Tests/MahApps.Metro.Tests.csproj
- src/Mahapps.Metro.Tests/TestApp.xaml.cs
- src/Mahapps.Metro.Tests/TestHelpers/AccentHelper.cs
- src/Mahapps.Metro.Tests/TestHelpers/AutomationTestBase.cs
- src/Mahapps.Metro.Tests/TestHelpers/TestHost.cs
- src/Mahapps.Metro.Tests/Tests/FlyoutTest.cs
- src/Mahapps.Metro.Tests/Tests/ThemeManagerTest.cs
- src/Mahapps.Metro.Tests/Views/AnimatedTabControlWindow.xaml.cs
- src/Mahapps.Metro.Tests/Views/AutoWatermarkTestWindow.xaml.cs
- src/Mahapps.Metro.Tests/Views/ButtonWindow.xaml.cs
- src/Mahapps.Metro.Tests/Views/CleanWindow.xaml.cs
- src/Mahapps.Metro.Tests/Views/DateAndTimePickerWindow.xaml.cs
- src/Mahapps.Metro.Tests/Views/DialogWindow.xaml.cs
- src/Mahapps.Metro.Tests/Views/FlyoutWindow.xaml.cs
- src/Mahapps.Metro.Tests/Views/HiddenMinMaxCloseButtonsWindow.xaml.cs
- src/Mahapps.Metro.Tests/Views/TextBoxHelperTestWindow.xaml.cs
- src/Mahapps.Metro.Tests/paket.references
- src/build.cake
- src/paket.dependencies
- src/paket.lock
ThemeManager: overloaded ctors and methods to allow add accent and theme with resource 
dictionaries instead URIs.
Closes #3227
> (GH-3227) Fix for ThemeManager: dynamic accents only work once

- src/MahApps.Metro/Styles/FlatSlider.xaml
Changed binding for the `Height` property in the Horizontal FlatSlider style to bind to the Slider's `Height` property instead of `MinHeight`.
_Closed issues_
Closes https://github.com/MahApps/MahApps.Metro/issues/3238
> Fix for Track's height in FlatSlider style

- src/MahApps.Metro/Controls/NumericUpDown.cs
I have removed the handling for non-digits within the preview text input and this is now deferred until we attempt to parse the text value into the numeric representation.
The user is now able to specify their own parsing number style instead of replying on `NumberStyles.Any`. This means that we can correctly parse the value based on what the user wants, this also means that we will parse the value as an integer if the user supplies an input mode of 'Number'. The default of this value is `NumerStyles.Any` so as to maintain backwards compatibility.
I've manually tested this with as many use cases and data as I could think of and the existing behaviour of the NumericUpDown appears to have been maintained.
There does not appear to be any unit tests covering the NumericUpDown so I was unable …
> [3215] NumericUpDown - Hexdecimal input mode

- src/MahApps.Metro/Controls/Extensions.cs
- src/MahApps.Metro/Controls/FlipView.cs
- src/MahApps.Metro/Controls/Underline.cs
- Fix TabItem HeaderFontSize change leads to freeze
- Use new extension method ExecuteWhenLoaded
This issue appears only with  .Net 4.7.x. The reason for this is not clear, but it was  the Underline control, which sets some properties before the control is loaded.
Closes #3308
> (GH-3308) Fix TabItem HeaderFontSize change leads to freeze

- src/MahApps.Metro.Samples/MahApps.Metro.Demo/ExampleViews/HamburgerMenuDefault.xaml.cs
- src/MahApps.Metro.Samples/MahApps.Metro.Demo/MainWindow.xaml.cs
- src/MahApps.Metro/Controls/TimePicker/TimePickerBase.cs
- src/paket.dependencies
- src/paket.lock
- TimePicker: fix WPF0014 SetValue must use registered type.
- Demo MainWindow: WPF0005 Name of PropertyChangedCallback should match registered name.
- Demo MainWindow: WPF0019 Cast sender to correct type.
- Demo HamburgerMenuDefault:
+ WPF0120 Register containing member name as name for routed command.
+ WPF0122 Register name and owning type for routed command.
> Fix WpfAnalyzers warnings

- src/MahApps.Metro/ThemeManager/Theme.cs
- src/MahApps.Metro/ThemeManager/ThemeManager.cs
- src/Mahapps.Metro.Tests/Tests/ThemeManagerTest.cs
This PR changes the ThemeManager so that it reads the available themes from the assembly itself instead of using a hard coded list.
I will create a separate PR in which i will also eliminate the hard coded list of theme recognition resources keys to an embedded file.
The broader goal is to be able to fully share the ThemeManager code between MahApps.Metro and Fluent.Ribbon. ;-)
> Read available themes from assembly

- src/MahApps.Metro/ThemeManager/ThemeManager.cs
In case that the reg-key does not exists it returns `null` which is interpreted as `false` by `Convert.ToBoolean`
> Fixing light theme setting detection

- src/MahApps.Metro.Samples/MahApps.Metro.Demo/ExampleViews/CustomDialogExample.xaml
- src/MahApps.Metro.Samples/MahApps.Metro.Demo/MainWindow.xaml
- src/MahApps.Metro/Controls/Dialogs/InputDialog.xaml
- src/MahApps.Metro/Controls/Dialogs/InputDialog.xaml.cs
- src/MahApps.Metro/Controls/Dialogs/LoginDialog.xaml
- src/MahApps.Metro/Controls/Dialogs/LoginDialog.xaml.cs
- src/MahApps.Metro/Controls/Dialogs/MessageDialog.xaml
- src/MahApps.Metro/Controls/Dialogs/MessageDialog.xaml.cs
- src/MahApps.Metro/Controls/Dialogs/ProgressDialog.xaml
- src/MahApps.Metro/Themes/Dialogs/BaseMetroDialog.xaml
Fix for: Styling of buttons within a BaseMetroDialog should be facilitated
Change key style names and add style for normal button style in dialogs.
| old | new |
| --- | --- |
| AccentedDialogSquareButton | MahApps.Metro.Styles.Dialogs.AccentButton |
| AccentedDialogHighlightedSquareButton | MahApps.Metro.Styles.Dialogs.AccentHighlightButton |
| | MahApps.Metro.Styles.Dialogs.Button |
**Note**
A custom dialog must use the `MahApps.Metro.Styles.Dialogs.Button` style now explicit on every button.
Closes #3310
> Change Dialog Button Styles

- src/MahApps.Metro.Samples/MahApps.Metro.Demo/MainWindowViewModel.cs
- src/MahApps.Metro/Controls/Flyout.cs
- src/MahApps.Metro/ThemeManager/Theme.cs
- src/MahApps.Metro/ThemeManager/ThemeManager.StyleKeys.cs
- src/MahApps.Metro/ThemeManager/ThemeManager.cs
- src/Mahapps.Metro.Tests/TestHelpers/AutomationTestBase.cs
- src/Mahapps.Metro.Tests/Tests/ThemeManagerTest.cs
This PR once again syncs the ThemeManager code between MahApps.Metro and Fluent.Ribbon.
The changes include new APIs for changing themes, getting a list of available base colors and color schemes.
> Syncing ThemeManager code with Fluent.Ribbon

- src/MahApps.Metro.Samples/MahApps.Metro.Demo/ExampleViews/OtherExamples.xaml
- src/MahApps.Metro/Controls/ButtonsAlignment.cs
- src/MahApps.Metro/Controls/NumericUpDown.cs
- src/MahApps.Metro/Themes/NumericUpDown.xaml
Added more choices for positioning buttons on NumericUpDown control namely:
- New **ButtonsAlignment="OpposingSides**" option that will basically have the text box in the middle of the buttons.
- New **SwitchUpDownButtons** property that will switch the buttons places
For testing, I have changed the NumericUpDown that controls the index of FlipView2nd in the OtherExamples.xaml file.
> Added more choices for positioning buttons on NumericUpDown control

- src/MahApps.Metro.Samples/MahApps.Metro.Demo/ExampleViews/Sliders.xaml
- src/MahApps.Metro/Controls/RangeSlider.cs
Remove `AutoToolTipTextConverter` and add new properties to allow setting a DataTemplate for the AutoToolTip values (`AutoToolTipLowerValueTemplate`, `AutoToolTipUpperValueTemplate`, `AutoToolTipRangeValuesTemplate`)
Introduce also a helper class `RangeSliderAutoTooltipValues` which is used as the ToolTip content for the AutoToolTipRangeValuesTemplate.
**Example**
```xaml
<Controls:RangeSlider Width="200"
Margin="4"
Controls:SliderHelper.ChangeValueBy="LargeChange"
Controls:SliderHelper.EnableMouseWheel="MouseHover"
AutoToolTipPlacement="TopLeft"
LargeChange="10"
LowerValue="40"
Maximum="100"
Minimum="0"
Orientation="Horizontal"
SmallChange="1"
Style="{DynamicResource MahApps.Metro.Styles.RangeSlider.Win10}"
UpperValue="60"> …
```
> Add DataTemplates for range slider auto tool tip values

- src/MahApps.Metro.Samples/MahApps.Metro.Demo/ExampleViews/SelectionExamples.xaml
- src/MahApps.Metro.Samples/MahApps.Metro.Demo/MainWindowViewModel.cs
- src/MahApps.Metro/Controls/Helper/ScrollViewerHelper.cs
- src/MahApps.Metro/Controls/TreeHelper.cs
Add attached properties which allows to trigger the call to a command when reaching the end of the horizontal or vertical scrollable area. 
New `ScrollViewerHelper` attached properties are
- `EndOfVerticalScrollReachedCommand`
- `EndOfHorizontalScrollReachedCommand`
- `EndOfScrollReachedCommandParameter`
**Example**
```xaml
<ListBox Margin="2"
BorderThickness="1"
DisplayMemberPath="Name"
ItemsSource="{Binding Artists}"
SelectedIndex="0"
Controls:ScrollViewerHelper.EndOfVerticalScrollReachedCommand="{Binding EndOfScrollReachedCmdWithParameter, Mode=OneWay}"
Style="{StaticResource VirtualisedMetroListBox}" />
```
Original idea by this PR #2663 is from @Evangelink 
Closes #2615 
Closes …
> ScrollViewer end of scroll command

- src/MahApps.Metro.Samples/MahApps.Metro.Demo/MainWindow.xaml
- src/MahApps.Metro/Controls/MetroWindow.cs
Add new property `ShowSystemMenu`: Gets or sets a value that indicates whether the system menu should popup with left mouse click on the window icon.
Fix for: How to disable System Menu On Left Click at the Icon of a MetroWindow
Closes #3453
> (GH-3453) Add new property ShowSystemMenu

- src/MahApps.Metro.Samples/MahApps.Metro.Demo/ExampleViews/SelectionExamples.xaml
- src/MahApps.Metro/Controls/Helper/ComboBoxHelper.cs
- src/MahApps.Metro/Styles/Controls.ComboBox.xaml
- src/MahApps.Metro/Styles/Controls.DataGrid.xaml
- src/MahApps.Metro/Styles/Controls.ListBox.xaml
- src/MahApps.Metro/Styles/Controls.ListView.xaml
- src/MahApps.Metro/Themes/HamburgerMenuTemplate.xaml
Using `IsVirtualizingWhenGrouping` breaks virtualization for DataGrid and ItemsControls, so this PR fix this.
The obsolete `EnableVirtualizationWithGrouping` attached property will also be deleted.
Closes #3040
> (GH-3040) Fix grouping virtualization for DataGrid (ItemsControls)

- src/MahApps.Metro/Controls/DataGridNumericUpDownColumn.cs
- src/MahApps.Metro/Styles/Controls.DataGrid.xaml
It's not possible to change some properties for the `NumericUpDown` styles for the `DataGridNumericUpDownColumn`. To allow this, we introduce 2 new styles
- `MahApps.Metro.Styles.DataGrid.NumericUpDownColumnStyle`
- `MahApps.Metro.Styles.DataGrid.NumericUpDownColumnEditingStyle`
Now it's possible to used these styles to change properties.
Closes #3470
> (GH-3470) Fix for: DataGridNumericUpDownColumn - Vertical alignment

- src/MahApps.Metro/Controls/DataGridNumericUpDownColumn.cs
This PR expose more dependency properties for the `NumericUpDown` control at the `DataGridNumericUpDownColumn`. This makes it easier to control these properties without overriding the styles.
Closes #3266 
Closes #3335
> Expose more dependency properties for NumericUpDown control at DataGridNumericUpDownColumn

- src/MahApps.Metro/Controls/Helper/ControlsHelper.cs
- src/MahApps.Metro/Styles/Controls.Buttons.xaml
Add a new attached property `FocusBorderThickness` at `ControlsHelper` (which can be used for other styles too) to allow changing the border thickness for the default `MahApps.Metro.Styles.MetroButton` style.
Closes #3477
> (GH-3477) Add new attached property FocusBorderThickness

- src/MahApps.Metro.Samples/MahApps.Metro.Demo/ExampleViews/HamburgerMenuCreatorsUpdate.xaml
- src/MahApps.Metro/Controls/HamburgerMenu/HamburgerMenu.Properties.cs
- src/MahApps.Metro/Controls/HamburgerMenu/MenuItems/HamburgerMenuItem.cs
- src/MahApps.Metro/Controls/HamburgerMenu/MenuItems/HamburgerMenuItemBase.cs
- src/MahApps.Metro/Controls/HamburgerMenu/MenuItems/HamburgerMenuItemCollection.cs
- src/MahApps.Metro/Controls/HamburgerMenu/MenuItems/HamburgerMenuItemStyleSelector.cs
- src/MahApps.Metro/Controls/HamburgerMenu/MenuItems/HamburgerMenuSeparatorItem.cs
- src/MahApps.Metro/Themes/HamburgerMenu.xaml
- src/MahApps.Metro/Themes/HamburgerMenuTemplate.xaml
Add new `HamburgerMenuSeparatorItem` for `HamburgerMenu` to allow add seperators between the `HamburgerMenuItems`.
Closes #3434
> (GH-3434) Add new HamburgerMenuSeparatorItem for HamburgerMenu

- src/MahApps.Metro/Controls/MetroWindow.cs
- src/MahApps.Metro/Controls/WindowCommands.cs
- src/MahApps.Metro/Themes/MetroWindow.xaml
- src/MahApps.Metro/Themes/WindowCommands.xaml
If there are more then 2 or 3 window commands on the right or left site and the user resizes the window then the Min, Max, Close buttons move out the window and open dialogs will not resize to a slower size.
To solve this I changed the window commands control from ItemsControl to ToolBar class which allows us to use the overlow mechanism of this control.
- The default and centered window style will now use this new overflow mechanism.
These changes causes also a breaking change to the window commands overlay behavior. This feature will be removed, because a window command can now not overlay a Flyout if it's open.
Closes #1936 
Closes #3408
> Improvement for title bar and window commands

- .gitignore
- src/Directory.Build.Props
- src/MahApps.Metro.Samples/MahApps.Metro.Caliburn.Demo/MahApps.Metro.Caliburn.Demo.csproj
- src/MahApps.Metro.Samples/MahApps.Metro.Demo/ExampleWindows/FlyoutDemo.xaml
- src/MahApps.Metro.Samples/MahApps.Metro.Demo/MahApps.Metro.Demo.csproj
- src/MahApps.Metro/Controls/MetroWindow.cs
- src/MahApps.Metro/Controls/MetroWindowHelpers.cs
- src/MahApps.Metro/Controls/OverlayBehavior.cs
- src/MahApps.Metro/Controls/WindowCommandsOverlayBehavior.cs
- src/MahApps.Metro/MahApps.Metro.csproj
- src/Mahapps.Metro.Tests/MahApps.Metro.Tests.csproj
- src/Mahapps.Metro.Tests/Tests/FlyoutTest.cs
- src/Mahapps.Metro.Tests/Tests/MetroWindowTest.cs
After improving the title bar in #3503 the window commands and window button commands needs also a change for the overlay brushes.
Split WindowCommandsOverlayBehavior into 2 separate enumerations.
- `WindowCommandsOverlayBehavior` for Left and Right window commands
- `OverlayBehavior` for Icon and WindowButton commands
- ` WindowCommandsOverlayBehavior` contains now only 2 enumeration values (Never and HiddenTitleBar)
The new overlay behavior of the window commands needs also new overlay brushes. Because the window commands now doesn't overlay the Flyouts and so it's not necessary to set a calculated overlay brush for the foreground.
> Change window commands overlay behavior after title bar changes (GH-3503)

- .gitignore
- src/Directory.Build.Props
- src/MahApps.Metro.Samples/MahApps.Metro.Caliburn.Demo/MahApps.Metro.Caliburn.Demo.csproj
- src/MahApps.Metro.Samples/MahApps.Metro.Demo/ExampleWindows/FlyoutDemo.xaml
- src/MahApps.Metro.Samples/MahApps.Metro.Demo/MahApps.Metro.Demo.csproj
- src/MahApps.Metro/Controls/MetroWindow.cs
- src/MahApps.Metro/Controls/MetroWindowHelpers.cs
- src/MahApps.Metro/Controls/OverlayBehavior.cs
- src/MahApps.Metro/Controls/WindowCommandsOverlayBehavior.cs
- src/MahApps.Metro/MahApps.Metro.csproj
- src/MahApps.Metro/Styles/Controls.RadioButton.xaml
- src/Mahapps.Metro.Tests/MahApps.Metro.Tests.csproj
- src/Mahapps.Metro.Tests/Tests/FlyoutTest.cs
- src/Mahapps.Metro.Tests/Tests/MetroWindowTest.cs
The original radio button sets the Horizobtal and VarticalAlignment on Horizontal-/VerticalContentAlignmen. This allows that in a multiline content the radio button can be put on the firest line of text.
> Support to align the radio checkbox in RadioButton

- .gitignore
- paket.lock
- src/MahApps.Metro.Samples/MahApps.Metro.Demo/ExampleViews/OtherExamples.xaml.cs
- src/MahApps.Metro.Samples/MahApps.Metro.Demo/ExampleViews/TabControlExamples.xaml
- src/MahApps.Metro.Samples/MahApps.Metro.Demo/ExampleViews/TabControlExamples.xaml.cs
- src/MahApps.Metro/Controls/MetroTabControl.cs
- src/MahApps.Metro/ThemeManager/ThemeManager.cs
- src/MahApps.Metro/Themes/MetroTabControl.xaml
This PR changes the base class of BaseMetroTabControl from TabControl to TabControlEx from ControlzEx.
This allows us to keep the visual content in memory and prevent reloads of the UI contained in Tabs.
To be as flexible as possible i have added a need property `KeepVisualTreeInMemoryWhenChangingTabs` to `MetroTabControl`.
The default value is currently set to `false` to not break any current usages of the control.
> Use TabControlEx from ControlzEx as base class for BaseMetroTabControl

- src/MahApps.Metro/Controls/Dialogs/BaseMetroDialog.cs
- src/MahApps.Metro/Themes/Dialogs/BaseMetroDialog.xaml
Add properties to allow set the inner Dialog content GridLength.
- `DialogContentMargin`: Gets or sets the left and right margin for the dialog content. (default 25*)
- `DialogContentWidth`: Gets or sets the width for the dialog content. (default 50*)
Closes #3484 
/cc @Evangelink
> (GH-3484) Allow set Dialogs inner content Column GridLength

- src/MahApps.Metro/Controls/Dialogs/LoginDialog.xaml.cs
- src/MahApps.Metro/Controls/Dialogs/LoginDialogSettings.cs
Adds a new boolean property `RememberCheckBoxChecked` to the `LoginDialogSettings` which allows to configure the initial checked state of the remember checkbox.
Fix #3504
> (GH-3504) Add initial remember checkbox checked

- src/MahApps.Metro.Samples/MahApps.Metro.Demo/ExampleViews/TextExamples.xaml
- src/MahApps.Metro/Controls/NumericUpDown.cs
- src/MahApps.Metro/Themes/NumericUpDown.xaml
This PR was create after discussing with @wunianqing (#3522): The `NumericUpDown` control will response on every enter and change their value. This will cause a strange behavior when you binding value to a control like Slider. So I added a property to allow value effect after press enter.
The default is true to keep the  current behavior. If the up or down button will be used then the focus will move to it and triggers the lost focus event of the inner TextBox to change the value.
Add any other context or screenshots about the feature request here.
> NumericUpDown: Add a property to control changing value with key Enter

- src/MahApps.Metro/Behaviors/WindowsSettingBehavior.cs
- src/MahApps.Metro/Controls/Dialogs/DialogManager.cs
- src/MahApps.Metro/ThemeManager/ThemeManager.cs
Add null checks for usage of `Application.Current` in the main part of the library. Note that the demo and the unit tests haven't been updated as they are unlikely to be used wrapped in a WinForm App.
**Unit test**
No unit test added but if needed I can add a new test project with a WinForm app hosting the WPF MahApps window.
Fix #3544
> [GH-3544] Add null check for Application.Current

- src/MahApps.Metro.Samples/MahApps.Metro.Demo/App.xaml
- src/MahApps.Metro.Samples/MahApps.Metro.Demo/ExampleViews/ButtonsExample.xaml
- src/MahApps.Metro.Samples/MahApps.Metro.Demo/MainWindowViewModel.cs
- src/MahApps.Metro/Controls/CustomValidationPopup.cs
- src/MahApps.Metro/Controls/Helper/ValidationHelper.cs
- src/MahApps.Metro/Styles/ValidationErrorTemplate.xaml
Added a MouseOver Trigger to the Validation Template to show the Error Message.
- Add a new `ValidationHelper` static class for Validation.
- Add an attached property `ShowValidationErrorOnMouseOver` which can control this feature for a single control.
- Add also the same property to the `CustomValidationPopup` class to allow setting this behavior to all controls.
- Add an attached property `CloseOnMouseLeftButtonDown` to the `ValidationHelper` to enable setting this behavior for a single control.
Closes #3539
> Added a Trigger to MouseOver Property of ValidationMessage

- src/MahApps.Metro.Samples/MahApps.Metro.Demo/ExampleViews/ButtonsExample.xaml
- src/MahApps.Metro/Controls/Dialogs/DialogManager.cs
- src/MahApps.Metro/Controls/Dialogs/InputDialog.xaml
- src/MahApps.Metro/Controls/Dialogs/LoginDialog.xaml
- src/MahApps.Metro/Controls/Dialogs/MessageDialog.xaml
- src/MahApps.Metro/Controls/Dialogs/ProgressDialog.xaml
- src/MahApps.Metro/Themes/Dialogs/BaseMetroDialog.xaml
1. Add delegate to customize external dialog window.
1. Remove dialog button's height restriction, using MinHeight instead of Height.
**Unit test**
I really don't know,  sorry. Maybe some guidance?
None.
None.
> Add delegate to customize external dialog window

- src/MahApps.Metro/ThemeManager/ThemeManager.cs
Only check RDs that have keys and only if first RD has at least as many keys as second.
Otherwise we might detect RDs as equal that have zero keys.
Checking if the first RD has at least as many keys as the second just ensures that we don't compare apples with pineapples ;-)
> Improve check for RD "equality"

- src/MahApps.Metro/Themes/HamburgerMenuTemplate.xaml
The height of the inner `PaneHeader` DockPanel was set to the HamburgerHeight. This is wrong because it'll already set by the inner `HamburgerButton`.
Closes #3592
> (GH-3592) Fix HamburgerVisibility "Collapsed" state

- src/MahApps.Metro/Styles/Controls.Buttons.xaml
- src/MahApps.Metro/Styles/Themes/Theme.Template.xaml
Renamed the ResourceKey `SemiTransparentGrey `to `SemiTransparentGray ` to be consistent with the other `Gray` Resources
Closes #3575
> Renamed SemiTransparentGrey to SemiTransparentGray 

- src/MahApps.Metro.Samples/MahApps.Metro.Demo/ExampleViews/ButtonsExample.xaml
- src/MahApps.Metro/Styles/Controls.Buttons.xaml
- Added setter for the `Foreground` property to `MahApps.Styles.ToggleButton.Circle` when `IsEnabled=False`
- Added setter for the `Foreground` property to `MahApps.Styles.Button.Circle` when `IsEnabled=False`
- Updated demo with enabled/disabled version of `MahApps.Styles.Button.Circle` (current demo only display a custom derived style for Accent color)
Closes #3349
> (GH-3349) Fix disable content of ToggleButton & Button when using circle style

- src/MahApps.Metro.Samples/MahApps.Metro.Demo/ExampleViews/SplitViewExamples.xaml
- src/MahApps.Metro.Samples/MahApps.Metro.Demo/ExampleViews/TextExamples.xaml
- src/MahApps.Metro/MahApps.Metro.csproj
- src/MahApps.Metro/Styles/Controls.GridSplitter.xaml
- src/MahApps.Metro/Styles/Controls.xaml
- src/MahApps.Metro/Styles/VS/ListBox.xaml
- Added a Style for the `GridSplitter`-Control
- Make the new Style the default
- Updated the `SplitView`-Example with a `GridSplitter`
**Unit test**
I don't know, sorry!
Light-Mode:
Dark-Mode:
Closes #3612
> Add a Style for the GridSplitter-Control

- src/MahApps.Metro/Controls/HamburgerMenu/MenuItems/HamburgerMenuItem.cs
- src/MahApps.Metro/Controls/HamburgerMenu/MenuItems/HamburgerMenuItemStyleSelector.cs
- src/MahApps.Metro/Controls/HamburgerMenu/MenuItems/HamburgerMenuSeparatorItem.cs
- src/MahApps.Metro/Controls/HamburgerMenu/MenuItems/IHamburgerMenuItem.cs
- src/MahApps.Metro/Controls/HamburgerMenu/MenuItems/IHamburgerMenuSeparatorItem.cs
The new style selector doesn't work together with other items then directly derived from HamburgerMenuItem class. This commit fixes this, so it's possible to use any other classes too. Additionally it's possible to use classes derived from the new interface IHamburgerMenuItem.
> HamburgerMenu: Allow using own items together with the new HamburgerMenuItemStyleSelector

- src/MahApps.Metro.Samples/MahApps.Metro.Demo/ExampleWindows/VSDemo.xaml
- src/MahApps.Metro/Styles/VS/Button.xaml
- src/MahApps.Metro/Styles/VS/Colors.xaml
- src/MahApps.Metro/Styles/VS/Menu.xaml
- src/MahApps.Metro/Styles/VS/Styles.xaml
- src/MahApps.Metro/Styles/VS/TextBox.xaml
- Added resources to make the ContextMenu look correct when using the VS theme
- Made minor improvements to the default Button style for the VS theme
This PR is a fix for #2864 
- Add VS Context Menu style MahApps.Styles.ContextMenu.VisualStudio
- Override MahApps.TextBox.ContextMenu with the VS styles
> Fix that makes ContextMenu work with VS theme

- src/MahApps.Metro.Samples/MahApps.Metro.Demo/MainWindow.xaml
- src/MahApps.Metro.Samples/MahApps.Metro.Demo/MainWindow.xaml.cs
- src/MahApps.Metro/Controls/Dialogs/BaseMetroDialog.cs
- src/MahApps.Metro/Controls/Dialogs/DialogManager.cs
- src/MahApps.Metro/Controls/Dialogs/InputDialog.xaml
- src/MahApps.Metro/Controls/Dialogs/LoginDialog.xaml
- src/MahApps.Metro/Controls/Dialogs/MessageDialog.xaml
- src/MahApps.Metro/Controls/Dialogs/MetroDialogSettings.cs
- src/MahApps.Metro/Controls/Dialogs/ProgressDialog.xaml
- src/MahApps.Metro/Styles/Fonts.xaml
- src/MahApps.Metro/Themes/Dialogs/BaseMetroDialog.xaml
Added the DialogButtonFontSize Property to MetroDialogSettings and integrated them in sync with the existing implementations of DialogTitleFontSize and DialogMessageFontSize.
**Additional Context**
In a second commit (without issue reference) i also added an entry to the demo app sampling the usage of the new property. I didn't know whether this is appreciated or not.
Defaulting to 12pt:
Using override 30pt:
Closes #3618
> Add the ability to control button font size in dialogs via MetroDialogSettings

- src/MahApps.Metro/Converters/CornerRadiusBindingConverter.cs
- src/MahApps.Metro/Converters/RadiusType.cs
- src/MahApps.Metro/Converters/ThicknessBindingConverter.cs
- src/MahApps.Metro/Converters/ThicknessToDoubleConverter.cs
- src/MahApps.Metro/Styles/Controls.DataGrid.xaml
- src/MahApps.Metro/Styles/Controls.Expander.xaml
- src/MahApps.Metro/Styles/Controls.GroupBox.xaml
- src/MahApps.Metro/Styles/Controls.ListBox.xaml
- src/MahApps.Metro/Styles/Controls.ListView.xaml
- src/MahApps.Metro/Styles/Controls.TreeView.xaml
- src/MahApps.Metro/Styles/ValidationErrorTemplate.xaml
> More CornerRadius usage

- src/MahApps.Metro/Styles/Controls.Buttons.xaml
- src/MahApps.Metro/Styles/VS/Button.xaml
Changed the styles of almost all Buttons to support `ControlsHelper.CornerRadius`. This does NOT change the default style, but now a user can have an `AccentedSquareButton` with a `CornerRadius` (yes I know it does not make sense from the word, but someone might find it beautiful)
**Unit test**
None
Here is the result: 
#3299 #2871 
Happy coding
Tim
> Added AttachedProperty CornerRadius to all Buttons (optional)

- src/MahApps.Metro/Controls/NumericUpDown.cs
- src/Mahapps.Metro.Tests/Tests/NumericUpDownTests.cs
Fix issue with P, % and ‰ used in the StringFormat property of NumericUpDown but outside of the format item. "{}{0:P}" would work but "{}{0:0.0} P" would not work correctly.
**Unit test**
Added additional asserts in appropriate unit tests.
**Related Issues**
This PR fixes a couple of problems mentioned in #3376 but does not resolve the issue completely. It only deals with using special characters outside of the format item. Other concerns in the issue is left unresolved.
> Fix issue with P, % and ‰ used in StringFormat outside of the format item

- src/MahApps.Metro/Styles/Controls.AnimatedSingleRowTabControl.xaml
Fix Missing ComboBox Scrollbars when using Controls.AnimatedSingleRowTabControl.
Renamed templates and styles
- MahApps.Styles.RepeatButton.ScrollBar -> MahApps.Styles.RepeatButton.ScrollBar.AnimatedSingleRow
- MahApps.Templates.ScrollBar.Horizontal -> MahApps.Templates.ScrollBar.AnimatedSingleRow.Horizontal
- MahApps.Templates.ScrollBar.Vertical -> MahApps.Templates.ScrollBar.AnimatedSingleRow.Vertical
- MahApps.Templates.ScrollViewer -> MahApps.Templates.ScrollViewer.AnimatedSingleRow
- MahApps.Templates.TabControl.Horizontal -> MahApps.Templates.TabControl.AnimatedSingleRow.Horizontal
- MahApps.Templates.TabControl.Vertical -> MahApps.Templates.TabControl.AnimatedSingleRow.Vertical
Closes #3647
> Subsequent changes after GH-3552

- src/MahApps.Metro/Controls/SplitView/SplitView.cs
- src/MahApps.Metro/Themes/SplitView.xaml
- Adds a new `OverlayBrush` dependency property to the `SplitView`. 
Closes #3661
> Add an OverlayBrush to the SplitView

- src/MahApps.Metro/Controls/SplitButton.cs
- src/MahApps.Metro/Styles/Controls.ComboBox.xaml
- src/MahApps.Metro/Themes/SplitButton.xaml
Derive `SplitButton` from ComboBox to fix disappearing Items. Implementing only the interesting stuff from the ComboBox is not possible because of too many internal things.
- Derive from ComboBox
- `IsExpanded` DP is now `IsDropDownOpen`
- Remove `ListBoxStyle` DP
- The `SplitButton` template uses now an ItemsPresenter like the ComboBox instead a full ListBox
- The `IsEditable` property will be ignored and is always set to false
- Update documentation
Closes #3513
> Fix SplitButton contents disappearing on subsequent clicks

- src/MahApps.Metro.Samples/MahApps.Metro.Demo/ExampleViews/DateExamples.xaml
- src/MahApps.Metro.Samples/MahApps.Metro.Demo/ExampleViews/SelectionExamples.xaml
- src/MahApps.Metro/Styles/Controls.ComboBox.xaml
- src/MahApps.Metro/Styles/Controls.DataGrid.xaml
- src/MahApps.Metro/Styles/Controls.DatePicker.xaml
- src/MahApps.Metro/Styles/Controls.PasswordBox.xaml
- src/MahApps.Metro/Styles/Controls.TextBox.xaml
- src/MahApps.Metro/Themes/DateTimePicker.xaml
- src/MahApps.Metro/Themes/HotKeyBox.xaml
- src/MahApps.Metro/Themes/NumericUpDown.xaml
The padding for all input controls are hard coded in there styles, so it's not possible to override these settings in an easy way.
> Fix padding for input controls

- src/MahApps.Metro.Samples/MahApps.Metro.Demo/ExampleViews/TextExamples.xaml
- src/MahApps.Metro/Controls/NumericUpDown.cs
- src/Mahapps.Metro.Tests/Tests/NumericUpDownFixture.cs
- src/Mahapps.Metro.Tests/Tests/NumericUpDownTests.cs
The current behavior for e.g. percentage text input with StringFotmat like P0 or {0:0.00%} converts the input one-to-one to the value:
100% = 100
This is not what the user expects, because the .Net default works different:
100% = 1
So this PR changes this behavior to the .Net default one.
**Unit test**
Closes #3376 
/cc @mgnslndh @timunie
> Handle NumericUpDown percentage StringFormat correctly

- src/MahApps.Metro.Samples/MahApps.Metro.Demo/ExampleWindows/VSDemo.xaml
- src/MahApps.Metro/Styles/VS/Colors.xaml
- src/MahApps.Metro/Styles/VS/Menu.xaml
- Add new VS brush `MahApps.Brushes.Menu.Checkmark.Fill`
- Add new VS brush `MahApps.Brushes.Menu.Checkmark.Background`
Found at [SO](https://stackoverflow.com/q/29234024/920384)
```xaml
<MenuItem Header="Switch to...">
<MenuItem IsCheckable="True" IsChecked="True" Header="Stroke-Based" StaysOpenOnClick="True" />
<MenuItem IsCheckable="True" IsChecked="True" Header="Color-Transfer" StaysOpenOnClick="True" />
</MenuItem>
```
**Fixed**
> Add CheckMark for VS MenuItem

- src/MahApps.Metro.Samples/MahApps.Metro.Demo/ExampleViews/HamburgerMenuCreatorsUpdate.xaml
- src/MahApps.Metro/Controls/HamburgerMenu/HamburgerMenu.Events.cs
- src/MahApps.Metro/Controls/HamburgerMenu/HamburgerMenu.Properties.cs
- src/MahApps.Metro/Controls/HamburgerMenu/HamburgerMenu.cs
- src/MahApps.Metro/Controls/HamburgerMenu/MenuItems/HamburgerMenuHeaderItem.cs
- src/MahApps.Metro/Controls/HamburgerMenu/MenuItems/HamburgerMenuItemStyleSelector.cs
- src/MahApps.Metro/Controls/HamburgerMenu/MenuItems/IHamburgerMenuHeaderItem.cs
- src/MahApps.Metro/Themes/HamburgerMenu.xaml
- src/MahApps.Metro/Themes/HamburgerMenuTemplate.xaml
- Add new `HamburgerMenuHeaderItem` (`IHamburgerMenuHeaderItem`)
An item which can be used to show a header above other HamburgerMenu items.
- Prevent selection for IHamburgerMenuHeaderItem and IHamburgerMenuSeparatorItem
- Use HamburgerMenuHeaderItem at creators style sample
> Add new HamburgerMenuHeaderItem

- src/MahApps.Metro.Samples/MahApps.Metro.Demo/ExampleViews/SelectionExamples.xaml
- src/MahApps.Metro.Samples/MahApps.Metro.Demo/MainWindowViewModel.cs
- src/MahApps.Metro/Controls/Helper/MultiSelectorHelper.cs
- Added new `MultiSelectorHelper`, an item that allows for 2 way binding between a multiselector/listbox and a collection for selected items.
- Updated `Selection` tab to use `MultiSelectorHelper` in the listbox sample
**Unit test**
None
None
> Add helper for multi selected binding for Listbox/Multiselector controls

- src/MahApps.Metro.Samples/MahApps.Metro.Demo/ExampleViews/DateExamples.xaml
- src/MahApps.Metro.Samples/MahApps.Metro.Demo/MainWindowViewModel.cs
- src/MahApps.Metro/Controls/Helper/DatePickerHelper.cs
- src/MahApps.Metro/Controls/Helper/MahAppsCommands.cs
- src/MahApps.Metro/Controls/MetroWindow.cs
- src/MahApps.Metro/Styles/Controls.DatePicker.xaml
- src/MahApps.Metro/Themes/DateTimePicker.xaml
- Add `DatePickerHelper` with new attached properties. This allows us to handle this button separately to another clear button.
- `DropDownButtonContent`
- `DropDownButtonContentTemplate`
- `DropDownButtonFontFamily`
- `DropDownButtonFontSize`
- Use new DatePicker helper for `DateTimePicker` and `TimePicker`
- Introduce `MahAppsCommands.ClearControlCommand`
- This command does the same as the attached TextBoxHelper IsClearTextButtonBehaviorEnabled property and should be used later for all controls too. So then we doesn't need 2 separate styles for ButtonCommand usage.
**Unit test**
-/-
Closes #3656
> DatePicker enhancements

- src/MahApps.Metro/Controls/Dialogs/DialogManager.cs
- src/MahApps.Metro/Controls/Extensions.cs
- src/MahApps.Metro/Controls/WinApiHelper.cs
- Added a check for window state in `CreateModalExternalWindow`
- Added a border offset to take in account the overhang on both sides of the window when maximized causing a dialog to extend outside of the screen bounds.
- Fix `SetupExternalDialogWindow`
Use the monitor from where the owner stays and use the working area for the dialog size properties and remove also the left and right border.
- Simplify getting the working area from current monitor with new extension method `GetMonitorWorkSize`
Use this method in both variants SetupExternalDialogWindow and CreateModalExternalWindow which also fixes the main issue without calculating an offset by hand.
Closes #3538
> Improved external dialog to no longer extend onto other monitors

- src/MahApps.Metro/Controls/Helper/TreeViewItemHelper.cs
- src/MahApps.Metro/Styles/Controls.TreeView.xaml
Add this new attached property to make it possible to set the inner ToggleButton style. The default is `MahApps.Styles.ToggleButton.ExpandCollapse`.
Sample
```xaml
<Style BasedOn="{StaticResource MahApps.Styles.TreeViewItem}" TargetType="{x:Type TreeViewItem}">
<Setter Property="controls:TreeViewItemHelper.ToggleButtonStyle">
<Setter.Value>
<Style BasedOn="{StaticResource MahApps.Styles.ToggleButton.ExpandCollapse}" TargetType="{x:Type ToggleButton}">
<Setter Property="Visibility" Value="Hidden" />
</Style>
</Setter.Value>
</Setter>
</Style>
```
or
```xaml
<Style x:Key="SpecialCustomTreeViewItemToggleButtonStyle" BasedOn="{StaticResource MahApps.Styles.ToggleButton.ExpandCollapse}" TargetType="{x:Type ToggleButton}">
<Setter Property="Visibility" Value="Hidden" />
</Style>
<Style …
```
> Add new attached property TreeViewItemHelper.ToggleButtonStyle

- src/MahApps.Metro/Controls/ContentControlEx.cs
- src/MahApps.Metro/Controls/Helper/ControlsHelper.cs
- src/MahApps.Metro/Styles/Clean/CleanGroupBox.xaml
- src/MahApps.Metro/Styles/Controls.Buttons.xaml
- src/MahApps.Metro/Styles/Controls.CheckBox.xaml
- src/MahApps.Metro/Styles/Controls.DataGrid.xaml
- src/MahApps.Metro/Styles/Controls.Expander.xaml
- src/MahApps.Metro/Styles/Controls.GroupBox.xaml
- src/MahApps.Metro/Styles/Controls.Label.xaml
- src/MahApps.Metro/Styles/Controls.ListView.xaml
- src/MahApps.Metro/Styles/Controls.PasswordBox.xaml
- src/MahApps.Metro/Styles/Controls.RadioButton.xaml
- src/MahApps.Metro/Styles/Controls.TabControl.xaml
- src/MahApps.Metro/Styles/Controls.Toolbar.xaml
- src/MahApps.Metro/Styles/VS/Expander.xaml
- src/MahApps.Metro/Styles/VS/GroupBox.xaml
- src/MahApps.Metro/Styles/VS/TabControl.xaml
- src/MahApps.Metro/Themes/DropDownButton.xaml
- src/MahApps.Metro/Themes/FlipView.xaml
- src/MahApps.Metro/Themes/Flyout.xaml
- src/MahApps.Metro/Themes/HamburgerMenuTemplate.xaml
- src/MahApps.Metro/Themes/MetroHeader.xaml
- src/MahApps.Metro/Themes/MetroTabItem.xaml
- src/MahApps.Metro/Themes/SplitButton.xaml
- src/MahApps.Metro/Themes/WindowCommands.xaml
Introduce a new attached dependency property `ControlsHelper.RecognizesAccessKey` to allow set the `RecognizesAccessKey` of controls which has a `ContentControlEx` / `ContentPresenter` inside.
Closes #3715
> Introduce new attached property ControlsHelper.RecognizesAccessKey

- src/MahApps.Metro.Samples/MahApps.Metro.Demo/ExampleViews/ButtonsExample.xaml
- src/MahApps.Metro/Controls/Helper/RadioButtonHelper.cs
- src/MahApps.Metro/Styles/Controls.CheckBox.xaml
- src/MahApps.Metro/Styles/Controls.RadioButton.xaml
- src/MahApps.Metro/Styles/Themes/Theme.Template.xaml
This PR add the Windows 10 18362 RadioButton style `MahApps.Styles.RadioButton.Win10`.
MahApps.Brushes.RadioButton.Foreground
MahApps.Brushes.RadioButton.ForegroundPointerOver
MahApps.Brushes.RadioButton.ForegroundPressed
MahApps.Brushes.RadioButton.ForegroundDisabled
MahApps.Brushes.RadioButton.Background
MahApps.Brushes.RadioButton.BackgroundPointerOver
MahApps.Brushes.RadioButton.BackgroundPressed
MahApps.Brushes.RadioButton.BackgroundDisabled
MahApps.Brushes.RadioButton.BorderBrush
MahApps.Brushes.RadioButton.BorderBrushPointerOver
MahApps.Brushes.RadioButton.BorderBrushPressed
MahApps.Brushes.RadioButton.BorderBrushDisabled
MahApps.Brushes.RadioButton.OuterEllipseStroke …
> Add RadioButton Windows 10 Style

- src/MahApps.Metro/Styles/Themes/Theme.Template.xaml
- src/Mahapps.Metro.Tests/TestHelpers/ThemeHelper.cs
This is just a rough fix.
The code is not optimized for performance.
As the whole ThemeHelper will be replaced with the RuntimeThemeGenerator from ControlzEx i will use better optimized code there.
> Fixes UnitTest failures by adjusting the XAML content before parsing

- src/MahApps.Metro/Controls/HamburgerMenu/MenuItems/HamburgerMenuItemBase.cs
- src/MahApps.Metro/Themes/HamburgerMenuTemplate.xaml
I've added a Visibility property to HamburgerMenuItem and HamburgerMenuSeparatorItem in response to issue #3768 
It will closes #3768
> Add IsVisible property to HambugerMenuItemBase

- src/MahApps.Metro.Samples/MahApps.Metro.Demo/ExampleViews/ButtonsExample.xaml
- src/MahApps.Metro.Samples/MahApps.Metro.Demo/MainWindowViewModel.cs
- src/MahApps.Metro/Controls/CommandHelpers.cs
- src/MahApps.Metro/Controls/ToggleSwitch.cs
Add OnCommand and OffCommand properties to the ToggleSwitch. The previous ToggleSwitch had similar commands which allowed simple logic for this 2 states.
The command parameter for both commands will be the value of the CommandParameter or the ToggleSwitch if the property is null.
If the commands are not executable then the ToggleSwitch is still enabled, it will only disable the execuation.
e.g.
```xaml
<Controls:ToggleSwitch CommandParameter="{Binding}"
OnCommand="{Binding ToggleSwitchOnCommand}"
OffCommand="{Binding ToggleSwitchOffCommand}" />
```
Closes #3783
> (GH-3783) Add OnCommand and OffCommand to ToggleSwitch

- src/MahApps.Metro.Samples/MahApps.Metro.Demo/ExampleViews/ButtonsExample.xaml
- src/MahApps.Metro/Controls/Badged.cs
- src/MahApps.Metro/Converters/SizeToCornerRadiusConverter.cs
- src/MahApps.Metro/Themes/Badged.xaml
- Added a `BadgeTemplate` and `BadgeTemplateSelector` to the `Badge` control
- Set the `MinWidth` to be `ActualHeight`. That way we make sure the Badge shape is correct
- Set the `Badge` `CornerRadius` to the half of `ActualHeight`. This lets the control look rounded as before, even with bigger content 
**Unit test**
None
preview:
#3789
> Added a way to use DataTemplate in BadgedControl

- src/MahApps.Metro/Controls/CustomValidationPopup.cs
I was having an issue where the canShow variable always ends up false.
This change should fix the problem and not interfere in the current logical flow.
> Fixed Validation Tooltip that never shows up.

- src/MahApps.Metro.Samples/MahApps.Metro.Demo/ExampleWindows/VSDemo.xaml
- src/MahApps.Metro/Controls/Helper/ExpanderHelper.cs
- src/MahApps.Metro/Styles/Controls.Expander.xaml
- src/MahApps.Metro/Styles/VS/Expander.xaml
The Expander reserves internal needed space before expanding. This PR fixes this.
Additionally the collapse storyboard needs to set a keyframe to visible, because it collapse the expander directly if the storyboard is executed for the first time (strange behavior).
Closes #3812
> (GH-3812) Fix wrong space for Expander before expanded

- src/MahApps.Metro/Accessibility/AccessibilitySwitches.cs
- src/MahApps.Metro/Styles/Controls.DatePicker.xaml
- src/MahApps.Metro/Themes/DateTimePicker.xaml
We use a DatePickerTextBox inside the TimePickerBase which causes these errors with TargetFramework 4.8 and higher.
The DatePickerTextBox style uses triggers for UseNetFx472CompatibleAccessibilityFeatures, but the Bindings are looking for a DatePicker, that's why we get these errors.
To fix this we added a new style for our DatePickerTextBox called `MahApps.Styles.DatePickerTextBox.TimePickerBase`.
Closes #3829
> (GH-3829) Fix DateTimePicker BindingExpression errors

- src/MahApps.Metro/Styles/Controls.RadioButton.xaml
We need to use a different brush or an attached property to set the Fill and Stroke properties.
For now we use the MahApps.Brushes.ThemeBackground and MahApps.Brushes.CheckBox.
Closes #3821
> (GH-3821) Fix Fill and Stroke brush for RadioButton's outer ellipse

- src/MahApps.Metro/Controls/HamburgerMenu/HamburgerMenu.Properties.cs
Fix coercing of OpenPaneLength at HamburgerMenu.
The current behavior gives us a wrong value and a wrong UI.
Closes #3817
> (GH-3817) Fix coercing of OpenPaneLength at HamburgerMenu

- src/MahApps.Metro.Samples/MahApps.Metro.Demo/ExampleViews/TextExamples.xaml
- src/MahApps.Metro.Samples/MahApps.Metro.Demo/MainWindowViewModel.cs
- src/MahApps.Metro/Controls/DecimalPointCorrectionMode.cs
- src/MahApps.Metro/Controls/NumericUpDown.cs
If the user hits the `Decimal`-Key let's type the decimal separator which the current culture use. 
Introduce a new dependency property `DecimalPointCorrection` to allow override the decimal-point culture input for the TextBox.
(solution taken from https://highfieldtales.wordpress.com/2014/10/19/numpads-decimal-point-correction-for-wpf)
Closes #3843
> [NumericUpDown] Always use the current cultures decimal separator

- src/MahApps.Metro.Samples/MahApps.Metro.Demo/ExampleViews/TextExamples.xaml
- src/MahApps.Metro/Styles/Controls.FlatSlider.xaml
The current MinWidth and MinHeight of the horizontal and vertical Flat slider was hard coded. So introduce 2 new resource keys to allow changing these values dynamically.
- MahApps.Sizes.Slider.Flat.Horizontal.MinHeight (default 12)
- MahApps.Sizes.Slider.Flat.Vertical.MinWidth (default 12)
> Add Flat slider resource keys for MinWidth and MinHeight

- src/MahApps.Metro/Controls/HamburgerMenu/HamburgerMenuListBox.cs
- src/MahApps.Metro/Controls/HamburgerMenu/MenuItems/HamburgerMenuItemBase.cs
- src/MahApps.Metro/Controls/HamburgerMenu/MenuItems/IHamburgerMenuItemBase.cs
- src/MahApps.Metro/Themes/Generic.xaml
- src/MahApps.Metro/Themes/HamburgerMenuTemplate.xaml
Introduce HamburgerMenuListBox class which handles the IsVisible (IHamburgerMenuItemBase) and IsEnabled (IHamburgerMenuItem) properties and bind them to the properties of the ListBoxItem.
This makes it easier to use own ViewModel collections which are mostly not implement these properties. But now it can be done with the interfaces.
[Here is an example](https://github.com/punker76/code-samples/tree/main/MahAppsMetroHamburgerMenu) for this scenario:
Closes #3859
> (GH-3859) Allow own ViewModel collection for HamburgerMenu ItemsSource

- src/MahApps.Metro/Controls/Helper/RadioButtonHelper.cs
- src/MahApps.Metro/Styles/Controls.RadioButton.xaml
Added new attached properties to the RadioButtonHelper to allow change all brushes and size for a RadioButton easily.
RadioButtonHelper.RadioSize
RadioButtonHelper.RadioCheckSize
RadioButtonHelper.ForegroundPointerOver
RadioButtonHelper.ForegroundPressed
RadioButtonHelper.ForegroundDisabled
RadioButtonHelper.BackgroundPointerOver
RadioButtonHelper.BackgroundPressed
RadioButtonHelper.BackgroundDisabled
RadioButtonHelper.BorderBrushPointerOver
RadioButtonHelper.BorderBrushPressed
RadioButtonHelper.BorderBrushDisabled
RadioButtonHelper.OuterEllipseFill
RadioButtonHelper.OuterEllipseFillPointerOver
RadioButtonHelper.OuterEllipseFillPressed
RadioButtonHelper.OuterEllipseFillDisabled
RadioButtonHelper.OuterEllipseStroke
RadioButtonHelper.OuterEllipseStrokePointerOver …
> Added new attached properties to the RadioButtonHelper

- src/MahApps.Metro/Automation/Peers/MetroWindowAutomationPeer.cs
- src/MahApps.Metro/Controls/MetroWindow.cs
- src/MahApps.Metro/Controls/WinApiHelper.cs
Make some extra checks before calling GetWindowTextLength and GetWindowText to prevent Win32Exception.
Works only with ControlzEx 4.3.2 and later.
Closes #3892
> Add MetroWindowAutomationPeer to prevent Win32Exception

- src/MahApps.Metro/Automation/Peers/WindowCommandsAutomationPeer.cs
- src/MahApps.Metro/Controls/MetroWindow.cs
- src/MahApps.Metro/Controls/WindowCommands.cs
- src/MahApps.Metro/Themes/WindowCommands.xaml
Fix Accessibility Insights issues with WindowCommands.
- Add `WindowCommandsAutomationPeer` class
- Set AutomationProperties name to `LeftWindowCommands` or `RightWindowCommands`
- Set AutomationProperties name for overflow button to `OverflowToggleButton`
Closes #3894
> Fix Accessibility Insights issues with WindowCommands

- src/MahApps.Metro/Themes/WindowButtonCommands.xaml
Accessibility for WindowButtonCommands
- Set AutomationProperties AutomationId and Name for Min/Max/Restore/Close buttons.
> Accessibility fixes for WindowButtonCommands

- src/MahApps.Metro/MahApps.Metro.csproj
- src/MahApps.Metro/VisualStudioToolsManifest.xml
Add all possible MahApps controls to the `VisualStudioToolsManifest.xml` file so that all custom control will be populated in the Visual Studio toolbox.
Refer to this [link](https://docs.microsoft.com/en-us/nuget/guides/create-ui-controls#add-toolboxassets-pane-support-for-xaml-controls) for more information about the structure of the VisualStudioToolsManifest file.
[Blog post](https://www.syncfusion.com/blogs/post/add-net-core-3-0-custom-control-to-your-visual-studio-toolbox.aspx)
> Add Custom Controls to the Visual Studio Toolbox

- src/MahApps.Metro/Controls/Helper/TextBoxHelper.cs
Now an update of the binding is done before executing the command of "TextBoxHelper.ButtonCommand".
guess not
See #3924 
#3924
> Update Binding before executing the command of "TextBoxHelper.ButtonCommand"

- src/MahApps.Metro/Controls/DataGridNumericUpDownColumn.cs
Add a missing DecimalPointCorrection property to DataGridNumericUpDownColumn
Closes #3903
> Add DecimalPointCorrection property to DataGridNumericUpDownColumn

- src/MahApps.Metro/Controls/CustomValidationPopup.cs
- src/MahApps.Metro/Controls/Flyout.cs
The validation error was not shown on Flyout after the Flyout is shown.
Introduce a new Flyout property `IsShown` to indicate that the Flyout is completely shown after `IsOpen` property was set to true.
Closes #3943
> Fix not displaying validation error on Flyout

- src/MahApps.Metro.Samples/MahApps.Metro.Demo/ExampleViews/SelectionExamples.xaml
- src/MahApps.Metro/Controls/Helper/ItemHelper.cs
- src/MahApps.Metro/Styles/Controls.ComboBox.xaml
- src/MahApps.Metro/Styles/Controls.ListBox.xaml
- src/MahApps.Metro/Styles/Controls.ListView.xaml
- src/MahApps.Metro/Styles/Controls.TreeView.xaml
- src/MahApps.Metro/Themes/HamburgerMenuTemplate.xaml
- Fix overriding of ItemsControl items background
- Allow set background and foreground for mouse right and left button down
Add 4 new properties to ItemHelper
+ MouseLeftButtonPressedBackgroundBrush
+ MouseLeftButtonPressedForegroundBrush
+ MouseRightButtonPressedBackgroundBrush
+ MouseRightButtonPressedForegroundBrush
Closes #3900 
Closes #3947
> Fix overriding of ItemsControl items background

- src/MahApps.Metro.Samples/MahApps.Metro.Demo/MainWindow.xaml.cs
- src/MahApps.Metro/Behaviors/BorderlessWindowBehavior.cs
- src/MahApps.Metro/Controls/ContentControlEx.cs
- src/MahApps.Metro/Controls/ContentPresenterEx.cs
- src/MahApps.Metro/Themes/ContentControlEx.xaml
- src/MahApps.Metro/Themes/MetroWindow.xaml
- Set Icon always hit test visible to chrome
- Fix template binding for inner grid background for ContentControlEx
- Bind the IsHitTestVisibleInChromeProperty to the content of the ContentControlEx
- Bind the IsHitTestVisibleInChromeProperty to the content of the new ContentPresenterEx
Closes #3963
> Fix not showing GlowBrush if ResizeMode is set to NoResize

- src/MahApps.Metro.Samples/MahApps.Metro.Demo/ExampleWindows/CleanWindowDemo.xaml
- src/MahApps.Metro/Styles/Controls.Shadows.xaml
- src/MahApps.Metro/Styles/VS/Shadows.xaml
- there is a dotMemory unit testing nuget out there but don't know much about it..
I've updated all DropShadowEffects (including VS & DropShadowBrush)- assuming there is no usage where x:Shared=True is appropriate
Closes #3974
> Drop shadow effect memory leak

- src/MahApps.Metro/Styles/Controls.ContextMenu.xaml
- src/MahApps.Metro/Styles/VS/ContextMenu.xaml
Added `x:Shared="False"` to the context menu (cut/copy/paste), used for all text-box controls.
none
There seems to be a lot of confusion about the sharing of context menus on the internet:
- Look at what Linda is replying to Bill Gates II [here](https://social.msdn.microsoft.com/Forums/vstudio/en-US/05dc431e-731e-415d-88ac-daa028f0a03e/using-a-contextmenu-resource-more-than-once?forum=wpf)
- [Here](https://www.c-sharpcorner.com/Resources/651/how-to-share-a-contextmenu-in-wpf.aspx) they explicitly show x:Shared="true" 
My guess is that it probably has to do with something in the style- as it the leak doesn't grow up in instances, it's one per control type (I think). 
Either that or it's the shared RoutedCommands (can there be a problem with those being shared!?)
If anyone understands the …
> Adding x:Shared="False" to MahApps.TextBox.ContextMenu

- src/MahApps.Metro/Controls/Dialogs/InputDialog.xaml.cs
- src/MahApps.Metro/Controls/Dialogs/LoginDialog.xaml.cs
- src/MahApps.Metro/Controls/Dialogs/MessageDialog.xaml.cs
- src/MahApps.Metro/Controls/Dialogs/ProgressDialogController.cs
Fix InvalidOperationException at registered CancellationToken delegate.
Closes #3214
> Fix InvalidOperationException at registered CancellationToken delegate

- .gitignore
- build.cake
- src/MahApps.Metro/Styles/Controls.MenuItem.xaml
- src/MahApps.Metro/Styles/VS/MenuItem.xaml
- tools/packages.config
Fix HorizontalAlignment of ContextMenu Icon. The default was set to Left which doesn't look nice.
> Fix HorizontalAlignment of ContextMenu Icon

- src/MahApps.Metro/Converters/ColorToSolidColorBrushConverter.cs
- src/MahApps.Metro/Themes/ColorPicker/ColorCanvas.xaml
- src/MahApps.Metro/Themes/ColorPicker/ColorPalette.xaml
- src/MahApps.Metro/Themes/ColorPicker/ColorPicker.xaml
Implement a `ColorToSolidColorBrushConverter` because if we bind direct to a `Color` we might get binding issues.
none
This is an issue for some users but not for all. 
@nzain can you clone my branch, attach your tracing-tool and give me a feedback if it works now for you as well? Thank you. 
@seba30 if you enter a wrong color name I want to raise an error so the user gets notified that the value was wrong. So in this case the binding issue is wanted. 
Closes #4019
> Implement ColorToSolidColorBrushConverter

- src/MahApps.Metro/Controls/Helper/TextBoxHelper.cs
Use the SetCurrentValue method to prevent the binding from being released.
> Keep SelectedItemProperty Binding for ClearTextButton in ComboBox

- src/MahApps.Metro/Styles/Controls.ContextMenu.xaml
- src/MahApps.Metro/Styles/VS/ContextMenu.xaml
- src/MahApps.Metro/Themes/ToggleSwitch.xaml
Fix ToggleSwitch Right Alignment. After this fix it should be possible to have right aligned content. Also the inner MinWidth can now be set by the MinWidth of the ToggleSwitch itself.
Closes #4030
> (GH-4030) Fix ToggleSwitch Right Alignment

- src/MahApps.Metro/Controls/FlipView.cs
The SelectionChanged event is a bubbling event, so if the ListBox inside the FlipView fires the event, all other events in the same container will be fired. To fix this we check this inside the FlipView now and stop the bubbling.
Closes #4012
> Fix FlipView SelectionChanged event firing twice

- src/MahApps.Metro.Samples/MahApps.Metro.Demo/ExampleViews/ButtonsExample.xaml
- src/MahApps.Metro/Controls/Helper/CheckBoxHelper.cs
- src/MahApps.Metro/Converters/CornerRadiusFilterConverter.cs
- src/MahApps.Metro/Styles/Controls.CheckBox.xaml
- Add CornerRadiusFilterConverter. Filters a CornerRadius by the given Filter property. Result can be a new CornerRadius or a value of it's 4 corners.
- Add new CheckCornerRadius attached property to CheckBoxHelper
Closes #4050
> Fix CheckBox CornerRadius not working

- src/MahApps.Metro/Styles/Controls.TextBox.xaml
Fix FloatingWatermark position when using Left value for TextBoxHelper.ButtonsAlignment.
Closes #4015
> Fix FloatingWatermark position when using Left value for TextBoxHelper.ButtonsAlignment

- src/MahApps.Metro/Behaviors/WindowsSettingBehavior.cs
Fix possible NullReferenceException in WindowsSettingBehavior while unregistering session ending event.
Closes #4013
> Fix NullReferenceException in WindowsSettingBehavior

- src/MahApps.Metro/Themes/DateTimePicker.xaml
Setting IsClockVisible=false on the TimePicker should not hide the HoursMinutesSeconds picker. Only the clock should be hidden
Closes #4083
> Fix bug #4083

- src/MahApps.Metro/Controls/ColorPicker/ColorHelper.cs
- src/MahApps.Metro/Controls/ColorPicker/ColorPalette.cs
- src/MahApps.Metro/Controls/ColorPicker/ColorPickerBase.cs
- src/MahApps.Metro/Converters/ColorToNameConverter.cs
- src/MahApps.Metro/Themes/ColorPicker/ColorCanvas.xaml
- src/MahApps.Metro/Themes/ColorPicker/ColorPalette.xaml
- src/MahApps.Metro/Themes/ColorPicker/ColorPicker.xaml
Added more properties to `ColorPicker`
- `AreRgbChannelsVisible`
- `AreHsvChannelsVisible`
- `IsAlphaChannelVisible`
- `IsColorNameVisible`
- `IsEyeDropperVisible`
Additionally the `ColorHelper` is not static anymore. That way the user may roll his own `ColorHelper` and override `ColorFromString` and `GetColorName`. 
@seba30 please give me a 👍 or 👎 if this PR suits your needs
@punker76  I'll also update the docs if this PR is merged. 
Closes #4020
Closes #4023
> Feature ColorPicker should allow the hide some parts

- src/MahApps.Metro.Samples/MahApps.Metro.Demo/ExampleViews/TextExamples.xaml
- src/MahApps.Metro.Samples/MahApps.Metro.Demo/MainWindowViewModel.cs
- src/MahApps.Metro/Controls/NumericUpDown.cs
- src/Mahapps.Metro.Tests/Tests/NumericUpDownTests.cs
Implemented a new Property `DefaultValue` which will be used if the `Value` is `null`. This will also prevent errors for non-nullable values if set.
Implemented some basic tests which worked fine so far. 
Test-Overview: 
```c# 
MahApps.Metro.Tests.NumericUpDownTestsNumericUpDownTests.ShouldSetDefaultValue
// 1. Test: The default value must be set here. Let's check this.
// 2. Test: There is no default value, so we should be able to set it to null
// 3. Test: We set the Default Value greater than the Maximum. It should be corrected by the control
// 4. Test: We set the Default Value lower than the Minimum. It should be corrected by the control
```
See the demo for Testing
Closes #3668 
Closes #3936
> Implement `DefaultValue` to the `NumericUpDown`-Control

- src/Directory.Build.Props
- src/MahApps.Metro.Samples/MahApps.Metro.Demo/MainWindow.xaml.cs
- src/MahApps.Metro/Behaviors/TiltBehavior.cs
- src/MahApps.Metro/Controls/Dialogs/BaseMetroDialog.cs
- src/MahApps.Metro/Controls/Flyout.cs
- src/MahApps.Metro/Controls/MetroWindow.cs
- src/MahApps.Metro/MahApps.Metro.csproj
We have to use the correct theme when we receive a ThemeChanged event as it's a global event.
If the event targets the current window we use the theme from e.NewTheme, otherwise we have to detect the theme for `this` and use that as the new flyout theme.
#4096
> Fix for #4096

- src/MahApps.Metro/Controls/CustomValidationPopup.cs
- src/MahApps.Metro/Controls/TreeHelper.cs
Fix getting the wrong Ancestor (ScrollViewer) at CustomValidationPopup
Closes #4117
> Fix getting the wrong Ancestor (ScrollViewer) at CustomValidationPopup

- src/MahApps.Metro/Controls/ColorPicker/ColorPicker.cs
This PR adds a property `CloseOnSelectedColorChanged` to the `ColorPicker` control which allows the user to specify if the DropDown should be closed after a color is selected from a palette.
Further info can be found in #4128.
None, because I don't know how to to that for this control.
The default value is `false` to not break existing behavior.
Closes #4128
> Add option to close ColorPicker on selected color changed

- src/MahApps.Metro/Controls/ColorPicker/ColorPicker.cs
This PR fixes a wrong xml comment of the property `CloseOnSelectedColorChanged`.
Sorry for the inconvenience.
> ColorPicker: fix wrong xml comment

- src/MahApps.Metro.Samples/MahApps.Metro.Demo/ExampleViews/TextExamples.xaml
- src/MahApps.Metro/Controls/NumericUpDown.cs
- src/MahApps.Metro/Styles/Controls.Buttons.xaml
- src/MahApps.Metro/Styles/Controls.PasswordBox.xaml
- src/MahApps.Metro/Styles/Controls.xaml
- src/MahApps.Metro/Themes/Generic.xaml
- src/MahApps.Metro/Themes/HamburgerMenuTemplate.xaml
- src/MahApps.Metro/Themes/NumericUpDown.xaml
Add new properties to allow changing inner spin buttons
- SpinButtonStyle
- ButtonUpContent
- ButtonUpContentTemplate
- ButtonUpContentStringFormat
- ButtonDownContent
- ButtonDownContentTemplate
- ButtonDownContentStringFormat
Add new styles
- MahApps.Styles.NumericUpDown
- MahApps.Styles.Button.NumericUpDown.Spin
- MahApps.Styles.NumericUpDown.Fluent (experimental)
Add new const keys
- NumericUpDownBorderThickness
- NumericUpDownSelectedBorderThickness
- NumericUpDownSpinButtonRightBorderThickness
- NumericUpDownSpinButtonLeftBorderThickness
> Make NumericUpDown more stylable

- src/MahApps.Metro.Samples/MahApps.Metro.Demo/ExampleViews/ColorPickerExample.xaml
- src/MahApps.Metro/Controls/ColorPicker/ColorHelper.cs
- src/MahApps.Metro/Themes/ColorPicker/ColorPicker.xaml
- Fix missing TemplateBinding for `ColorPalettes`
- Make the `ColorNamesDictionary` an instance member 
- Create parameterless constructor with uses the default translations
- Create constructor which uses a given culture. If the the culture is `null` we use the actual color names from .NET
- Create a constructor which uses a given culture and a given resource to look up the names
- 
None
⚠ BREAKING CHANGE ⚠
This PR might be a breaking change if anyone used the static `ColorNamesHelper`.
Closes #4131
> Fix wrong translation for color names

- src/global.json
This PR fixes an incorrect sdk version inside of `global.json`.
The version needs to be specified in a correct format to take effect. See second line of output from `dotnet --info`.
According to [this issue](https://github.com/dotnet/sdk/issues/13799) and the [corresponding documentation](https://docs.microsoft.com/en-us/dotnet/core/tools/global-json?tabs=netcore3x#matching-rules) you need to specify an existing version.
Maybe you want to specify `latestMinor` instead of `latestFeature`. ([see documentation](https://docs.microsoft.com/en-us/dotnet/core/tools/global-json?tabs=netcore3x#rollforward))
> Fix incorrect sdk version in `global.json`

- src/MahApps.Metro/MahApps.Metro.csproj
We have to constrain the version range for our dependency on ControlzEx. Otherwise people might end in a situation where nuget automatically chooses an incompatible higher version.
> Adding proper version range for ControlzEx dependency

- src/MahApps.Metro.Samples/MahApps.Metro.Demo/ExampleViews/SelectionExamples.xaml
- src/MahApps.Metro.Samples/MahApps.Metro.Demo/ExampleViews/TextExamples.xaml
- src/MahApps.Metro/Converters/IsNotNullConverter.cs
Add a IsNotNullConverter value converter.
Sample:
```xaml
<ComboBox Width="200"
Margin="{StaticResource ControlMargin}"
mah:TextBoxHelper.ClearTextButton="{Binding Path=SelectedItem, RelativeSource={RelativeSource Mode=Self}, Converter={x:Static mah:IsNotNullConverter.Instance}}"
mah:TextBoxHelper.Watermark="Please select an item..."
SelectedIndex="0">
<ComboBoxItem Content="Item 1" />
<ComboBoxItem Content="Item 2" />
<ComboBoxItem Content="Very long Item 3 for MahApps.Metro" />
<ComboBoxItem Content="Item 4" />
</ComboBox>
```
> Add IsNotNullConverter value converter

- src/Directory.Build.Props
- src/MahApps.Metro.Samples/MahApps.Metro.Caliburn.Demo/App.net452.config
- src/MahApps.Metro.Samples/MahApps.Metro.Caliburn.Demo/App.net46.config
- src/MahApps.Metro.Samples/MahApps.Metro.Caliburn.Demo/App.net47.config
- src/MahApps.Metro.Samples/MahApps.Metro.Caliburn.Demo/App.netcoreapp3.0.config
- src/MahApps.Metro.Samples/MahApps.Metro.Caliburn.Demo/App.netcoreapp3.1.config
- src/MahApps.Metro.Samples/MahApps.Metro.Caliburn.Demo/AppBootstrapper.cs
- src/MahApps.Metro.Samples/MahApps.Metro.Caliburn.Demo/Controls/StartupTasks.cs
- src/MahApps.Metro.Samples/MahApps.Metro.Caliburn.Demo/Controls/ViewLocator.cs
- src/MahApps.Metro.Samples/MahApps.Metro.Caliburn.Demo/MahApps.Metro.Caliburn.Demo.csproj
- src/MahApps.Metro.Samples/MahApps.Metro.Caliburn.Demo/Services/IServiceLocator.cs
- src/MahApps.Metro.Samples/MahApps.Metro.Caliburn.Demo/Services/MefServiceLocator.cs
- src/MahApps.Metro.Samples/MahApps.Metro.Caliburn.Demo/ViewModels/ShellViewModel.cs
- src/MahApps.Metro.Samples/MahApps.Metro.Caliburn.Demo/Views/ShellView.xaml
- src/MahApps.Metro.Samples/MahApps.Metro.Demo/App.net452.config
- src/MahApps.Metro.Samples/MahApps.Metro.Demo/App.net46.config
- src/MahApps.Metro.Samples/MahApps.Metro.Demo/App.net47.config
- src/MahApps.Metro.Samples/MahApps.Metro.Demo/App.netcoreapp3.1.config
- src/MahApps.Metro.Samples/MahApps.Metro.Demo/MahApps.Metro.Demo.csproj
- src/MahApps.Metro/Accessibility/AccessibilitySwitches.cs
- src/MahApps.Metro/Controls/Dialogs/BaseMetroDialog.cs
- src/MahApps.Metro/Controls/WindowSettings.cs
- src/Mahapps.Metro.Tests/Tests/NumericUpDownFixture.cs
Drop .NET Framework 4.5.2 and 4.6 which will reach End of Support on April 26, 2022.
Use latest Caliburn.Micro v4.0.173 in demo.
Closes #4214
> Drop .NET Framework 4.5.2 and 4.6

- src/MahApps.Metro.Samples/MahApps.Metro.Demo/ExampleViews/DataGridExamples.xaml
- src/MahApps.Metro/Styles/Controls.DataGrid.xaml
- src/MahApps.Metro/Styles/Themes/Theme.Template.xaml
Show the IsReadOnly property state of the column as background. Introduce new brush keys for the DataGridColumnHeader.
- `MahApps.Brushes.DataGridColumnHeader.Background`
- `MahApps.Brushes.DataGridColumnHeader.Background.MouseOver`
- `MahApps.Brushes.DataGridColumnHeader.Background.ReadOnly`
- `MahApps.Brushes.DataGridColumnHeader.Foreground`
- `MahApps.Brushes.DataGridColumnHeader.BorderBrush`
- `MahApps.Brushes.DataGridColumnHeader.SortArrowFill`
Closes #3243
> Show read only state in DataGridColumnHeader

- src/MahApps.Metro/Controls/CustomValidationPopup.cs
- src/MahApps.Metro/Controls/Helper/ValidationHelper.cs
- src/MahApps.Metro/Styles/Controls.ValidationError.xaml
Add new dependency property ShowValidationErrorOnKeyboardFocus to the validation popup. Also add an attached property to the ValidationHelper.
With this new properties it's possible to hide the popup globally or for a specific control. The validation can then be shown with the `ShowValidationErrorOnMouseOver` property.
Closes #4086
> Add ShowValidationErrorOnKeyboardFocus property to validation popup

- src/MahApps.Metro/Styles/Controls.MenuItem.xaml
MenuItem causing 'System.Windows.Data.Inforamtion 10:...' messages being generated. This causes performance problems when the controls are unloaded from the view or when DataContext is set to null.
XAML binding performance bug - missing FallbackValue values causes WPF information messages to be generated.
No unit tests - changes to XAML only
> Fix missing FallbackValue values in binding for MahApps styles

- src/MahApps.Metro.Samples/MahApps.Metro.Demo/ExampleViews/DataGridExamples.xaml
- src/MahApps.Metro.Samples/MahApps.Metro.Demo/MainWindowViewModel.cs
- src/MahApps.Metro.Samples/MahApps.Metro.Demo/Models/BindingProxy.cs
- src/MahApps.Metro/Controls/Helper/VisibilityHelper.cs
The VisibilityHelper cannot change the visibility of a DataGridColumn, this type does not inherits from FrameworkElement.
I've update the VisibilityHelper to allow this case.
I also updated the sample project to show this feature in use, in the DataGrid view.
> Handle DataGridColumn visibility in VisibilityHelper

- src/MahApps.Metro/Styles/Controls.Calendar.xaml
This is to address performance issues when templates & styles are loaded & unloaded from the visual tree - these warnings slow the UI from rendering and can cause animation to stutter - specifically the Calendar control in this case.
This only occur where a Template or Style (MahApps) uses a "{Binding}" without specifying a 'FallbackValue' value.
examples of the messages:
System.Windows.Data Information: 10 :
Cannot retrieve value using the binding and no valid fallback value exists; using default instead. BindingExpression:(no path); DataItem=null; target element is 'TextBlock' (Name=''); target property is 'Text' (type 'String')
System.Windows.Data Information: 10 :
Cannot retrieve value using the binding and no valid fallback value exists; using default instead. …
> Added FallbackValue in XAML for Calendar control styles:

- src/MahApps.Metro.Samples/MahApps.Metro.Caliburn.Demo/ViewModels/Flyouts/FlyoutLeftViewModel.cs
- src/MahApps.Metro.Samples/MahApps.Metro.Caliburn.Demo/ViewModels/Flyouts/FlyoutTopViewModel.cs
- src/MahApps.Metro.Samples/MahApps.Metro.Demo/ExampleWindows/FlyoutDemo.xaml
- src/MahApps.Metro.Samples/MahApps.Metro.Demo/ExampleWindows/FlyoutDemo.xaml.cs
- src/MahApps.Metro/Controls/Flyout.cs
- src/MahApps.Metro/Controls/FlyoutTheme.cs
BREAKING CHANGE: Remove Flyout accent theme
An accent theme background is really complicated to manage. If it's really necessary to use such background then the user can create a special resource theme with the ThemeManager and use it for the Flyout.
Closes #4253
> Remove flyout accent theme

- src/MahApps.Metro/Styles/Controls.TabControl.xaml
- src/MahApps.Metro/Styles/VS/TabControl.xaml
- src/MahApps.Metro/Themes/MetroTabItem.xaml
Allow set the CornerRadius for TabItem:
```xaml
<TabItem BorderThickness="1 1 1 0" mah:ControlsHelper.CornerRadius="4 4 0 0" Header="Test">
</TabItem>
```
Closes #4248
> Allow set the CornerRadius for TabItem

- src/MahApps.Metro/Styles/Controls.TabControl.xaml
- src/MahApps.Metro/Styles/VS/TabControl.xaml
- src/MahApps.Metro/Themes/MetroTabControl.xaml
Allow set the CornerRadius for the inner Border of the TabControl.
```xaml
<TabControl BorderThickness="1" mah:ControlsHelper.CornerRadius="4">
</TabControl>
```
Closes #4248
> Allow set the CornerRadius for TabControl

- src/MahApps.Metro/Controls/GridViewHeaderRowPresenterEx.cs
- src/MahApps.Metro/Controls/Helper/ItemHelper.cs
- src/MahApps.Metro/Styles/Controls.ListView.xaml
The column reorder indicator of the `GridViewHeaderRowPresenter` is hard coded and can not easily change by the user. Especially the brush of the inner border can not be changed.
So we added a new attached property to the `ItemHelper` called `GridViewHeaderIndicatorBrush`.
The default value for `ItemHelper.GridViewHeaderIndicatorBrush` is `MahApps.Brushes.AccentBase`.
> Allow changing the ListView grid header reorder indicator brush

- src/MahApps.Metro/Controls/Dialogs/MessageDialog.cs
Fix DefaultButtonFocus error.
The DefaultButtonFocus is always Negative, can't change to the other, except MessageDialogStyle is Affirmative.
> Fix changing DefaultButtonFocus for MessageDialog

- src/MahApps.Metro.Samples/MahApps.Metro.Demo/ExampleViews/DateExamples.xaml
- src/MahApps.Metro.Samples/MahApps.Metro.Demo/ExampleViews/MultiSelectionComboBoxExample.xaml
- src/MahApps.Metro.Samples/MahApps.Metro.Demo/ExampleViews/SelectionExamples.xaml
- src/MahApps.Metro.Samples/MahApps.Metro.Demo/ExampleViews/TextExamples.xaml
- src/MahApps.Metro.Samples/MahApps.Metro.Demo/ExampleViews/TextExamples.xaml.cs
- src/MahApps.Metro.Samples/MahApps.Metro.Demo/MainWindowViewModel.cs
- src/MahApps.Metro.sln.DotSettings
- src/MahApps.Metro/Controls/Helper/MahAppsCommands.cs
- src/MahApps.Metro/Controls/Helper/TextBoxHelper.cs
- src/MahApps.Metro/Controls/HotKeyBox.cs
- src/MahApps.Metro/Controls/TimePicker/TimePickerBase.cs
- src/MahApps.Metro/Styles/Controls.CheckBox.xaml
- src/MahApps.Metro/Styles/Controls.ComboBox.xaml
- src/MahApps.Metro/Styles/Controls.DatePicker.xaml
- src/MahApps.Metro/Styles/Controls.PasswordBox.xaml
- src/MahApps.Metro/Styles/Controls.RichTextBox.xaml
- src/MahApps.Metro/Styles/Controls.TextBox.xaml
- src/MahApps.Metro/Styles/VS/MetroWindow.xaml
- src/MahApps.Metro/Themes/ColorPicker/ColorPicker.xaml
- src/MahApps.Metro/Themes/DateTimePicker.xaml
- src/MahApps.Metro/Themes/HotKeyBox.xaml
- src/MahApps.Metro/Themes/MultiSelectionComboBox.xaml
- src/MahApps.Metro/Themes/NumericUpDown.xaml
- src/Mahapps.Metro.Tests/Tests/HeaderedControlHelperTests.cs
- src/Mahapps.Metro.Tests/Tests/TextBoxHelperTests.Fixture.cs
- src/Mahapps.Metro.Tests/Tests/TextBoxHelperTests.cs
- src/Mahapps.Metro.Tests/Views/TextBoxHelperTestWindow.xaml
Add clear/custom button command to all input controls and use the ClearControlCommand.
- RichTextBox
- TextBox
- ComboBox
- DatePicker
- DateTimePicker
- PasswordBox
- MultiSelectionComboBox
- ColorPicker
- NumericUpDown
- HotKeyBox
TextBoxHelperTests
- Add new MahAppsCommands.SearchCommand
- Create new MahApps.Styles.CheckBox.MultiSelectionComboBoxItem for MahApps.Styles.MultiSelectionComboBoxItem.CheckBox
- Add new TextBoxHelper.ButtonCommandTarget. With this property it's easier to set the target for the clear command.
- Add a new HotKeyChanged event to the HotKeyBox
**BREAKING CHANGE**
- TextBoxHelper.IsClearTextButtonBehaviorEnabled and TextBoxHelper.TextButton attached properties removed
- MahApps.Styles.RichTextBox.Button style removed
- MahApps.Styles.TextBox.Button style removed …
> Add clear/custom button command to all input controls

- src/MahApps.Metro.Samples/MahApps.Metro.Demo/ExampleViews/TextExamples.xaml
- src/MahApps.Metro.Samples/MahApps.Metro.Demo/ExampleWindows/CleanWindowDemo.xaml
- src/MahApps.Metro/Controls/Helper/TextBoxHelper.cs
- src/MahApps.Metro/Styles/Controls.PasswordBox.xaml
- src/MahApps.Metro/Styles/Controls.Shadows.xaml
- src/MahApps.Metro/Styles/Controls.Shared.xaml
- src/MahApps.Metro/Styles/Controls.TextBox.xaml
- src/MahApps.Metro/Themes/HotKeyBox.xaml
BREAKING CHANGE: remove the IsWaitingForData attached property
Remove the IsWaitingForData attached property and all associated styles and effects.
The "mandatory" visual can be used with the WPF validation rules, so this extra attached property can be removed.
> Remove the IsWaitingForData attached property

- src/MahApps.Metro.Samples/MahApps.Metro.Demo/MainWindow.xaml
- src/MahApps.Metro.Samples/MahApps.Metro.Demo/MainWindow.xaml.cs
- src/MahApps.Metro/Controls/Dialogs/BaseMetroDialog.cs
- src/MahApps.Metro/Controls/Dialogs/DialogManager.cs
This PR removes the methods to show an existing dialog externally:
- ShowDialogExternally<TDialog>
- ShowModalDialogExternally<TDialog>
I will not continue to maintain these 2 methods.
> Remove methods to show an existing dialog externally

- src/MahApps.Metro/Controls/WinApiHelper.cs
I noticed that restoring the window size wasn't very consistent - and on a brand new test project it would get smaller each time it was opened and closed. Reviewing the code it looks like WindowPlacementSetting uses the DPI to adjust the scale factor when saving the settings - but that isn't used when restoring the window.  This change takes the DPI scale factor into account when restoring. 
This fixes the issue for me. Don't have enough experience with the codebase to add a unit test.
> when restoring window size use the DPI scale factor

- src/MahApps.Metro.Samples/MahApps.Metro.Demo/ExampleViews/TextExamples.xaml
- src/MahApps.Metro/Controls/CustomValidationPopup.cs
- src/MahApps.Metro/Controls/Helper/ValidationHelper.cs
- src/MahApps.Metro/Styles/Controls.ValidationError.xaml
Original change from #4451 added by @nekizalb 
Add an option to always show ErrorTemplate text, regardless of focus or mouse over.
This change introduces a new attached property in ValidationHelper to enable the behavior and a new style trigger that will enable when the template has errors and the new attached property, ValidationHelper.AlwaysShowValidationError, is set to true for the element.
Closes #4451
> Add an option to always show ErrorTemplate text

- src/MahApps.Metro.Samples/MahApps.Metro.Demo/ExampleViews/SplitViewExamples.xaml
- src/MahApps.Metro/Controls/SplitView/SplitView.cs
Change SplitView from Control to ContentControl to fix these binding issues. Introduce also PaneTemplate dependency property and change the Pane property type to object.
Closes #4468
> Change SplitView to ContentControl

- src/MahApps.Metro.Samples/MahApps.Metro.Demo/ExampleViews/TextExamples.xaml
- src/MahApps.Metro/Automation/Peers/NumericUpdDownAutomationPeer.cs
- src/MahApps.Metro/Controls/NumericUpDown.cs
I have added automationpeer to numericupdown ui element.
The automation peer will let the numericupdown button to get automationids and name given from user which will ease the automation testing
Closes #2166
> #2166 automatiopeer for numericupdown
