MahApps.Metro/Controls/Dialogs/BaseMetroDialog.cs
MahApps.Metro/Controls/Dialogs/MessageDialog.cs
MahApps.Metro/Controls/FlipView.cs
MahApps.Metro/Controls/Flyout.cs
MahApps.Metro/Controls/MetroNavigationWindow.cs
MahApps.Metro/Controls/MetroWindow.cs
MahApps.Metro/Themes/Dialogs/MessageDialog.xaml
MahApps.Metro/Themes/FlipView.xaml
MahApps.Metro/Themes/Flyout.xaml
MahApps.Metro/Themes/MetroNavigationWindow.xaml
docs/release-notes/1.1.0.md
samples/MetroDemo/ExampleViews/OtherExamples.xaml
samples/MetroDemo/ExampleWindows/CleanWindowDemo.xaml.cs
samples/MetroDemo/ExampleWindows/FlyoutDemo.xaml
samples/MetroDemo/MainWindow.xaml
samples/MetroDemo/MainWindow.xaml.cs

^^ @Amrykid the changes should be merged with some enhancements... ;-P

Changes from The Amrykid Service Pack

---

MahApps.Metro/Styles/Accents/Amber.xaml
MahApps.Metro/Styles/Accents/Cyan.xaml
MahApps.Metro/Styles/Accents/Lime.xaml
MahApps.Metro/Styles/Accents/Olive.xaml
MahApps.Metro/Styles/Accents/Pink.xaml
MahApps.Metro/Styles/Accents/Steel.xaml
MahApps.Metro/Styles/Accents/Teal.xaml

Here, look at this:
For the most styles, it looks better with a white title (in my opinion)

Fix ideal foreground for some color styles

---

MahApps.Metro/Behaviours/BorderlessWindowBehavior.cs

This should fix the maximize bug.

Fix Maximize bug

---

MahApps.Metro/Microsoft.Windows.Shell/WindowChromeWorker.cs

Also redraw with WVR.VALIDRECTS for smoother animation.

New hack for ignoretaskbar window moving

---

MahApps.Metro/Themes/Dialogs/MessageDialog.xaml

Added back Text wrapping for MessageDialog Message (#1766)

Text wrapping for MessageDialog Message

---

MahApps.Metro/Controls/WindowButtonCommands.cs
MahApps.Metro/Controls/WindowCommands.cs
MahApps.Metro/Themes/MetroWindow.xaml
docs/release-notes/1.1.0.md

for pre-created windows (e.g. flyout demo)
Closes #1503

fix foreground color of WindowComands and WindowButtonCommands

---

MahApps.Metro/Controls/WindowCommands.cs
MahApps.Metro/Themes/MetroWindow.xaml
docs/release-notes/1.1.0.md
samples/MetroDemo/ExampleWindows/FlyoutDemo.xaml

so we can hide the WindowCommands seperators
Closes #1708

new ShowSeparators property for WindowCommands

---

MahApps.Metro/Controls/Helper/TextBoxHelper.cs
MahApps.Metro/Styles/Controls.PasswordBox.xaml
docs/release-notes/1.1.0.md

Passwordbox, fix visibility of cleartext button

---

MahApps.Metro/Styles/Controls.Scrollbars.xaml
MahApps.Metro/Styles/Controls.TextBox.xaml
docs/release-notes/1.1.0.md

Removed margin from ScrollViewer in TextBox style

---

MahApps.Metro/Controls/MetroWindow.cs
samples/MetroDemo/MainWindow.xaml

Closes  #1688 Hide icon after window is loaded

Add callback for ShowIconOnTitleBar

---

MahApps.Metro/Controls/WindowSettings.cs

use GetWindowRect to save possible snapped window (thx @thoemmi for the tipp)
Closes #1811

Fix Window Placement and Border Snaps #1811

---

MahApps.Metro/Controls/Helper/DataGridCellHelper.cs

Fix DataGrid Selection Color Disappearing #1728

---

MahApps.Metro/Controls/GlowWindow.xaml.cs

the glow window handles the mouse click, but it should not...
http://stackoverflow.com/a/14790533/920384 for reference

the Glow window should not be clickable

---

MahApps.Metro/Behaviours/BorderlessWindowBehavior.cs

Fix Win32Exception "Invalid window handle" #1880

---

MahApps.Metro/Behaviours/GlowWindowBehavior.cs
MahApps.Metro/Controls/GlowWindow.xaml.cs
MahApps.Metro/Themes/Glow.xaml

the title says all...
(warn: don't look too much on the gifs... :-P )
before
after

try to fix flickering glow borders (on resizing)

---

MahApps.Metro/Controls/NumericUpDown.cs

NumericUpDown will support per instance culture binding which can be used in string formatting/presentation operations when used in conjuction with StringFormat property.

NumericUpDown per instance culture

---

MahApps.Metro/Controls/CustomValidationPopup.cs
MahApps.Metro/Styles/ValidationErrorTemplate.xaml

Closes #1922 IDataErrorInfo validation text flickers on strange location with Flyout

fix validation popup location flicker

---

MahApps.Metro/Controls/DropDownButton.cs
MahApps.Metro/Styles/Controls.Buttons.xaml
MahApps.Metro/Themes/DropDownButton.xaml
samples/MetroDemo/ExampleViews/ButtonsExample.xaml

- style and template improvements
- new `ButtonStyle` dependency property and new style key `ButtonDropDownStyle`
- new `ArrowBrush` dependency property
- better focus handling
- new `MenuStyle` dependency property
- fix alignement and margins
- new `IconTemplate` dependency property
- new `ArrowVisibility` dependency property
Closes #1574 Update DropDownButton.xaml with MetroCircle-style

DropDownButton improvements

---

MahApps.Metro/Controls/Dialogs/MessageDialog.cs
docs/release-notes/1.2.0.md

Close message dialog when pressing **Esc**. Fixes #1976

cancel message dialog on Esc

---

MahApps.Metro/Controls/DropDownButton.cs
MahApps.Metro/Controls/SplitButton.cs
MahApps.Metro/Styles/Controls.Buttons.xaml
MahApps.Metro/Themes/DropDownButton.xaml
MahApps.Metro/Themes/SplitButton.xaml
samples/MetroDemo/ExampleViews/ButtonsExample.xaml

- style and template improvements
- new `ButtonStyle`, `ButtonArrowStyle` dependency properties and new style keys `ButtonSplitStyle`, `ButtonSplitArrowStyle`
- new `ArrowBrush` dependency property
- better focus handling
- new `ListBoxStyle` dependency property
- fix alignement and margins
- new `IconTemplate` dependency property

SplitButton improvements

---

MahApps.Metro/Controls/NumericUpDown.cs
samples/MetroDemo/ExampleViews/TextExamples.xaml

this pr fixes runtime changes to this properties, because the value was not updated correctly.

NumericUpDown fix for runtime changes to StringFormat and Culture property

---

MahApps.Metro/Controls/Dialogs/ProgressDialogController.cs

Closes #1702 ProgressDialog should have diffrent min/max values. [Request]

Add Minimum, Maximum properties to ProgressDialogController

---

MahApps.Metro/Styles/Controls.TreeView.xaml
samples/MetroDemo/ExampleViews/SelectionExamples.xaml
samples/MetroDemo/Models/Album.cs
samples/MetroDemo/Models/Artist.cs

Closes #1896 TreeView and large data

TreeViewStyle enhancements

---

MahApps.Metro/Controls/CustomValidationPopup.cs
MahApps.Metro/Styles/ValidationErrorTemplate.xaml
samples/MetroDemo/App.xaml

Closes #1469 CustomValidationPopup OnPreviewMouseLeftButtonDown Event
- new `CloseOnMouseLeftButtonDown` dependency property
- new style `MetroValidationPopup`

CustomValidationPopup changes

---

MahApps.Metro/Controls/Glow.cs
MahApps.Metro/Controls/GlowWindow.xaml
MahApps.Metro/Controls/GlowWindow.xaml.cs
MahApps.Metro/Controls/MetroWindow.cs
MahApps.Metro/Styles/Clean/CleanWindow.xaml
MahApps.Metro/Themes/Glow.xaml
MahApps.Metro/Themes/MetroWindow.xaml
samples/MetroDemo/MainWindow.xaml
samples/MetroDemo/MainWindow.xaml.cs

So, this is my attempt to fix the glow corners.
Current situation (before this PR):
And now (with this PR):
Closes #2118 Glow border is missing the corners
/cc @thoemmi @flagbug

[WIP][RFC] Fix for Glow corners

---

MahApps.Metro/Controls/MetroProgressBar.cs
MahApps.Metro/Themes/MetroProgressBar.xaml
docs/release-notes/1.2.0.md
readme.md

switching an invisible indeterminate ProgressBar to visible doesn't shows the animation, also the width wasn't correct, so this should it fix now
Closes #2180

fix ProgressBar IsIndeterminate visibility

---

MahApps.Metro/Controls/WindowCommands.cs
docs/release-notes/1.2.0.md
readme.md

Closes #2188 WindowCommands.ShowSeparators=False is ignored

fix wrong behavior with IsSeparatorVisible for WindowCommands

---

MahApps.Metro/Controls/Dialogs/MessageDialog.cs
MahApps.Metro/Themes/Dialogs/MessageDialog.xaml

Add command to copy the message in a MessageDialog

Add copy message in MessageDialog

---

MahApps.Metro/Styles/Controls.ComboBox.xaml

Cant override the button content for combo box; this fixes that.

Make combo style respect textbox helper button content

---

MahApps.Metro/Controls/Flyout.cs
MahApps.Metro/Themes/Flyout.xaml
samples/MetroDemo/ExampleWindows/FlyoutDemo.xaml

This enables a keyboard shortcut to press the escape button to close flyouts

Adding IsCancel="True" to Flyout button

---

MahApps.Metro/AppTheme.cs
MahApps.Metro/Behaviours/PasswordBoxBindingBehavior.cs
MahApps.Metro/Behaviours/ReloadBehavior.cs
MahApps.Metro/Behaviours/StylizedBehaviors.cs
MahApps.Metro/Controls/Helper/ButtonHelper.cs
MahApps.Metro/Controls/Helper/ComboBoxHelper.cs
MahApps.Metro/Controls/Helper/ControlsHelper.cs
MahApps.Metro/Controls/Helper/DataGridCellHelper.cs
MahApps.Metro/Controls/Helper/DataGridRowHelper.cs
MahApps.Metro/Controls/Helper/ExpanderHelper.cs
MahApps.Metro/Controls/Helper/GroupBoxHelper.cs
MahApps.Metro/Controls/Helper/PasswordBoxHelper.cs
MahApps.Metro/Controls/Helper/ScrollBarHelper.cs
MahApps.Metro/Controls/Helper/SliderHelper.cs
MahApps.Metro/Controls/Helper/TabControlHelper.cs
MahApps.Metro/Controls/Helper/TextBoxHelper.cs
MahApps.Metro/Controls/Helper/ToggleButtonHelper.cs
MahApps.Metro/Controls/Helper/VisibilityHelper.cs
MahApps.Metro/Microsoft.Windows.Shell/WindowChrome.cs

Added **[CategoryAttribute("MahApps.Metro")]** for each AttachedProperty.

[WIP] The Blend Service Pack

---

MahApps.Metro/Styles/Controls.xaml
docs/release-notes/1.2.1.md

set tab stop and focusable to false (FloatingMessageContainerStyle) should fix the issue
Closes #2296

fix hidden TextBox focus

---

MahApps.Metro/Styles/Controls.Tooltip.xaml

Reverts MahApps/MahApps.Metro#2359

Revert "Added ContentStringFormat TemplateBinding to ToolTip"

---

MahApps.Metro/Styles/Controls.Tooltip.xaml
MahApps.Metro/Styles/Fonts.xaml

inspired by @nrpog
Added ContentStringFormat TemplateBinding to ToolTip #2359

Tooltip improvement

---

MahApps.Metro/Styles/Controls.Scrollbars.xaml
MahApps.Metro/Styles/Controls.Toolbar.xaml
MahApps.Metro/Styles/Sizes.xaml
samples/MetroDemo/ExampleViews/DataGridExamples.xaml

- use MetroComboBox style for ToolBar.ComboBoxStyleKey
- fix mouse click on ScrollBar
- try reduce boiler plate code
Closes #1439 ComboBox in Toolbar closes if Scrollbar track/button is clicked

ComboBox toolbar scrollbar fix

---

MahApps.Metro/Controls/NumericUpDown.cs

Reverts MahApps/MahApps.Metro#2404

Revert "Fixes the HasDecimals property, broken before on commit bd6aa38e."

---

MahApps.Metro/Themes/Flyout.xaml
MahApps.Metro/Themes/NumericUpDown.xaml

Reverts MahApps/MahApps.Metro#2381
affected by https://github.com/MahApps/MahApps.Metro/pull/2386#issuecomment-191647522

Revert "AutomationId based on name fix"

---

MahApps.Metro/Controls/Flyout.cs

Fixed a typo i found while scrolling through Flyout.cs

fixed typo in Flyout.cs

---

MahApps.Metro/Behaviours/DatePickerTextBoxBehavior.cs
MahApps.Metro/Controls/Helper/TextBoxHelper.cs
MahApps.Metro/Controls/NumericUpDown.cs
MahApps.Metro/Controls/TimePicker/DateTimePicker.cs
MahApps.Metro/Controls/TimePicker/TimePickerBase.cs
MahApps.Metro/Controls/TimePicker/TimePickerBaseSelectionChangedEventArgs.cs
MahApps.Metro/Converters/ClockDegreeConverter.cs
MahApps.Metro/MahApps.Metro.NET45.csproj
MahApps.Metro/MahApps.Metro.csproj
MahApps.Metro/Styles/Controls.DatePicker.xaml
MahApps.Metro/Themes/DateTimePicker.xaml
samples/MetroDemo/ExampleViews/DateExamples.xaml

-
Resolves  #2524 
Resolves #2486

Extending FloatingWatermarks

---

MahApps.Metro/Controls/TimePicker/TimePickerBase.cs

Date time picker improvements

---

docs/release-notes/1.5.0.md
src/MahApps.Metro.Samples/MahApps.Metro.Demo/MahApps.Metro.Demo.Shared/ExampleViews/HamburgerMenuSample.xaml
src/MahApps.Metro.Samples/MahApps.Metro.Demo/MahApps.Metro.Demo.Shared/ExampleViews/HamburgerMenuSample.xaml.cs
src/MahApps.Metro/MahApps.Metro.Shared/Controls/HamburgerMenu/HamburgerMenu.Events.cs
src/MahApps.Metro/MahApps.Metro.Shared/Controls/HamburgerMenu/HamburgerMenu.HamburgerButton.cs
src/MahApps.Metro/MahApps.Metro.Shared/Controls/HamburgerMenu/HamburgerMenu.Options.cs
src/MahApps.Metro/MahApps.Metro.Shared/Controls/HamburgerMenu/HamburgerMenu.Properties.cs
src/MahApps.Metro/MahApps.Metro.Shared/Controls/HamburgerMenu/HamburgerMenu.cs
src/MahApps.Metro/MahApps.Metro.Shared/Controls/HamburgerMenu/MenuItems/HamburgerMenuGlyphItem.cs
src/MahApps.Metro/MahApps.Metro.Shared/Controls/HamburgerMenu/MenuItems/HamburgerMenuIconItem.cs
src/MahApps.Metro/MahApps.Metro.Shared/Controls/HamburgerMenu/MenuItems/HamburgerMenuImageItem.cs
src/MahApps.Metro/MahApps.Metro.Shared/Controls/HamburgerMenu/MenuItems/HamburgerMenuItem.cs
src/MahApps.Metro/MahApps.Metro.Shared/Controls/HamburgerMenu/MenuItems/HamburgerMenuItemCollection.cs
src/MahApps.Metro/MahApps.Metro.Shared/Controls/SplitView/SplitView.cs
src/MahApps.Metro/MahApps.Metro.Shared/MahApps.Metro.Shared.projitems
src/MahApps.Metro/MahApps.Metro/Styles/Colors.xaml
src/MahApps.Metro/MahApps.Metro/Themes/HamburgerMenu.xaml
src/MahApps.Metro/MahApps.Metro/Themes/SplitView.xaml

Closes #2848 HamburgerMenu Command MVVM

HamburgerMenu changes/improvements

---

docs/release-notes/1.5.0.md
src/MahApps.Metro.Samples/MahApps.Metro.Caliburn.Demo/MahApps.Metro.Caliburn.Demo.NET40/MahApps.Metro.Caliburn.Demo.NET40.csproj
src/MahApps.Metro.Samples/MahApps.Metro.Caliburn.Demo/MahApps.Metro.Caliburn.Demo.NET45/MahApps.Metro.Caliburn.Demo.NET45.csproj
src/MahApps.Metro.Samples/MahApps.Metro.Demo/MahApps.Metro.Demo.NET40/MahApps.Metro.Demo.NET40.csproj
src/MahApps.Metro.Samples/MahApps.Metro.Demo/MahApps.Metro.Demo.Shared/ExampleViews/ButtonsExample.xaml
src/MahApps.Metro.Samples/MahApps.Metro.Demo/MahApps.Metro.Demo.Shared/ExampleViews/ButtonsExample.xaml.cs
src/MahApps.Metro/MahApps.Metro.Shared/Controls/Badged.cs
src/MahApps.Metro/MahApps.Metro.Shared/MahApps.Metro.Shared.projitems
src/MahApps.Metro/MahApps.Metro/MahApps.Metro.NET40.csproj
src/MahApps.Metro/MahApps.Metro/MahApps.Metro.NET45.csproj
src/MahApps.Metro/MahApps.Metro/Themes/Badged.xaml
src/MahApps.Metro/MahApps.Metro/Themes/Generic.xaml
src/MahApps.Metro/paket.references
src/Mahapps.Metro.Tests/Mahapps.Metro.Tests.NET40/Mahapps.Metro.Tests.NET40.csproj
src/paket.dependencies
src/paket.lock

Add new `Badged` control. Thx to @ButchersBoy

Add new Badged control

---

readme.md

Added links to TeamCity projects because the were missing.

Adding links to TeamCity projects

---

docs/release-notes/1.5.0.md
src/MahApps.Metro.Samples/MahApps.Metro.Demo/MahApps.Metro.Demo.Shared/ExampleViews/HamburgerMenuSample.xaml
src/MahApps.Metro.Samples/MahApps.Metro.Demo/MahApps.Metro.Demo.Shared/ExampleViews/HamburgerMenuSample.xaml.cs
src/MahApps.Metro.Samples/MahApps.Metro.Demo/MahApps.Metro.Demo.Shared/MainWindowViewModel.cs
src/MahApps.Metro/MahApps.Metro.Shared/Controls/CommandHelpers.cs
src/MahApps.Metro/MahApps.Metro.Shared/Controls/HamburgerMenu/MenuItems/HamburgerMenuItem.cs
src/MahApps.Metro/MahApps.Metro.Shared/MahApps.Metro.Shared.projitems
src/MahApps.Metro/MahApps.Metro/Themes/Generic.xaml
src/MahApps.Metro/MahApps.Metro/Themes/HamburgerMenu.xaml

- Implement the interface ICommandSource
- Handle Command binding change to hook or unhook command executable
- Listen to the new command stuff to enable or disable the HamburgerMenuItem
- New `MahApps.Metro.Styles.HamburgerMenu` key for the HamburgerMenu style
Closes #2865 [Feature request]Enable/Disable of Hamburger Menu Item

HamburgerMenuItem Command improvements

---

src/MahApps.Metro/MahApps.Metro/Styles/Controls.RadioButton.xaml

ContentStringFormat was missing in RadioButton. Added this to the ContentPresenter

add contentstringformat to contentpresenter in controls.radiobutton.xaml

---

src/MahApps.Metro.Samples/MahApps.Metro.Demo/MahApps.Metro.Demo.Shared/ExampleViews/DateExamples.xaml
src/MahApps.Metro/MahApps.Metro.Shared/Controls/TimePicker/DateTimePicker.cs
src/MahApps.Metro/MahApps.Metro.Shared/Controls/TimePicker/TimePickerBase.cs
src/MahApps.Metro/MahApps.Metro.Shared/Controls/TimePicker/TimePickerFormat.cs
src/MahApps.Metro/MahApps.Metro.Shared/MahApps.Metro.Shared.projitems
src/Mahapps.Metro.Tests/Mahapps.Metro.Tests.Shared/Tests/DateTimePickerTests.cs
src/Mahapps.Metro.Tests/Mahapps.Metro.Tests.Shared/Views/DateAndTimePickerWindow.xaml

DisplayFormat in DateTimePicker and TimePicker

---

src/MahApps.Metro/MahApps.Metro/Styles/Controls.Buttons.xaml

_Describe the changes you have made to improve this project._
Fixed the fuzzy borders on some buttons by setting SnapsToDevicePixels=True and adding a TemplateBinding to the border.
#2937

Fixed fuzzy Borders on Buttons

---

docs/release-notes/1.6.0.md
src/MahApps.Metro.Samples/MahApps.Metro.Demo/MahApps.Metro.Demo.Shared/ExampleWindows/VSDemo.xaml
src/MahApps.Metro/MahApps.Metro/MahApps.Metro.NET40.csproj
src/MahApps.Metro/MahApps.Metro/MahApps.Metro.NET45.csproj
src/MahApps.Metro/MahApps.Metro/Styles/VS/GroupBox.xaml
src/MahApps.Metro/MahApps.Metro/Styles/VS/ScrollBar.xaml
src/MahApps.Metro/MahApps.Metro/Styles/VS/Styles.xaml
src/MahApps.Metro/MahApps.Metro/Styles/VS/TabControl.xaml
src/MahApps.Metro/MahApps.Metro/Themes/Badged.xaml
src/MahApps.Metro/MahApps.Metro/Themes/MetroTabItem.xaml
src/MahApps.Metro/MahApps.Metro/Themes/MetroWindow.xaml
tools/XamlStyler/Options/MahApps.Metro.Accents.XAMLStyler.json
tools/XamlStyler/Options/MahApps.Metro.XAMLStyler.json

This PR adds the missing GroupBox style for the VS theme.
Closes #3070

Add missing VS GroupBox style

---

docs/release-notes/1.6.0.md
src/MahApps.Metro/MahApps.Metro/Styles/Controls.AnimatedSingleRowTabControl.xaml
src/MahApps.Metro/MahApps.Metro/Styles/Controls.DatePicker.xaml
src/MahApps.Metro/MahApps.Metro/Themes/MetroAnimatedSingleRowTabControl.xaml
src/MahApps.Metro/MahApps.Metro/Themes/NumericUpDown.xaml

- Fix wrong background and missing binding to ControlsHelper.CornerRadius
- Fix padding usage
Closed #3086

Fix NumericUpDown Issue #3086

---

docs/release-notes/1.6.0.md
src/MahApps.Metro/MahApps.Metro/Themes/HamburgerMenu.xaml

- Fix setting IsTabStop for HamburgerMenu which doesn't have any effect for the inner ListBox items
Closes #3010

Fix #3010 IsTabStop for HamburgerMenu

---

src/MahApps.Metro/MahApps.Metro.Shared/Controls/Flyout.cs
src/MahApps.Metro/MahApps.Metro/Themes/Flyout.xaml

Changing the inner TextBlock to a ContentControl solves this issue.
Closes #3143

Fix for #3143 Flyout's header not binding to XmlProvider

---

src/MahApps.Metro/MahApps.Metro.Shared/Controls/Flyout.cs
src/MahApps.Metro/MahApps.Metro.Shared/Controls/FlyoutAutomationPeer.cs
src/MahApps.Metro/MahApps.Metro.Shared/MahApps.Metro.Shared.projitems

- Add FlyoutAutomationPeer for better CodedUI support
Closes #2527

Add FlyoutAutomationPeer for better CodedUI support

---

src/MahApps.Metro/MahApps.Metro.Shared/Controls/MetroThumbContentControl.cs

MetroThumbContentControl: Catch possible exception and trace it

---

src/MahApps.Metro.Samples/MahApps.Metro.Demo/MahApps.Metro.Demo.Shared/ExampleViews/HamburgerMenuDefault.xaml
src/MahApps.Metro/MahApps.Metro/Themes/HamburgerMenuTemplate.xaml

- Fix/improve PanePlacement handling for right aligned
- Update first showcase to change PanePlacement on the fly
Closes #3085

HamburgerMenu: correct PanePlacement handling

---

src/MahApps.Metro/MahApps.Metro.Shared/Controls/NumericUpDown.cs

- Fix not correct coerced value if min or max value was reached
- Fix manual change indication (e.g Tab is a non indicator)
Closes #3039

Fix for (GH-3039) NumericUpDown

---

src/MahApps.Metro/Styles/FlatSlider.xaml

(GH-3248) fix thumb in FlatSlider

---

src/MahApps.Metro.Samples/MahApps.Metro.Demo/ExampleViews/TextExamples.xaml
src/MahApps.Metro/Controls/NumericUpDown.cs
src/Mahapps.Metro.Tests/Tests/NumericUpDownTests.cs

Fix NumericUpDown Input Issues with StringFormat and parsing numbers.
**Unit test**
*NumericUpDownTests* 
Closes #3189 
Closes #3217 
Closes #3224

(GH-3189) Fix NumericUpDown Input Issues with StringFormat

---

src/MahApps.Metro/Controls/TransitioningContentControl.cs
src/MahApps.Metro/Themes/TransitioningContentControl.xaml
src/build.cake

Changing ContentTemplate via triggers has no effect, cause the template was only set in code behind.
Closes #3275

(GH-3275) Fix TransitioningContentControl vs. ContentControl

---

readme.md

Add appveyor nuget link to readme

Add appveyor nuget link to readme

---

src/Directory.build.props
src/MahApps.Metro/Controls/MetroWindow.cs
src/MahApps.Metro/MahApps.Metro.csproj
src/build.cake
src/paket.dependencies
src/paket.lock

Fix dependencies and use msbuild NuGet pack target.
Closes #3340

Fix dependencies for alpha v2.0

---

src/build.cake

This PR allows us to run the unit tests locally

Allow unit tests to be run locally

---

src/MahApps.Metro/MahApps.Metro.csproj

This PR should fix the requirement to build multiple times after a clean checkout.

Fixing multiple compile issues

---

src/MahApps.Metro/Controls/TimePicker/DateTimePicker.cs

Fix https://github.com/MahApps/MahApps.Metro/issues/3455

Fix for DateTimePicker System.IndexOutOfRangeException #3455

---

src/MahApps.Metro/Controls/ToggleSwitchButton.cs

Always update thumb position for ToggleSwitchButton after drag
Not sure if this does not break anything, really.
#3458

Always update thumb position after drag

---

readme.md

Added link to Certify The Web as another example

Add to linked examples

---

src/MahApps.Metro/Controls/HamburgerMenu/HamburgerMenu.EventArgs.cs
src/MahApps.Metro/Controls/HamburgerMenu/HamburgerMenu.Events.cs

Allow cancelling the item click for HamburgerMenu items. This can be done e.g. by
```csharp
private void HamburgerMenuControl_OnItemInvoked(object sender, HamburgerMenuItemInvokedEventArgs e)
{
if (somethingNotAllowed) {
e.Handled = true;
return;
}
this.HamburgerMenuControl.Content = e.InvokedItem;
}
```
Closes #3457

(GH-3457) Allow cancelling the item click for HamburgerMenu items

---

src/MahApps.Metro/Controls/Dialogs/InputDialog.xaml.cs
src/MahApps.Metro/Controls/Dialogs/LoginDialog.xaml.cs
src/MahApps.Metro/Controls/Dialogs/MessageDialog.xaml.cs

Mimics the behavior of Escape on all dialogs.
Fix #3252

Close dialogs with Alt+F4

---

src/MahApps.Metro/MahApps.Metro.csproj

Ensure that there is a backslash between nuget path and tool folder
Fix #3590

(GH-3590) Ensure that there is a backslash between nuget path and tool folder

---

src/MahApps.Metro.Samples/MahApps.Metro.Demo/ExampleViews/DataGridExamples.xaml
src/MahApps.Metro/Controls/DataGridNumericUpDownColumn.cs
src/MahApps.Metro/Styles/Controls.DataGrid.xaml
src/MahApps.Metro/Themes/NumericUpDown.xaml

Add TextAlignment to DataGridNumericUpDownColumn

---

src/MahApps.Metro/Behaviors/WindowsSettingBehavior.cs
src/MahApps.Metro/Styles/Themes/Theme.Template.xaml
src/MahApps.Metro/Themes/MetroWindow.xaml

Fix creating a MetroWindow in a different thread

---

src/MahApps.Metro/Controls/TransitioningContentControl.cs
src/MahApps.Metro/Themes/TransitioningContentControl.xaml

We need also a new state for the start and reset state to get also a fired event of the changed and ended storyboard animation.
Closes #3620

Add a hidden state for TransitioningContentControl

---

src/MahApps.Metro/Styles/Controls.CheckBox.xaml
src/MahApps.Metro/Styles/Controls.ComboBox.xaml
src/MahApps.Metro/Styles/Controls.DatePicker.xaml
src/MahApps.Metro/Styles/Controls.PasswordBox.xaml
src/MahApps.Metro/Styles/Controls.TextBox.xaml
src/MahApps.Metro/Themes/DateTimePicker.xaml

Allow using the attached property CornerRadius for more controls...
- for TextBox and RichTextBox
- for PasswordBox
- for DatePicker
- for DateTimePicker
- for CheckBox
- for ComboBox (changed only the template part)
Closes #3582

Use CornerRadius for some controls

---

src/MahApps.Metro/Styles/Controls.TextBox.xaml

(GH-3646) Fix broken RichTextBox

---

src/MahApps.Metro.Samples/MahApps.Metro.Demo/ExampleViews/TextExamples.xaml
src/MahApps.Metro/Styles/Controls.ComboBox.xaml
src/MahApps.Metro/Styles/Controls.DatePicker.xaml
src/MahApps.Metro/Styles/Controls.PasswordBox.xaml
src/MahApps.Metro/Styles/Controls.TextBox.xaml
src/MahApps.Metro/Styles/Shared.xaml

Share all watermark text message storyboards for all text input controls.
- Add new storyboards `MahApps.Storyboard.EnterGotFocus` and `MahApps.Storyboard.ExitGotFocus`
- Add new storyboards `MahApps.Storyboard.EnterGotFocus.DatePickerTextBox` and `MahApps.Storyboard.ExitGotFocus.DatePickerTextBox`
- Add new storyboards `MahApps.Storyboard.EnterHasText` and `MahApps.Storyboard.ExitHasText`
- Add new storyboards `MahApps.Storyboard.EnterHasText.DatePickerTextBox` and `MahApps.Storyboard.ExitHasText.DatePickerTextBox`

Share watermark text message storyboards

---

src/MahApps.Metro/Themes/WindowCommands.xaml

- Add new style `MahApps.Styles.Button.WindowCommands`
- Add new style `MahApps.Styles.ToggleButton.WindowCommands`
Closes #3681

Add explicit WindowCommand styles for Button/ToggleButton

---

src/MahApps.Metro.Samples/MahApps.Metro.Demo/ExampleViews/TextExamples.xaml
src/MahApps.Metro.Samples/MahApps.Metro.Demo/ExampleViews/TextExamples.xaml.cs

Changed the way the NumericUpDown-Example is presented. 
* Add more options for the user to test
**ToDo:**
**Unit test**
None
_None_

Improve NumericUpDown example

---

build.ps1

Fix Cake build error: Could not find an installer for the 'dotnet' scheme.
We need this slight modification until the Cake itself fixes this.
thx to @gep13
Closes #3702

Fix Cake build error

---

src/MahApps.Metro.Samples/MahApps.Metro.Demo/App.xaml
src/MahApps.Metro/Styles/Controls.Label.xaml

Changed the `Style` of `MahApps.Styles.Label` to enable `ContentCharacterCasing`
**Unit test**
None
None
Closes #3699

Use ContentControlEx at Labels Template to enable ContentCharacterCasing

---

src/MahApps.Metro/Styles/Themes/GeneratorParameters.json

This PR changes to blue color scheme to a "real" blue.
@punker76 we already chatted about this ;-)

Changing blue color scheme to blue

---

src/MahApps.Metro/Behaviors/TiltBehavior.cs
src/MahApps.Metro/Controls/LayoutInvalidationCatcher.cs
src/MahApps.Metro/Controls/Planerator.cs

Fix not updating child when using TiltBehavior, after changing accent or theme.
Closes #3720

Fix not updating child when using TiltBehavior, after changing accent or theme

---

src/MahApps.Metro.Samples/MahApps.Metro.Demo/ExampleViews/ButtonsExample.xaml
src/MahApps.Metro.Samples/MahApps.Metro.Demo/ExampleViews/TextExamples.xaml
src/MahApps.Metro.Samples/MahApps.Metro.Demo/MainWindowViewModel.cs
src/MahApps.Metro/Controls/CustomValidationPopup.cs
src/MahApps.Metro/Controls/Flyout.cs
src/MahApps.Metro/Controls/MetroContentControl.cs
src/MahApps.Metro/Styles/ValidationErrorTemplate.xaml
src/MahApps.Metro/Themes/Badged.xaml
src/MahApps.Metro/Themes/DateTimePicker.xaml
src/MahApps.Metro/Themes/MetroContentControl.xaml

Fix validation popup position after scrolling inside
- ScrollViewer
- TransitioningContentControl
- MetroContentControl
- Flyout
Closes #3356 
Closes #2093 
Closes #2695

(GH-3356, GH-2093) Fix validation popup position after scrolling inside a ScrollViewer

---

src/MahApps.Metro.Samples/MahApps.Metro.Demo/ExampleViews/DataGridExamples.xaml
src/MahApps.Metro.Samples/MahApps.Metro.Demo/ExampleWindows/VSDemo.xaml
src/MahApps.Metro.Samples/MahApps.Metro.Demo/MainWindowViewModel.cs
src/MahApps.Metro.Samples/MahApps.Metro.Demo/ValueConverter/ItemCountConverter.cs
src/MahApps.Metro/Controls/Helper/ExpanderHelper.cs
src/MahApps.Metro/Controls/NumericUpDown.cs
src/MahApps.Metro/Styles/Controls.DataGrid.xaml
src/MahApps.Metro/Styles/Controls.Expander.xaml
src/MahApps.Metro/Styles/VS/Expander.xaml

- Fix Expander visibility when there is no storyboard for collapse and expand
- Search for ScrollViewer at NumericUpDown only when needed
- Fix "Cannot find source for binding with reference..." errors
- DataGrid GroupStyle
+ MahApps.Styles.ToggleButton.ExpanderHeader.Down.DataGrid.GroupItem
+ MahApps.Styles.GroupItem.DataGrid
Closes #3236

Add DataGrid GroupStyle and fix grouping errors

---

src/MahApps.Metro/Styles/Controls.CheckBox.xaml

Change Check Background for CheckBox from Transparent to MahApps.Brushes.ThemeBackground.
Closes #3827

(GH-3827) Change Check Background for CheckBox

---

src/MahApps.Metro/Controls/Flyout.cs

An instruction was duplicated on the same line. This is a nitpick, but I was reading the source code and found this.
Feel free to ignore this PR if you want.

Fixed duplicated instruction

---

.editorconfig
src/MahApps.Metro/Styles/Themes/GeneratorParameters.json

Fix Highlight color for Blue and Purple
Closes #3838

(GH-3838) Fix Highlight color for Blue and Purple

---

src/MahApps.Metro/Controls/Dialogs/BaseMetroDialog.cs
src/MahApps.Metro/Controls/Dialogs/DialogManager.cs
src/MahApps.Metro/Controls/Flyout.cs
src/MahApps.Metro/Controls/MetroWindowHelpers.cs

The problem here was that we don't have an application which normally holds all necessary MahApps resources. External dialogs are based on a dynamically created window that doesn't had these resources. There was also some other null pointer exceptions which are now also fixed.
Thx @damienvanrobaeys for the sample and help.
and also @JM2K69 for the help.
Closes #3500 
Closes #3684 
Closes #3755 
Closes #3861

Fix not showing external dialogs inside Powershell scripts

---

src/MahApps.Metro/Controls/Dialogs/DialogManager.cs

(GH-3865) Fix InvalidOperationException when open a dialog over a child window

---

build.cake
src/MahApps.Metro/Behaviors/TiltBehavior.cs
src/MahApps.Metro/Controls/Dialogs/BaseMetroDialog.cs
src/MahApps.Metro/Controls/Flyout.cs
src/MahApps.Metro/Controls/MetroWindow.cs

Execute ThemeManager changes at the current Dispatcher UI thread.
Closes #3872

Fix ThemeManager changes not working with different (STA) threads

---

src/MahApps.Metro/Styles/Controls.Buttons.xaml
src/MahApps.Metro/Styles/VS/Button.xaml

Use ClipBorder for Buttons which handles the click area correctly.
Closes #3874

Fix Button CornerRadius mouse area

---

src/MahApps.Metro/Converters/MathConverter.cs
src/Mahapps.Metro.Tests/Tests/MathConverterTests.cs

- Check for 0 on division and trace it as warning
- Return DependencyProperty.UnsetValue at convert back methods
- MathConverterTests
Maybe the ConvertBack can be implemented, but not in this PR.
Closes #3888

Fixes for MathConverter

---

src/MahApps.Metro/Controls/TimePicker/DateTimePicker.cs
src/MahApps.Metro/Styles/Controls.Calendar.xaml
src/MahApps.Metro/Themes/DateTimePicker.xaml

- Add missing `BlackoutDates` property to DateTimePicker
- Add also `CalendarStyle` property to allow overriding the style for the Calendar.
- Add new style `MahApps.Styles.Calendar.DateTimePicker`
Closes #3887

(GH-3887) Add missing BlackoutDates to DateTimePicker

---

src/MahApps.Metro/Themes/MetroWindow.xaml

Fix hit testing for window titlebar if ResizeMode is NoResize.
Closes #3901

Fix hit testing for window titlebar if ResizeMode is NoResize

---

readme.md

This pull request adds [WinReform](https://github.com/AKruimink/WinReform) to the list of example application that use MahApps Metro (2.0.0).
Having developed multiple application using MahApps, using both the old 1.6 as well as the new 2.0 release, i know what i look for in an example application.
Although the demo offers everything one could possibly need, for someone that just starts it can be rather overwhelming, and doesn't always give a good sense as to where to start, or how to properly implement it.
That is a good place for example applications, real world applications, build to function, that can show off the framework in a good light and make it easy for people new to the framework or people looking for inspiration to do some knowledge up.
I think (personal bias aside) that …

[RFC] Updates the MahApps example list

---

src/MahApps.Metro.Samples/MahApps.Metro.Demo/HamburgerMenuRipple/HamburgerMenuRipple.xaml
src/MahApps.Metro/Controls/Helper/ItemHelper.cs
src/MahApps.Metro/Styles/Controls.ComboBox.xaml
src/MahApps.Metro/Styles/Controls.ListBox.xaml
src/MahApps.Metro/Styles/Controls.ListView.xaml
src/MahApps.Metro/Styles/Controls.TreeView.xaml
src/MahApps.Metro/Themes/HamburgerMenuTemplate.xaml

- Add ItemHelper.HoverSelectedForegroundBrush property
- Add ItemHelper.HoverForegroundBrush property
- Enable overriding ItemsControl trigger brushes
Closes #3900

Fix/Update ItemHelper property usage

---

src/MahApps.Metro/Controls/DropDownButton.cs
src/MahApps.Metro/Themes/DropDownButton.xaml

Allow set GroupStyle for DropDownButton.
Closes #3913

Allow GroupStyle for DropDownButton

---

src/MahApps.Metro/Styles/Controls.ComboBox.xaml
src/MahApps.Metro/Styles/Controls.DatePicker.xaml
src/MahApps.Metro/Styles/Controls.PasswordBox.xaml
src/MahApps.Metro/Styles/Controls.TextBox.xaml
src/MahApps.Metro/Styles/Themes/Theme.Template.xaml
src/MahApps.Metro/Themes/DateTimePicker.xaml

- Allow overriding Watermark Storyboards and floating text foreground (`MahApps.Brushes.TextBlock.FloatingMessage` brush)
Closes #3868

Allow overriding Watermark Storyboards and floating text foreground

---

src/MahApps.Metro.Samples/MahApps.Metro.Caliburn.Demo/Controls/StartupTasks.cs
src/MahApps.Metro.Samples/MahApps.Metro.Caliburn.Demo/Controls/ViewLocator.cs
src/MahApps.Metro/Styles/Controls.ComboBox.xaml
src/MahApps.Metro/Styles/Controls.DatePicker.xaml
src/MahApps.Metro/Styles/Controls.PasswordBox.xaml
src/MahApps.Metro/Styles/Controls.TextBox.xaml

Do not use DynamicResource to get Storyboards inside Triggers. Because this is not possible if there is no App or the resources not being added to the App.xaml.
Closes #3954

Do not use DynamicResource to get Storyboards inside Triggers

---

src/MahApps.Metro.Samples/MahApps.Metro.Demo/ExampleWindows/CleanWindowDemo.xaml
src/MahApps.Metro/Themes/ColorPicker/ColorPicker.xaml
src/MahApps.Metro/Themes/ToggleSwitch.xaml

Use HeaderedControlHelper.HeaderForeground to set the Header Foreground of the ToggleSwitch.
Closes #3961

Use HeaderedControlHelper.HeaderForeground for ToggleSwitch

---

src/MahApps.Metro/Controls/ColorPicker/ColorEyeDropper.cs

added `SelectedColorChangedEvent` to `ColorEyeDropper`
Closes #3977

Add SelectedColorChangedEvent to ColorEyeDropper

---

src/MahApps.Metro.Samples/MahApps.Metro.Demo/ExampleViews/OtherExamples.xaml
src/MahApps.Metro.Samples/MahApps.Metro.Demo/ExampleViews/OtherExamples.xaml.cs
src/MahApps.Metro/Controls/FlipView.cs
src/MahApps.Metro/Controls/FlipViewItem.cs
src/MahApps.Metro/Themes/FlipView.xaml
src/MahApps.Metro/Themes/Generic.xaml

- Add BannerBackground and BannerForeground
- Add BannerOpacity
- Change type of BannerText to object
- Improve FlipViewItem
- Add a default style
- Add a BannerText property
- Allow changing content for navigation buttons
- Allow changing the banner content via template and string format
- Allow set the navigation button style
- Fix mouse over trigger
Closes #3910

More changable properties for FlipView

---

src/MahApps.Metro.Samples/MahApps.Metro.Demo/ExampleViews/OtherExamples.xaml
src/MahApps.Metro.Samples/MahApps.Metro.Demo/Markup/EnumBindingSourceExtension.cs
src/MahApps.Metro/Controls/FlipView.cs
src/MahApps.Metro/Controls/NavigationIndexPlacement.cs
src/MahApps.Metro/Themes/FlipView.xaml

Add Navigation Index to FlipView

Add Navigation Index to FlipView

---

src/MahApps.Metro.Samples/MahApps.Metro.Demo/ExampleViews/OtherExamples.xaml
src/MahApps.Metro/Styles/Controls.DataGrid.xaml

Fix DataGridComboBoxColumn Selection Issue.
- Set IsSynchronizedWithCurrentItem to false by default.
Closes #3982

Fix DataGridComboBoxColumn Selection Issue

---

src/MahApps.Metro/Controls/Dialogs/DialogManager.cs
src/MahApps.Metro/Controls/Dialogs/InputDialog.xaml
src/MahApps.Metro/Controls/Dialogs/LoginDialog.xaml

- Fix ignoring MaxHeight for Dialogs
- Fix vertical Button position for Input and Login Dialogs
Closes #3967

Fix ignoring MaxHeight for Dialogs

---

src/MahApps.Metro.Samples/MahApps.Metro.Demo/App.xaml
src/MahApps.Metro/Controls/Helper/ControlsHelper.cs
src/MahApps.Metro/Themes/ColorPicker/ColorPalette.xaml

- Add missing style `MahApps.Styles.ColorPalette.ColorPickerDropDown`
- Allow override of ContentCharacterCasing property for ColorPalette
Closes #3985

Fix ColorPalette of ColorPicker

---

src/MahApps.Metro.Samples/MahApps.Metro.Demo/ExampleViews/ColorPickerExample.xaml
src/MahApps.Metro/Controls/ColorPicker/ColorPicker.cs
src/MahApps.Metro/Controls/ColorPicker/ColorPickerBase.cs

Fix InvalidCastException at ColorPicker when a DefaultColor is set.
Closes #3986

Fix InvalidCastException at ColorPicker when a DefaultColor is set

---

src/MahApps.Metro/Controls/ColorPicker/BuildInColorPalettes.cs

Fixes Issue #3991 
None
This reverts one of the last recent changes which seems to cause this issue. @punker76 I know you do not like this solution but I have no other 😒 
Closes #3991 
Happy coding
Tim

Fix RecentColor - Issue

---

src/MahApps.Metro/Themes/ColorPicker/ColorEyeDropper.xaml
src/MahApps.Metro/Themes/ColorPicker/ColorPalette.xaml
src/MahApps.Metro/Themes/ColorPicker/ColorPicker.xaml

- Fix wrong background for ColorPaletteItem (MahApps.Brushes.White doesn't exist)
- MahApps.Sizes.ColorListBox.ItemWidth and MahApps.Sizes.ColorListBox.ItemHeight are already defined
- Use Uri style for Eyedropper cursor

Minor ColorPicker / ColorPalette fixes

---

src/MahApps.Metro/Themes/DateTimePicker.xaml

Fixed the issue by changing DynamicResource for the Storybord DataTrigger in DateTimePicker.xaml to StaticResource.
Changes made by Tobias Ernst @TSerious
Closes #4065

Fix issue #4065

---

src/MahApps.Metro/Behaviors/WindowsSettingBehavior.cs
src/MahApps.Metro/Controls/Extensions.cs

After upgrading to version 2.4.4 I've noticed a change which prevents you from creating a window I a different thread. This will fix this issue. by adding an additional Dispatcher.Invoke call.
Closes #4072

Fixed issue #4072

---

src/MahApps.Metro/Controls/FontIcon.cs
src/MahApps.Metro/Controls/IconElement.cs
src/MahApps.Metro/Controls/MetroNavigationWindow.xaml
src/MahApps.Metro/Controls/PathIcon.cs
src/MahApps.Metro/Styles/Controls.CheckBox.xaml
src/MahApps.Metro/Themes/FontIcon.xaml
src/MahApps.Metro/Themes/Generic.xaml
src/MahApps.Metro/Themes/PathIcon.xaml

Update FontIcon and add new PathIcon control.
- Inherit Foreground from visual parent for IconElement and FontIcon
- Add PathIcon control

Update FontIcon and add new PathIcon control

---

src/MahApps.Metro.Samples/MahApps.Metro.Demo/ExampleViews/TextExamples.xaml
src/MahApps.Metro.Samples/MahApps.Metro.Demo/ExampleWindows/ShowcaseFlyout.xaml
src/MahApps.Metro/Controls/Icons/FontIcon.cs
src/MahApps.Metro/Controls/Icons/IconElement.cs
src/MahApps.Metro/Controls/Icons/PathIcon.cs
src/MahApps.Metro/Styles/Controls.ContentControl.xaml
src/MahApps.Metro/Styles/Controls.DatePicker.xaml
src/MahApps.Metro/Styles/Controls.PasswordBox.xaml
src/MahApps.Metro/Styles/Controls.TabControl.xaml
src/MahApps.Metro/Styles/Controls.TextBox.xaml
src/MahApps.Metro/Themes/DateTimePicker.xaml
src/MahApps.Metro/Themes/DropDownButton.xaml
src/MahApps.Metro/Themes/Flyout.xaml
src/MahApps.Metro/Themes/HamburgerMenu.xaml
src/MahApps.Metro/Themes/SplitButton.xaml

Remove MahApps.Styles.ContentControl.PathIcon and use PathIcon instead. Also move classes to it's own folder.

Remove MahApps.Styles.ContentControl.PathIcon and use PathIcon instead

---

src/MahApps.Metro.Samples/MahApps.Metro.Demo/ExampleViews/TextExamples.xaml
src/MahApps.Metro/Controls/CustomValidationPopup.cs

Fix position of ValidationErrorTemplate together with ValidatesOnExceptions.
Closes #4120

Fix position of ValidationErrorTemplate together with ValidatesOnExceptions

---

src/MahApps.Metro/Controls/Dialogs/BaseMetroDialog.cs
src/MahApps.Metro/Styles/Themes/Theme.Template.xaml
src/MahApps.Metro/Themes/Dialogs/BaseMetroDialog.xaml

Add new dialog brush keys:
- MahApps.Brushes.Dialog.Background
- MahApps.Brushes.Dialog.Foreground
- MahApps.Brushes.Dialog.Background.Accent
- MahApps.Brushes.Dialog.Foreground.Accent
- MahApps.Brushes.Dialog.Glow

Add new dialog brush keys

---

src/MahApps.Metro/Styles/Clean/WindowCommands.xaml
src/MahApps.Metro/Styles/Controls.Buttons.xaml
src/MahApps.Metro/Styles/Controls.DataGrid.xaml
src/MahApps.Metro/Styles/Controls.Expander.xaml
src/MahApps.Metro/Styles/Controls.GroupBox.xaml
src/MahApps.Metro/Styles/Controls.ListView.xaml
src/MahApps.Metro/Styles/Fonts.xaml
src/MahApps.Metro/Styles/VS/Expander.xaml
src/MahApps.Metro/Styles/VS/GroupBox.xaml
src/MahApps.Metro/Themes/ColorPicker/ColorEyeDropper.xaml
src/MahApps.Metro/Themes/ColorPicker/ColorPalette.xaml
src/MahApps.Metro/Themes/Dialogs/BaseMetroDialog.xaml
src/MahApps.Metro/Themes/HotKeyBox.xaml
src/MahApps.Metro/Themes/WindowCommands.xaml
src/Mahapps.Metro.Tests/MahApps.Metro.Tests.csproj

Add new CharacterCasing keys:
- MahApps.CharacterCasing.Button
- MahApps.CharacterCasing.Button.Square
- MahApps.CharacterCasing.Button.Dialogs
- MahApps.CharacterCasing.Button.Dialogs.Accent
- MahApps.CharacterCasing.Button.Dialogs.AccentHighlight
- MahApps.CharacterCasing.DataGridColumnHeader
- MahApps.CharacterCasing.Expander
- MahApps.CharacterCasing.Expander.VisualStudio
- MahApps.CharacterCasing.GroupBox
- MahApps.CharacterCasing.GroupBox.VisualStudio
- MahApps.CharacterCasing.GridViewColumnHeader
- MahApps.CharacterCasing.ColorEyeDropper
- MahApps.CharacterCasing.ColorPalette
- MahApps.CharacterCasing.HotKeyBox
- MahApps.CharacterCasing.WindowCommands
- MahApps.CharacterCasing.WindowCommands.Clean
Closes #4126

Add new CharacterCasing keys

---

src/MahApps.Metro/MahApps.Metro.csproj
src/Mahapps.Metro.Tests/MahApps.Metro.Tests.csproj

Caused by changed invocation order with SDK version 5.0.301...

Fix compile

---

src/MahApps.Metro.Samples/MahApps.Metro.Demo/MainWindow.xaml.cs
src/MahApps.Metro.Samples/MahApps.Metro.Demo/Models/ThemeResource.cs
src/MahApps.Metro/Controls/Dialogs/ProgressDialogController.cs
src/MahApps.Metro/Controls/VisualStates.cs

Cancel Progress dialog on Escape button.
Closes #4114

Cancel Progress dialog on Escape button

---

src/MahApps.Metro/Converters/ThicknessFilterConverter.cs
src/MahApps.Metro/Styles/Controls.ComboBox.xaml
src/MahApps.Metro/Styles/Controls.ContextMenu.xaml
src/MahApps.Metro/Styles/Controls.Menu.xaml
src/MahApps.Metro/Styles/Controls.MenuItem.xaml
src/MahApps.Metro/Styles/Controls.Tooltip.xaml
src/MahApps.Metro/Styles/VS/ContextMenu.xaml
src/MahApps.Metro/Styles/VS/Menu.xaml
src/MahApps.Metro/Styles/VS/MenuItem.xaml

- Add ComboBoxPopupBorderThemeCornerRadius to allow changing corner radius for Popup border
- Allow setting the corner radius for ContextMenu and MenuItem 
- Allow setting the corner radius for Menu
WIP
Closes #4181

Allow setting corner radius for additional controls

---

src/MahApps.Metro/Controls/Helper/ExpanderHelper.cs
src/MahApps.Metro/Styles/Controls.Expander.xaml
src/MahApps.Metro/Styles/VS/Expander.xaml

Allow toggle the arrow and circle of the expander header.
- Add a new attached dependency property `ShowToggleButton` to the `ExpanderHelper`
Closes #4177

Allow toggle the arrow and circle of the expander header

---

src/MahApps.Metro.Samples/MahApps.Metro.Demo/MainWindow.xaml
src/MahApps.Metro.Samples/MahApps.Metro.Demo/MainWindowViewModel.cs
src/MahApps.Metro/Controls/MetroWindow.cs

Call CoerceValue for ShowTitleBarProperty to return to the correct value.
Closes #4169

Toggle UseNoneWindowStyle should return to correct state of ShowTitleBar

---

src/MahApps.Metro/Automation/Peers/ProgressRingAutomationPeer.cs
src/MahApps.Metro/Controls/ProgressRing.cs

Add an automation peer for the ProgressRing control.
Closes #4212

Add an automation peer for the ProgressRing control

---

src/MahApps.Metro.Samples/MahApps.Metro.Demo/ExampleViews/ButtonsExample.xaml
src/MahApps.Metro/Styles/Controls.Buttons.xaml

Improve flat toggle button disabled checked style.
Closes #4211

Improve flat toggle button disabled checked style

---

src/MahApps.Metro.Samples/MahApps.Metro.Demo/MainWindow.xaml.cs
src/MahApps.Metro/Controls/Dialogs/BaseMetroDialog.cs
src/MahApps.Metro/Controls/Dialogs/DialogManager.cs
src/MahApps.Metro/Controls/Dialogs/DialogStateChangedEventArgs.cs
src/MahApps.Metro/Controls/Dialogs/InputDialog.cs
src/MahApps.Metro/Controls/Dialogs/LoginDialog.cs
src/MahApps.Metro/Controls/Dialogs/MessageDialog.cs
src/MahApps.Metro/Controls/Dialogs/MetroDialogSettings.cs
src/MahApps.Metro/Controls/Dialogs/ProgressDialog.cs
src/MahApps.Metro/Controls/Helper/AccessKeyHelper.cs
src/MahApps.Metro/Controls/MetroWindow.cs
src/MahApps.Metro/Themes/Dialogs/LoginDialog.xaml
src/MahApps.Metro/Themes/Dialogs/ProgressDialog.xaml

- Simplify async show methods
- Simplify async overlay methods
- Simplify WaitForButtonPressAsync methods
- Fix keyboard navigation if dialog is open (#2400)
- Fix using access keys (mnemonics) in dialogs (#2400)
Closes #2400

Refactoring and fixing dialogs

---

.github/workflows/ci.yml
appveyor.yml
build.cake
readme.md
src/Directory.Build.Props
src/MahApps.Metro.Samples/MahApps.Metro.Caliburn.Demo/FodyWeavers.xsd
src/MahApps.Metro.Samples/MahApps.Metro.Caliburn.Demo/MahApps.Metro.Caliburn.Demo.csproj
src/MahApps.Metro.Samples/MahApps.Metro.Demo/ExampleWindows/CleanWindowDemo.xaml.cs
src/MahApps.Metro.Samples/MahApps.Metro.Demo/FodyWeavers.xsd
src/MahApps.Metro.Samples/MahApps.Metro.Demo/MahApps.Metro.Demo.csproj
src/MahApps.Metro.Samples/MahApps.Metro.Demo/MainWindowViewModel.cs
src/MahApps.Metro/Controls/MetroNavigationWindow.xaml.cs
src/global.json

Add the .NET 6 target framework.
Closes #4222

Add .NET 6 target framework

---

src/MahApps.Metro/Controls/RangeSlider.cs

Fix incorrect visuals after changing visibility by recalculate sizes for all visuals.
Closes #4210

Fix incorrect visuals after changing visibility

---

src/MahApps.Metro/Themes/HamburgerMenuTemplate.xaml

Fix the Hamburger visibility if the DisplayMode of a HamburgerMenu is set to Overlay and the IsPaneOpen property is set to False.
Closes #4093

Fix HamburgerButton visibility

---

src/MahApps.Metro.Samples/MahApps.Metro.Demo/Navigation/HomePage.xaml
src/MahApps.Metro.Samples/MahApps.Metro.Demo/Navigation/InterestingPage.xaml
src/MahApps.Metro.sln.DotSettings
src/MahApps.Metro/Controls/MetroNavigationWindow.xaml
src/MahApps.Metro/Controls/MetroNavigationWindow.xaml.cs

Add dependency property ShowsNavigationUI to MetroNavigationWindow to enable/disable the navigation buttons.
Closes #1786

Add ShowsNavigationUI to navigation window

---

src/MahApps.Metro.Samples/MahApps.Metro.Demo/MainWindow.xaml.cs
src/MahApps.Metro.Samples/MahApps.Metro.Demo/Navigation/HomePage.xaml
src/MahApps.Metro/Controls/MetroNavigationWindow.xaml
src/MahApps.Metro/Controls/MetroNavigationWindow.xaml.cs

Add home button to MetroNavigationWindow.
Closes #3052

Add home button to MetroNavigationWindow

---

src/MahApps.Metro.Samples/MahApps.Metro.Demo/ExampleViews/TextExamples.xaml
src/MahApps.Metro/Styles/Controls.ComboBox.xaml
src/MahApps.Metro/Styles/Controls.DatePicker.xaml
src/MahApps.Metro/Styles/Controls.PasswordBox.xaml
src/MahApps.Metro/Styles/Controls.TextBox.xaml
src/MahApps.Metro/Themes/ColorPicker/ColorPicker.xaml
src/MahApps.Metro/Themes/DateTimePicker.xaml
src/MahApps.Metro/Themes/MultiSelectionComboBox.xaml

Add fallback value to floating message converters
- MathSubtractConverter
- MathMultiplyConverter
Closes #4217

Add fallback value to floating message converters

---

src/MahApps.Metro.sln.DotSettings
src/MahApps.Metro/Controls/MetroHeader.cs
src/MahApps.Metro/Themes/MetroHeader.xaml

Add orientation property to MetroHeader.

Add orientation property to MetroHeader

---

src/Directory.Build.Props

Add the net48 as a target framework
Closes #4249

Add net48 target framework

---

readme.md

I have added a couple of projects of mine that use MahApps to the Examples section of the readme
N/A
N/A
N/A

Updated readme with some additional examples

---

src/MahApps.Metro/Styles/Controls.RichTextBox.xaml
src/MahApps.Metro/Styles/Controls.xaml

BREAKING CHANGE: move RichTextBox style to it's own resource file

Move RichTextBox style to it's own resource file

---

src/MahApps.Metro.Samples/MahApps.Metro.Demo/ExampleViews/SelectionExamples.xaml
src/MahApps.Metro/Controls/Helper/ItemHelper.cs
src/MahApps.Metro/Styles/Controls.Buttons.xaml
src/MahApps.Metro/Styles/Controls.ListBox.xaml

Add also new attached properties to ItemHelper to set the different border brush states
- ActiveSelectionBorderBrush
- SelectedBorderBrush
- HoverBorderBrush
- HoverSelectedBorderBrush
- DisabledSelectedBorderBrush
- DisabledBorderBrush
- MouseLeftButtonPressedBorderBrush
- MouseRightButtonPressedBorderBrush
```xaml
<ListBox AlternationCount="2"
BorderThickness="1"
Style="{StaticResource MahApps.Styles.ListBox.Virtualized}">
<ListBox.ItemContainerStyle>
<Style BasedOn="{StaticResource MahApps.Styles.ListBoxItem}" TargetType="{x:Type ListBoxItem}">
<Setter Property="BorderBrush" Value="{StaticResource MahApps.Brushes.Gray1}" />
<Setter Property="BorderThickness" Value="1" />
<Setter Property="Margin" Value="2" />
<Setter Property="mah:ControlsHelper.CornerRadius" Value="4" />
<Setter …
```

feat: #4288 allow set the corner radius of a ListBoxItem

---

src/MahApps.Metro.Samples/MahApps.Metro.Demo/MainWindow.xaml
src/MahApps.Metro/Styles/Controls.Slider.xaml
src/MahApps.Metro/Themes/RangeSlider.xaml

Add new double values to allow set the thumb size:
- MahApps.Sizes.Slider.HorizontalThumb.Height.Win10 = 24
- MahApps.Sizes.Slider.HorizontalThumb.Width.Win10 = 8
- MahApps.Sizes.Slider.VerticalThumb.Width.Win10 = 24
- MahApps.Sizes.Slider.VerticalThumb.Height.Win10 = 8
Closes #4287

Allow set the thumb height of the Win10 slider style

---

readme.md

Fix description of FolderSecurityViewer in readme.md

docs: fix description of FolderSecurityViewer in readme

---

src/MahApps.Metro/MahApps.Metro.csproj

Update ControlzEx to the latest preview

Updating ControlzEx

---

src/MahApps.Metro.Samples/MahApps.Metro.Demo/MainWindow.xaml
src/MahApps.Metro/Automation/Peers/MetroDialogAutomationPeer.cs
src/MahApps.Metro/Controls/Dialogs/BaseMetroDialog.cs
src/MahApps.Metro/Controls/Dialogs/DialogManager.cs
src/MahApps.Metro/Controls/Dialogs/ProgressDialogController.cs
src/MahApps.Metro/Styles/Controls.Buttons.xaml
src/MahApps.Metro/Themes/Dialogs/BaseMetroDialog.xaml
src/MahApps.Metro/Themes/MetroWindow.xaml
src/MahApps.Metro/Themes/WindowButtonCommands.xaml
src/Mahapps.Metro.Tests/MahApps.Metro.Tests.csproj
src/Mahapps.Metro.Tests/Tests/CustomDialogTest.cs
src/Mahapps.Metro.Tests/Views/DialogCustomTitleWindow.xaml
src/Mahapps.Metro.Tests/Views/DialogCustomTitleWindow.xaml.cs

Adding the ability for the dialog title to contain arbitrary content

---

src/MahApps.Metro/Controls/MultiSelectionComboBox/MultiSelectionComboBox.cs

fix: #4363 MultiSelectionComboBox item duplicating

---

src/MahApps.Metro/Controls/Helper/ControlsHelper.cs
src/MahApps.Metro/Themes/MultiSelectionComboBox.xaml

Fix #4375 
None
None
Fixes #4375

fix for GH #4375

---

src/Directory.packages.props
src/MahApps.Metro.Samples/MahApps.Metro.Demo/ExampleWindows/FlyoutDemo.xaml.cs
src/MahApps.Metro/Behaviors/WindowsSettingBehavior.cs
src/MahApps.Metro/Controls/MetroWindow.cs
src/MahApps.Metro/Controls/WinApiHelper.cs
src/MahApps.Metro/Controls/WindowSettings.cs

Add the `Reset` method to the `IWindowPlacementSettings` interface to allow reset the window settings.
Window settings behavior should be initialized after all other behaviors. Add also the missing length for new created window placement.
Closes #4359

Allow to reset the window settings

---

src/MahApps.Metro/Controls/ColorPicker/ColorPickerBase.cs

Fix an issue with `ColorPicker`, where `Hue` value was not updated in some cases
Fixes #4402

Fix HSV-Invalidation

---

.config/dotnet-tools.json
.github/workflows/ci.yml
appveyor.yml
build.cake
build.ps1
src/Directory.Build.Props
src/Directory.Build.Targets
src/Directory.packages.props
src/Mahapps.Metro.Tests/MahApps.Metro.Tests.csproj
src/Mahapps.Metro.Tests/Tests/AnimatedTabControlTest.cs
src/Mahapps.Metro.Tests/Tests/AutoWatermarkTest.cs
src/Mahapps.Metro.Tests/Tests/ButtonTests.cs
src/Mahapps.Metro.Tests/Tests/CleanWindowTest.cs
src/Mahapps.Metro.Tests/Tests/HeaderedControlHelperTests.cs
src/Mahapps.Metro.Tests/Tests/MultiSelectorHelperTests.cs
src/Mahapps.Metro.Tests/Tests/NumericUpDownTests.cs
src/Mahapps.Metro.Tests/Tests/TextBoxHelperTests.cs
src/Mahapps.Metro.Tests/Tests/TileTest.cs

- remove .NET Core 3.1 support
- update cake and cake script
- update package references

Housekeeping

---

src/MahApps.Metro/Themes/MultiSelectionComboBox.xaml

Currently MultiSelectionComboBox drop down height is always 200 and can't be changed. It should respect MaxDropDownHeight value. 
Change would make behavior similar to ComboBox style

Make MultiSelectionComboBox DropDown respect MaxDropDownHeight value
